import type { TermSeed } from './content-types';

const groups: Record<string, string[]> = {
  'konsep dasar keselamatan': ['bahaya|Bahaya','risiko|Risiko','insiden|Insiden','kecelakaan-kerja|Kecelakaan Kerja','near-miss|Near Miss','unsafe-action|Unsafe Action','unsafe-condition|Unsafe Condition','paparan|Paparan','konsekuensi|Konsekuensi','kemungkinan|Kemungkinan','pengendalian|Pengendalian','risiko-sisa|Risiko Sisa','risiko-awal|Risiko Awal','sumber-bahaya|Sumber Bahaya','skenario-risiko|Skenario Risiko','tindakan-korektif|Tindakan Korektif','tindakan-pencegahan|Tindakan Pencegahan','akar-penyebab|Akar Penyebab','penyebab-langsung|Penyebab Langsung','stop-work-authority|Stop Work Authority'],
  'metode penilaian risiko': ['hira|HIRA','hiradc|HIRADC','ibpr|IBPR','jsa|JSA','jha|JHA','hazid|HAZID','hazop|HAZOP','fmea|FMEA','fta|Fault Tree Analysis','eta|Event Tree Analysis','bowtie|Bowtie Analysis','lopa|LOPA','what-if|What-if Analysis','risk-matrix|Matriks Risiko','alarp|ALARP','risk-register|Risk Register','critical-control|Critical Control','barrier|Barrier','barrier-performance-standard|Barrier Performance Standard','risk-appetite|Risk Appetite'],
  'sistem dan tata kelola K3': ['smk3|SMK3','iso-45001|ISO 45001','p2k3|P2K3','csms|CSMS','moc|Management of Change','ptw|Permit to Work','legal-register|Legal Register','kebijakan-k3|Kebijakan K3','sasaran-k3|Sasaran K3','program-k3|Program K3','tinjauan-manajemen|Tinjauan Manajemen','audit-k3|Audit K3','inspeksi-k3|Inspeksi K3','kepatuhan-k3|Kepatuhan K3','konsultasi-pekerja|Konsultasi Pekerja','partisipasi-pekerja|Partisipasi Pekerja','budaya-k3|Budaya K3','due-diligence-k3|Due Diligence K3','assurance-k3|Assurance K3','continuous-improvement|Perbaikan Berkelanjutan'],
  'indikator dan statistik keselamatan': ['man-hours|Man-hours','safe-man-hours|Safe Man-hours','frequency-rate|Frequency Rate','severity-rate|Severity Rate','ltifr|LTIFR','trir|TRIR','lost-time-injury|Lost Time Injury','restricted-work-case|Restricted Work Case','medical-treatment-case|Medical Treatment Case','first-aid-case|First Aid Case','fatality-rate|Fatality Rate','incident-rate|Incident Rate','leading-indicator|Leading Indicator','lagging-indicator|Lagging Indicator','total-recordable-case|Total Recordable Case','days-away-from-work|Days Away from Work','exposure-hours|Exposure Hours','normalisasi-data|Normalisasi Data','baseline-kinerja|Baseline Kinerja','target-k3|Target K3'],
  'higiene industri dan pajanan': ['nilai-ambang-batas|Nilai Ambang Batas','twa|Time Weighted Average','stel|Short Term Exposure Limit','ceiling-limit|Ceiling Limit','wbgt|WBGT','isbb|ISBB','ppm|Parts per Million','mg-m3|Miligram per Meter Kubik','dba|dBA','lux|Lux','noise-dose|Dosis Kebisingan','oel|Occupational Exposure Limit','tlv|Threshold Limit Value','similar-exposure-group|Similar Exposure Group','personal-sampling|Personal Sampling','area-sampling|Area Sampling','industrial-hygiene|Higiene Industri','heat-stress|Tekanan Panas','cold-stress|Tekanan Dingin','biological-monitoring|Biological Monitoring'],
  'keselamatan bahan kimia': ['sds|Safety Data Sheet','ghs|Globally Harmonized System','piktogram-ghs|Piktogram GHS','flash-point|Flash Point','autoignition-temperature|Autoignition Temperature','lel|Lower Explosive Limit','uel|Upper Explosive Limit','acute-toxicity|Toksisitas Akut','chronic-toxicity|Toksisitas Kronis','carcinogen|Karsinogen','mutagen|Mutagen','reproductive-toxin|Toksikan Reproduksi','sensitizer|Sensitizer','corrosive|Korosif','oxidizer|Oksidator','flammable-liquid|Cairan Mudah Terbakar','chemical-incompatibility|Inkompatibilitas Kimia','secondary-container|Wadah Sekunder','spill-kit|Spill Kit','chemical-inventory|Inventaris Bahan Kimia'],
  'proteksi dan penanggulangan kebakaran': ['fire-triangle|Segitiga Api','fire-tetrahedron|Tetrahedron Api','fire-load|Beban Kebakaran','flashover|Flashover','backdraft|Backdraft','fire-compartment|Kompartemen Kebakaran','apar|APAR','hydrant|Hidran','sprinkler|Sprinkler','fire-alarm|Alarm Kebakaran','smoke-detector|Detektor Asap','heat-detector|Detektor Panas','fire-pump|Pompa Kebakaran','fire-door|Pintu Tahan Api','fire-warden|Fire Warden','muster-point|Titik Kumpul','means-of-egress|Sarana Jalan Keluar','fire-watch|Fire Watch','hot-work|Hot Work','ignition-source|Sumber Penyalaan'],
  'alat pelindung diri dan pernapasan': ['apd|Alat Pelindung Diri','respirator|Respirator','apr|Air Purifying Respirator','papr|Powered Air Purifying Respirator','scba|Self Contained Breathing Apparatus','apf|Assigned Protection Factor','fit-factor|Fit Factor','fit-test|Fit Test','cartridge|Kartrid Respirator','breakthrough-time|Breakthrough Time','full-face-respirator|Full Face Respirator','half-mask-respirator|Half Mask Respirator','particulate-filter|Filter Partikulat','safety-helmet|Helm Keselamatan','safety-glasses|Kacamata Keselamatan','face-shield|Pelindung Wajah','hearing-protection|Pelindung Pendengaran','chemical-gloves|Sarung Tangan Kimia','safety-shoes|Sepatu Keselamatan','ppe-compatibility|Kompatibilitas APD'],
  'bekerja di ketinggian': ['fall-factor|Fall Factor','fall-clearance|Fall Clearance','anchor-point|Anchor Point','lifeline|Lifeline','lanyard|Lanyard','srl|Self Retracting Lifeline','energy-absorber|Energy Absorber','suspension-trauma|Suspension Trauma','scaffolding-tag|Scaffolding Tag','guardrail|Guardrail','toe-board|Toe Board','working-platform|Platform Kerja','work-positioning|Work Positioning','rope-access|Akses Tali','fall-restraint|Fall Restraint','fall-arrest|Fall Arrest','horizontal-lifeline|Horizontal Lifeline','vertical-lifeline|Vertical Lifeline','double-lanyard|Double Lanyard','rescue-plan|Rencana Penyelamatan'],
  'ruang terbatas': ['confined-space|Ruang Terbatas','entrant|Entrant','attendant|Attendant','entry-supervisor|Entry Supervisor','atmospheric-testing|Pengujian Atmosfer','oxygen-deficiency|Kekurangan Oksigen','oxygen-enrichment|Pengayaan Oksigen','inerting|Inerting','purging|Purging','blanking|Blinding dan Blanking','double-block-and-bleed|Double Block and Bleed','continuous-monitoring|Pemantauan Berkelanjutan','gas-tester|Gas Tester','entry-permit|Izin Masuk','retrieval-system|Sistem Retrieval','tripod-rescue|Tripod Rescue','standby-person|Standby Person','ventilation|Ventilasi','stratification|Stratifikasi Gas','prohibited-condition|Kondisi Terlarang'],
  'operasi pengangkatan': ['swl|Safe Working Load','wll|Working Load Limit','load-chart|Load Chart','center-of-gravity|Pusat Gravitasi','sling-angle|Sudut Sling','d-d-ratio|Rasio D/d','rigging-plan|Rigging Plan','critical-lift|Critical Lift','tag-line|Tag Line','outrigger|Outrigger','ground-bearing-pressure|Ground Bearing Pressure','spreader-beam|Spreader Beam','lifting-beam|Lifting Beam','shackle|Shackle','wire-rope|Wire Rope','synthetic-sling|Synthetic Sling','chain-sling|Chain Sling','proof-load|Proof Load','dynamic-load|Beban Dinamis','exclusion-zone|Zona Eksklusi'],
  'keselamatan listrik dan energi': ['loto|Lockout Tagout','arc-flash|Arc Flash','arc-blast|Arc Blast','touch-voltage|Touch Voltage','step-voltage|Step Voltage','earthing|Pembumian','bonding|Bonding','rcd|Residual Current Device','elcb|Earth Leakage Circuit Breaker','energized-work|Pekerjaan Bertegangan','zero-energy-state|Zero Energy State','stored-energy|Energi Tersimpan','electrical-isolation|Isolasi Listrik','mechanical-isolation|Isolasi Mekanis','try-out|Try-out Verification','single-line-diagram|Single Line Diagram','insulation-resistance|Tahanan Isolasi','short-circuit|Hubung Singkat','overcurrent-protection|Proteksi Arus Lebih','intrinsically-safe|Intrinsically Safe'],
  'kesehatan kerja dan ergonomi': ['penyakit-akibat-kerja|Penyakit Akibat Kerja','health-surveillance|Surveilans Kesehatan','fit-to-work|Fit to Work','return-to-work|Return to Work','ergonomi|Ergonomi','fatigue|Kelelahan Kerja','psychosocial-hazard|Bahaya Psikososial','manual-handling|Manual Handling','musculoskeletal-disorder|Gangguan Muskuloskeletal','repetitive-work|Pekerjaan Repetitif','work-rest-cycle|Siklus Kerja Istirahat','occupational-infection|Infeksi Okupasi','fitness-for-duty|Fitness for Duty','medical-surveillance|Medical Surveillance','health-risk-assessment|Health Risk Assessment','hearing-conservation|Konservasi Pendengaran','respiratory-protection-program|Program Perlindungan Pernapasan','workplace-wellbeing|Kesejahteraan di Tempat Kerja','occupational-stress|Stres Kerja','job-demand|Tuntutan Kerja'],
  'keselamatan konstruksi': ['rkk|Rencana Keselamatan Konstruksi','smkk|Sistem Manajemen Keselamatan Konstruksi','temporary-works|Temporary Works','excavation|Penggalian','shoring|Shoring','formwork|Formwork','falsework|Falsework','lifting-zone|Zona Pengangkatan','demolition|Pembongkaran','earthwork|Pekerjaan Tanah','trenching|Trenching','benching|Benching','sloping|Sloping','barricade|Barikade','site-induction|Induksi Proyek','site-logistics|Logistik Proyek','temporary-electricity|Listrik Sementara','work-at-height-plan|Rencana Kerja Ketinggian','scaffold-inspection|Inspeksi Perancah','construction-safety-plan|Rencana Keselamatan Proyek'],
  'sertifikasi dan kompetensi': ['bnsp|BNSP','lsp|Lembaga Sertifikasi Profesi','tuk|Tempat Uji Kompetensi','asesi|Asesi','asesor|Asesor Kompetensi','skema-sertifikasi|Skema Sertifikasi','unit-kompetensi|Unit Kompetensi','skkni|SKKNI','kkni|KKNI','pjk3|PJK3','lisensi-k3|Lisensi K3','skp-k3|SKP K3','sertifikat-kompetensi|Sertifikat Kompetensi','sertifikat-pelatihan|Sertifikat Pelatihan','rekognisi-pembelajaran-lampau|Rekognisi Pembelajaran Lampau','portofolio-asesmen|Portofolio Asesmen','bukti-kompetensi|Bukti Kompetensi','validitas-bukti|Validitas Bukti','reliabilitas-asesmen|Reliabilitas Asesmen','kompetensi|Kompetensi'],
};

const categoryMeaning: Record<string,string> = {
  'konsep dasar keselamatan':'konsep untuk menjelaskan sumber bahaya, kejadian, dampak, dan tindakan pencegahan',
  'metode penilaian risiko':'metode atau unsur analisis yang membantu menyusun skenario, menilai risiko, dan memilih pengendalian',
  'sistem dan tata kelola K3':'unsur tata kelola yang menghubungkan kebijakan, tanggung jawab, pelaksanaan, evaluasi, dan perbaikan',
  'indikator dan statistik keselamatan':'ukuran yang memerlukan definisi kasus, periode, satuan, dan denominator agar dapat dibandingkan',
  'higiene industri dan pajanan':'istilah untuk mengenali, mengukur, menafsirkan, atau mengendalikan pajanan lingkungan kerja',
  'keselamatan bahan kimia':'istilah untuk mengenali sifat bahan, komunikasi bahaya, penyimpanan, penggunaan, dan respons tumpahan',
  'proteksi dan penanggulangan kebakaran':'komponen atau fenomena yang digunakan untuk memahami pencegahan, deteksi, pemadaman, pembatasan, dan evakuasi',
  'alat pelindung diri dan pernapasan':'perangkat atau parameter yang membantu memilih, menggunakan, dan memeriksa perlindungan personal',
  'bekerja di ketinggian':'komponen atau parameter sistem pencegahan jatuh, akses, posisi kerja, dan penyelamatan',
  'ruang terbatas':'peran, kondisi, atau pengendalian dalam perencanaan masuk, pemantauan atmosfer, komunikasi, dan penyelamatan',
  'operasi pengangkatan':'parameter, alat bantu, atau dokumen untuk merencanakan dan melaksanakan pengangkatan sesuai kapasitas',
  'keselamatan listrik dan energi':'konsep untuk mencegah kontak listrik, pelepasan energi, kebakaran, atau cedera saat pekerjaan teknis',
  'kesehatan kerja dan ergonomi':'konsep untuk menilai kesesuaian tuntutan kerja, pajanan, kondisi kesehatan, dan kemampuan pekerja',
  'keselamatan konstruksi':'komponen perencanaan dan pengendalian pekerjaan proyek, struktur sementara, akses, dan perubahan lapangan',
  'sertifikasi dan kompetensi':'istilah yang membedakan lembaga, skema, proses asesmen, bukti, lisensi, dan penunjukan',
};

export const termSeeds: TermSeed[] = Object.entries(groups).flatMap(([category, entries]) => entries.map((entry) => {
  const [slug, term] = entry.split('|');
  return { slug, term, category, definition:`${term} adalah ${categoryMeaning[category]}. Makna spesifiknya ditentukan oleh fungsi, kriteria, atau sumber resmi yang menyertai istilah tersebut.`, example:`Dalam praktik, ${term} dicatat bersama konteks pekerjaan, bukti, kriteria, penanggung jawab, dan keputusan yang dibuat.` };
}));
