import type { RegulationSeed } from './content-types';

const rows = `
uu-1-1970|Undang-Undang Nomor 1 Tahun 1970 tentang Keselamatan Kerja|dasar keselamatan kerja, tempat kerja, kewajiban pengurus, pengawasan, dan pencegahan kecelakaan|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/49/undang-undang-nomor-1-tahun-1970
pp-50-2012|PP Nomor 50 Tahun 2012 tentang Penerapan SMK3|kebijakan, perencanaan, pelaksanaan, evaluasi, audit, dan peningkatan SMK3|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/58/peraturan-pemerintah-nomor-50-tahun-2012
pp-28-2024-kesehatan|PP Nomor 28 Tahun 2024 tentang Pelaksanaan UU Kesehatan|pelaksanaan kerangka kesehatan termasuk aspek kesehatan kerja dan pencabutan PP 88 Tahun 2019|Berlaku; mencabut PP 88 Tahun 2019|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/294077/pp-np-28-tahun-2024
perpres-7-2019-penyakit-akibat-kerja|Perpres Nomor 7 Tahun 2019 tentang Penyakit Akibat Kerja|pengakuan dan klasifikasi penyakit akibat kerja|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1588/peraturan-presiden-nomor-7-tahun-2019
permenaker-13-2025-p2k3|Permenaker Nomor 13 Tahun 2025 tentang P2K3|pembentukan, keanggotaan, fungsi, dan administrasi P2K3|Berlaku; menjadi rujukan P2K3 saat ini|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2788/peraturan-menteri-ketenagakerjaan-nomor-13-tahun-2025
permenaker-4-2025-operator-pesawat-uap|Permenaker Nomor 4 Tahun 2025 tentang Operator Pesawat Uap|kualifikasi, lisensi, kelas, dan operasi pesawat uap|Berlaku; menggantikan aturan operator pesawat uap 1988|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2684/peraturan-menteri-ketenagakerjaan-nomor-4-tahun-2025
permenaker-11-2023-ruang-terbatas|Permenaker Nomor 11 Tahun 2023 tentang K3 di Ruang Terbatas|klasifikasi ruang, izin masuk, pengendalian atmosfer, personel, peralatan, dan penyelamatan|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2412/peraturan-menteri-ketenagakerjaan-nomor-11-tahun-2023
permenaker-13-2022-tuberkulosis|Permenaker Nomor 13 Tahun 2022 tentang Penanggulangan Tuberkulosis di Tempat Kerja|pencegahan, penemuan, penanganan, dan program TB di tempat kerja|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2225/peraturan-menteri-ketenagakerjaan-nomor-13-tahun-2022
permenaker-8-2020-pesawat-angkat-angkut|Permenaker Nomor 8 Tahun 2020 tentang K3 Pesawat Angkat dan Angkut|perencanaan, operasi, pemeriksaan, pengujian, operator, teknisi, dan rigger|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1668/peraturan-menteri-ketenagakerjaan-nomor-8-tahun-2020
permenaker-5-2018-lingkungan-kerja|Permenaker Nomor 5 Tahun 2018 tentang K3 Lingkungan Kerja|faktor fisika, kimia, biologi, ergonomi, psikologi, higiene, sanitasi, dan NAB|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1546/peraturan-menteri-ketenagakerjaan-nomor-5-tahun-2018
permenaker-6-2017-elevator-eskalator|Permenaker Nomor 6 Tahun 2017 tentang K3 Elevator dan Eskalator|pemasangan, pemeriksaan, pengujian, pemeliharaan, dan personel elevator serta eskalator|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1498/peraturan-menteri-ketenagakerjaan-nomor-6-tahun-2017
permenaker-38-2016-pesawat-tenaga-produksi|Permenaker Nomor 38 Tahun 2016 tentang K3 Pesawat Tenaga dan Produksi|mesin, pesawat tenaga, peralatan produksi, operator, pemeriksaan, dan pengujian|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1430/peraturan-menteri-ketenagakerjaan-nomor-38-tahun-2016
permenaker-37-2016-bejana-tekanan|Permenaker Nomor 37 Tahun 2016 tentang K3 Bejana Tekanan dan Tangki Timbun|pembuatan, pemasangan, pemeriksaan, pengujian, operasi, dan personel bejana serta tangki|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1429/peraturan-menteri-ketenagakerjaan-nomor-37-tahun-2016
permenaker-9-2016-ketinggian|Permenaker Nomor 9 Tahun 2016 tentang K3 Pekerjaan pada Ketinggian|perencanaan, prosedur, sistem akses, proteksi jatuh, kompetensi, lisensi, dan penyelamatan|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1210/peraturan-menteri-ketenagakerjaan-nomor-9-tahun-2016
permenaker-33-2015-perubahan-k3-listrik|Permenaker Nomor 33 Tahun 2015 tentang Perubahan K3 Listrik|perubahan ketentuan pada Permenaker Nomor 12 Tahun 2015|Berlaku; dibaca bersama Permenaker 12 Tahun 2015|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1156/peraturan-menteri-ketenagakerjaan-nomor-33-tahun-2015
permenaker-12-2015-k3-listrik|Permenaker Nomor 12 Tahun 2015 tentang K3 Listrik di Tempat Kerja|instalasi, operasi, pemeliharaan, pemeriksaan, pengujian, teknisi, dan Ahli K3 Listrik|Berlaku dengan perubahan Permenaker 33 Tahun 2015|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/610/peraturan-menteri-ketenagakerjaan-nomor-12-tahun-2015
permenaker-26-2014-penilaian-smk3|Permenaker Nomor 26 Tahun 2014 tentang Penilaian Penerapan SMK3|administrasi penilaian dan audit penerapan SMK3|Berlaku; tanggal metadata perlu dibaca dari dokumen resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/577/peraturan-menteri-ketenagakerjaan-nomor-26-tahun-2014
permenaker-8-2010-apd|Permenaker PER.08/MEN/VII/2010 tentang Alat Pelindung Diri|kewajiban pengusaha, penyediaan, pemilihan, penggunaan, dan pengelolaan APD|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/158/peraturan-menteri-nomor-8-tahun-2010
permenaker-25-2008-diagnosis-cacat|Permenaker PER.25/MEN/XII/2008 tentang Diagnosis dan Penilaian Cacat|pedoman diagnosis dan penilaian cacat akibat kecelakaan serta penyakit akibat kerja|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/198/peraturan-menteri-nomor-25-tahun-2008
permenaker-15-2008-p3k|Permenaker PER.15/MEN/VIII/2008 tentang P3K di Tempat Kerja|petugas, fasilitas, jumlah, lisensi, dan penyelenggaraan P3K|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/193/peraturan-menteri-nomor-15-tahun-2008
permenaker-11-2005-p4gn|Permenaker PER.11/MEN/VI/2005 tentang Pencegahan Penyalahgunaan Narkotika di Tempat Kerja|program pencegahan narkotika, psikotropika, dan zat adiktif di tempat kerja|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/225/peraturan-menteri-nomor-11-tahun-2005
permenaker-4-1995-pjk3|Permenaker PER.04/MEN/1995 tentang Perusahaan Jasa K3|penunjukan dan ruang lingkup layanan PJK3|Berlaku; status PJK3 individual harus diverifikasi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/236/peraturan-menteri-nomor-4-tahun-1995
permenaker-2-1992-ahli-k3|Permenaker PER.02/MEN/1992 tentang Tata Cara Penunjukan Ahli K3|persyaratan, permohonan, kewajiban, kewenangan, dan masa penunjukan Ahli K3|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/242/peraturan-menteri-tenaga-kerja-nomor-2-tahun-1992
permenaker-1-1992-pesawat-karbid|Permenaker PER.01/MEN/1992 tentang Pesawat Karbid|syarat K3 untuk pesawat karbid dan penggunaan asetilena|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/241/peraturan-menteri-nomor-1-tahun-1992
permenaker-2-1983-alarm-kebakaran|Permenaker PER.02/MEN/1983 tentang Instalasi Alarm Kebakaran Automatik|persyaratan instalasi deteksi dan alarm kebakaran automatik|Berlaku per sumber resmi; dibaca bersama aturan bangunan terbaru|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2779/peraturan-menteri-tenaga-kerja-nomor-2-tahun-1983
permenaker-2-1980-pemeriksaan-kesehatan|Permenaker PER.02/MEN/1980 tentang Pemeriksaan Kesehatan Tenaga Kerja|pemeriksaan kesehatan awal, berkala, dan khusus dalam keselamatan kerja|Berlaku per sumber resmi; dibaca bersama aturan kesehatan terbaru|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2402/peraturan-menteri-nomor-2-tahun-1980
permenaker-2-1982-juru-las|Permenaker PER.02/MEN/1982 tentang Kualifikasi Juru Las|syarat, kelas, posisi uji, pengujian, dan pemeliharaan kualifikasi juru las|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/3078/peraturan-menteri-tenaga-kerja-dan-transmigrasi-nomor-per-02-men-1982
kepmenaker-187-1999-bahan-kimia|Kepmenaker KEP.187/MEN/1999 tentang Pengendalian Bahan Kimia Berbahaya|klasifikasi potensi bahaya, SDS, label, petugas, Ahli K3 Kimia, dan pengendalian bahan|Berlaku per sumber resmi|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2608/keputusan-menteri-nomor-187-tahun-1999
kepmenaker-186-1999-kebakaran|Kepmenaker KEP.186/MEN/1999 tentang Unit Penanggulangan Kebakaran|organisasi, kelas personel, jumlah petugas, syarat, dan kurikulum unit kebakaran|Berlaku per TemanK3|TemanK3 Kemnaker|https://temank3.kemnaker.go.id/page/perundangan_detail/53/4befcf7c2fa0b02558b6259cec67047c
kepmenaker-5-2026-rekomendasi-lsp-k3|Kepmenaker Nomor 5 Tahun 2026 tentang Rekomendasi Lisensi LSP K3|rekomendasi Kemnaker untuk penerbitan lisensi BNSP bagi LSP bidang K3|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2822/keputusan-menteri-nomor-5-tahun-2026
semenaker-3-2024-program-k3-nasional|SE Menaker Nomor M/3/HK.04/IV/2024 tentang Program K3 Nasional|arah program K3 nasional 2024 sampai 2029|Berlaku sebagai surat edaran kebijakan|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2477/surat-edaran-menteri-nomor-3-tahun-2024
kepmenaker-146-2024-kader-norma|Kepmenaker Nomor 146 Tahun 2024 tentang Sertifikasi Kader Norma Ketenagakerjaan|pemberlakuan sertifikasi kompetensi untuk tenaga kerja bidang kader norma|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2503/keputusan-menteri-ketenagakerjaan-nomor-146-tahun-2024
pp-45-2023-keselamatan-radiasi|PP Nomor 45 Tahun 2023 tentang Keselamatan Radiasi Pengion|keselamatan radiasi pengion dan keamanan zat radioaktif|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/2373/peraturan-pemerintah-nomor-45-tahun-2023
permen-pupr-10-2021-smkk|Permen PUPR Nomor 10 Tahun 2021 tentang Pedoman SMKK|sistem manajemen keselamatan konstruksi dan RKK|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/216875/permen-pupr-no-10-tahun-2021
pp-14-2021-jasa-konstruksi|PP Nomor 14 Tahun 2021 tentang Perubahan Pelaksanaan Jasa Konstruksi|jasa konstruksi, kompetensi, usaha, dan pelaksanaan pekerjaan konstruksi|Berlaku sebagai perubahan PP 22 Tahun 2020|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/161844/pp-no-14-tahun-2021
pp-16-2021-bangunan-gedung|PP Nomor 16 Tahun 2021 tentang Bangunan Gedung|keselamatan bangunan, standar teknis, PBG, dan SLF|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/161846/pp-no-16-tahun-2021
permen-pu-26-2008-proteksi-kebakaran|Permen PU Nomor 26/PRT/M/2008 tentang Proteksi Kebakaran Bangunan|proteksi kebakaran aktif, pasif, dan sarana jalan keluar bangunan|Berlaku per sumber resmi; harmonisasi dengan PP 16 Tahun 2021 perlu diperiksa|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/104475/permen-pupr-no-26prtm2008-tahun-2008
permen-pu-20-2009-manajemen-kebakaran|Permen PU Nomor 20/PRT/M/2009 tentang Manajemen Proteksi Kebakaran|manajemen proteksi kebakaran perkotaan, lingkungan, dan bangunan|Status dan hubungan aturan terbaru perlu diverifikasi|Database Peraturan BPK|https://peraturan.bpk.go.id/Download/95219/PermenPU20-2009.pdf
permenkes-66-2016-k3-rumah-sakit|Permenkes Nomor 66 Tahun 2016 tentang K3 Rumah Sakit|pengelolaan K3 rumah sakit, bahaya, organisasi, dan program|Berlaku per BPK; harmonisasi dengan UU Kesehatan dan PP 28 Tahun 2024 perlu diperiksa|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/114482/permenkes-no-66-tahun-2016
permen-esdm-26-2018-kaidah-pertambangan|Permen ESDM Nomor 26 Tahun 2018 tentang Kaidah Pertambangan yang Baik|keselamatan pertambangan dan pengawasan mineral serta batubara|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/142457/permen-esdm-no-26-tahun-2018
permen-esdm-10-2021-keselamatan-ketenagalistrikan|Permen ESDM Nomor 10 Tahun 2021 tentang Keselamatan Ketenagalistrikan|SMK2, instalasi, operasi, pengujian, dan kompetensi ketenagalistrikan|Berlaku|JDIH ESDM|https://jdih.esdm.go.id/dokumen/view?id=2153
permen-esdm-7-2021-standardisasi-listrik|Permen ESDM Nomor 7 Tahun 2021 tentang Standardisasi Ketenagalistrikan|standardisasi serta tanda SNI atau tanda keselamatan peralatan listrik|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/180040/permen-esdm-no-7-tahun-2021
pp-22-2021-lingkungan|PP Nomor 22 Tahun 2021 tentang Perlindungan dan Pengelolaan Lingkungan Hidup|persetujuan lingkungan, emisi, air limbah, limbah B3, dan sanksi|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/161852/pp-no-22-tahun-2021
permen-lhk-5-2021-persetujuan-teknis|Permen LHK Nomor 5 Tahun 2021 tentang Persetujuan Teknis|persetujuan teknis dan surat kelayakan operasional pengendalian pencemaran|Berlaku; periksa ketentuan sektor terbaru|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/210999/permen-lhk-no-5-tahun-2021
permen-lhk-6-2021-limbah-b3|Permen LHK Nomor 6 Tahun 2021 tentang Pengelolaan Limbah B3|penyimpanan, pengumpulan, pengangkutan, pemanfaatan, pengolahan, dan penimbunan limbah B3|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/211000/permen-lhk-no-6-tahun-2021
pp-74-2001-b3|PP Nomor 74 Tahun 2001 tentang Pengelolaan B3|pengelolaan bahan berbahaya dan beracun sebagai bahan|Berlaku per BPK; bedakan bahan B3 dari limbah B3|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/53080/pp-no-74-tahun-2001
pp-7-1973-pestisida|PP Nomor 7 Tahun 1973 tentang Pengawasan Pestisida|peredaran, penyimpanan, dan penggunaan pestisida|Berlaku per JDIH; detail operasional terbaru perlu diperiksa|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/423/peraturan-pemerintah-nomor-7-tahun-1973
pp-58-2015-pengangkutan-radioaktif|PP Nomor 58 Tahun 2015 tentang Pengangkutan Zat Radioaktif|keselamatan dan keamanan pengangkutan zat radioaktif|Berlaku; mencabut PP 26 Tahun 2002|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/5632/pp-no-58-tahun-2015
pp-10-2018-bnsp|PP Nomor 10 Tahun 2018 tentang BNSP|kedudukan, fungsi, kewenangan, dan pelaksanaan sertifikasi kompetensi oleh BNSP|Berlaku; mencabut PP 23 Tahun 2004|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/72812/pp-no-10-tahun-2018
pp-31-2006-sistem-pelatihan-kerja|PP Nomor 31 Tahun 2006 tentang Sistem Pelatihan Kerja Nasional|pelatihan berbasis kompetensi, standar kompetensi, dan sertifikasi|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/49124/pp-no-31-tahun-2006
pp-34-2018-standardisasi|PP Nomor 34 Tahun 2018 tentang Standardisasi dan Penilaian Kesesuaian|standardisasi nasional, SNI, akreditasi, dan penilaian kesesuaian|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/89215/pp-no-34-tahun-2018
perpres-8-2012-kkni|Perpres Nomor 8 Tahun 2012 tentang KKNI|jenjang kualifikasi nasional dan penyetaraan capaian pembelajaran|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/41251/perpres-no-8-tahun-2012
permenaker-2-2016-standardisasi-kompetensi|Permenaker Nomor 2 Tahun 2016 tentang Sistem Standardisasi Kompetensi Kerja Nasional|sistem pengembangan, penerapan, dan harmonisasi standar kompetensi|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/1203/peraturan-menteri-ketenagakerjaan-nomor-2-tahun-2016
permenaker-3-2016-penetapan-skkni|Permenaker Nomor 3 Tahun 2016 tentang Tata Cara Penetapan SKKNI|pengembangan dan penetapan standar kompetensi kerja nasional|Berlaku|Database Peraturan BPK|https://peraturan.bpk.go.id/Details/146099/permenaker-no-3-tahun-2016
permenaker-21-2014-penerapan-kkni|Permenaker Nomor 21 Tahun 2014 tentang Penerapan KKNI|penerapan jenjang KKNI pada pelatihan, sertifikasi, dan pengembangan SDM|Berlaku|JDIH Kemnaker|https://jdih.kemnaker.go.id/peraturan/detail/568/peraturan-menteri-ketenagakerjaan-nomor-21-tahun-2014
pedoman-bnsp-201|Pedoman BNSP 201 tentang Persyaratan Umum LSP|persyaratan umum lembaga sertifikasi profesi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&sort=oldest
pedoman-bnsp-202|Pedoman BNSP 202 tentang Pembentukan LSP|proses pembentukan lembaga sertifikasi profesi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&sort=oldest
pedoman-bnsp-206|Pedoman BNSP 206 tentang Persyaratan TUK|persyaratan umum tempat uji kompetensi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&sort=oldest
pedoman-bnsp-208|Pedoman BNSP 208 tentang Lisensi BNSP kepada LSP|ketentuan umum lisensi lembaga sertifikasi profesi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&sort=oldest
pedoman-bnsp-210|Pedoman BNSP 210 tentang Pengembangan Skema Sertifikasi|pengembangan, validasi, dan pemeliharaan skema sertifikasi profesi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&sort=oldest
pedoman-bnsp-301|Pedoman BNSP 301 tentang Pelaksanaan Asesmen Kompetensi|prinsip dan proses pelaksanaan asesmen kompetensi|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&page=2&sort=oldest
pedoman-bnsp-302|Pedoman BNSP 302 tentang Penerbitan Sertifikat Kompetensi|proses penerbitan sertifikat kompetensi dan hubungannya dengan ketentuan terbaru|Pedoman resmi BNSP; revisi dokumen harus diperiksa|BNSP|https://bnsp.go.id/informasi-publik?category=Pedoman+dan+Peraturan&page=2&sort=oldest`;

export const regulationSeeds: RegulationSeed[] = rows.trim().split('\n').map((line) => {
  const [slug,title,scope,status,publisher,url] = line.split('|');
  return { slug, title, scope, status, source:{label:title,publisher,url} };
});
