import type { CompetencySeed, ProfessionSeed } from './content-types';

const professionRows = `
ahli-k3-umum|Ahli K3 Umum|membantu pengawasan penerapan norma K3 dan memberikan pertimbangan K3 sesuai ruang lingkup penunjukannya|perusahaan lintas sektor;proyek;kantor pusat;unit operasional|pemahaman norma;inspeksi;analisis risiko;komunikasi rekomendasi|regulated
auditor-smk3|Auditor SMK3|menilai kesesuaian dan efektivitas penerapan SMK3 berdasarkan kriteria serta bukti objektif|perusahaan;lembaga audit;proyek;rantai pasok|prinsip audit;sampling bukti;wawancara;penulisan temuan|regulated
petugas-p3k|Petugas P3K|memberikan pertolongan pertama dalam batas kompetensi dan mengaktifkan rujukan medis|pabrik;kantor;proyek;gudang;layanan publik|penilaian korban;pertolongan awal;evakuasi;pengelolaan fasilitas P3K|regulated
petugas-k3-kimia|Petugas K3 Kimia|mendukung inventarisasi, komunikasi bahaya, penyimpanan, dan pengendalian bahan kimia|industri kimia;laboratorium;gudang;manufaktur|SDS;label;kompatibilitas;respons tumpahan|regulated
ahli-k3-kimia|Ahli K3 Kimia|merancang dan mengevaluasi pengendalian risiko kimia serta pajanan di tempat kerja|proses kimia;manufaktur;laboratorium;pertambangan|penilaian pajanan;toksikologi;ventilasi;program pengendalian|regulated
teknisi-k3-listrik|Teknisi K3 Listrik|melaksanakan pemeriksaan dan pekerjaan kelistrikan dengan pengendalian bahaya energi|fasilitas;utilitas;pabrik;proyek konstruksi|proteksi listrik;pengujian;isolasi energi;dokumentasi|regulated
operator-forklift|Operator Forklift|mengoperasikan forklift sesuai kapasitas, rute, kondisi unit, dan aturan lalu lintas internal|gudang;pabrik;pelabuhan;pusat distribusi|inspeksi unit;stabilitas beban;stacking;komunikasi area|regulated
operator-crane|Operator Crane|mengoperasikan crane sesuai load chart, konfigurasi, kondisi lapangan, dan lifting plan|proyek;konstruksi;pelabuhan;pabrik;oil and gas|load chart;stabilitas;komunikasi lifting;inspeksi alat|regulated
rigger|Rigger|memilih serta memasang alat bantu angkat dan mengendalikan beban selama lifting|konstruksi;manufaktur;pelabuhan;migas|sling selection;sudut sling;pusat gravitasi;isyarat|scheme
scaffolder|Scaffolder|memasang, mengubah, dan membongkar perancah mengikuti desain serta prosedur aman|konstruksi;pemeliharaan;shipyard;fasilitas proses|komponen perancah;bracing;platform;proteksi jatuh|scheme
safety-officer|Safety Officer|mengawasi pelaksanaan program K3 harian, inspeksi, briefing, dan tindak lanjut temuan|proyek;pabrik;gudang;layanan|observasi lapangan;komunikasi;pelaporan;koordinasi tindakan|organizational
hse-officer|HSE Officer|mengintegrasikan kegiatan keselamatan, kesehatan kerja, dan lingkungan pada operasi|industri;proyek;logistik;fasilitas|risk assessment;compliance monitoring;incident reporting;environmental awareness|organizational
hse-supervisor|HSE Supervisor|mengkoordinasikan pengawasan lapangan, tim HSE, izin kerja, dan tindakan korektif|proyek besar;pabrik;pertambangan;migas|leadership;planning;PTW;performance monitoring|organizational
hse-manager|HSE Manager|menetapkan strategi, tata kelola, sumber daya, dan evaluasi kinerja HSE organisasi|korporasi;multi-site;proyek;operasi berisiko tinggi|governance;risk strategy;assurance;leadership communication|organizational
fire-warden|Fire Warden|membantu pencegahan kebakaran, pengosongan area, pemeriksaan zona, dan pelaporan saat darurat|kantor;pabrik;mal;rumah sakit;hotel|evacuation;area sweep;alarm communication;assembly accountability|organizational
paramedis-perusahaan|Paramedis Perusahaan|memberikan layanan kesehatan kerja, pertolongan, surveilans, dan koordinasi rujukan|klinik perusahaan;tambang;pabrik;perkebunan;proyek|clinical triage;occupational health;emergency care;recordkeeping|scheme
dokter-perusahaan|Dokter Perusahaan|memimpin pelayanan kesehatan kerja, penilaian kebugaran, surveilans, dan pencegahan penyakit akibat kerja|perusahaan;klinik kerja;industri;pertambangan|occupational medicine;fitness for work;surveillance;case management|regulated
higienis-industri|Higienis Industri|mengantisipasi, mengenali, mengevaluasi, dan mengendalikan pajanan lingkungan kerja|manufaktur;kimia;tambang;laboratorium;konsultan|exposure assessment;sampling;NAB;control evaluation|scheme
petugas-ruang-terbatas|Petugas Ruang Terbatas|menjalankan peran entrant atau attendant sesuai izin masuk dan rencana penyelamatan|migas;utilitas;manufaktur;galangan;pengolahan air|permit entry;gas awareness;communication;emergency action|scheme
pengawas-pekerjaan-ketinggian|Pengawas Pekerjaan Ketinggian|memastikan rencana, akses, anchor, peralatan, kompetensi, dan rescue tersedia sebelum pekerjaan tinggi|konstruksi;telekomunikasi;gedung;energi|fall protection planning;equipment inspection;supervision;rescue readiness|scheme
petugas-tanggap-darurat|Petugas Tanggap Darurat|merespons skenario darurat sesuai komando, fungsi tim, komunikasi, dan prosedur keselamatan|semua tempat kerja dengan organisasi ERT|incident response;communication;evacuation;team safety|organizational
investigator-kecelakaan-kerja|Investigator Kecelakaan Kerja|mengumpulkan fakta, menganalisis penyebab, dan merancang perbaikan setelah insiden|perusahaan;proyek;transportasi;operasi proses|evidence preservation;interview;causal analysis;corrective action|organizational
inspektor-k3|Inspektor K3|melakukan pemeriksaan terencana, mencatat bukti, mengklasifikasikan temuan, dan memantau perbaikan|pabrik;proyek;gudang;fasilitas|inspection planning;observation;evidence writing;follow-up|organizational
juru-las|Juru Las|melaksanakan pengelasan sesuai prosedur kerja, mutu sambungan, dan pengendalian bahaya hot work|fabrikasi;konstruksi;shipyard;pemeliharaan|welding process;WPS awareness;hot-work safety;quality inspection|scheme
safety-engineer|Safety Engineer|menerapkan prinsip rekayasa untuk menghilangkan atau mengurangi risiko pada desain, proses, dan peralatan|engineering;process industry;construction;manufacturing|design review;hazard analysis;engineering controls;technical communication|organizational
process-safety-engineer|Process Safety Engineer|mengendalikan risiko kecelakaan proses besar melalui desain, barrier, perubahan, dan pembelajaran insiden|kimia;migas;petrokimia;energi|PHA;barrier management;MOC;process incident analysis|organizational
occupational-health-nurse|Perawat Kesehatan Kerja|menjalankan pelayanan keperawatan kerja, pertolongan, edukasi, dan pemantauan kesehatan pekerja|klinik perusahaan;manufaktur;tambang;perkebunan|nursing assessment;first response;health promotion;surveillance support|organizational
safety-trainer|Trainer K3|merancang dan memfasilitasi pembelajaran K3 berbasis kebutuhan, risiko, dan evaluasi kompetensi|lembaga pelatihan;perusahaan;proyek;konsultan|training needs analysis;facilitation;assessment;learning evaluation|organizational
permit-issuer|Permit Issuer|menilai prasyarat dan mengotorisasi pekerjaan berisiko melalui sistem izin kerja|migas;kimia;utilitas;manufaktur|hazard verification;isolation review;SIMOPS;handover|organizational
gas-tester|Gas Tester|menggunakan instrumen untuk menilai oksigen, gas mudah terbakar, dan kontaminan sebelum atau selama pekerjaan|ruang terbatas;hot work;migas;pengolahan air|instrument check;sampling;interpretation;recording|scheme
lifting-supervisor|Lifting Supervisor|mengkoordinasikan lifting plan, peralatan, personel, zona eksklusi, dan penghentian operasi|konstruksi;pelabuhan;migas;manufaktur|lift planning;team coordination;site assessment;stop-work decision|organizational
warehouse-safety-coordinator|Koordinator K3 Gudang|mengendalikan interaksi kendaraan, rak, material, pekerja, kebakaran, dan ergonomi di gudang|warehouse;distribution center;cold storage;retail logistics|traffic management;racking safety;material handling;inspection|organizational
construction-safety-manager|Manajer Keselamatan Konstruksi|memimpin penerapan rencana keselamatan konstruksi, koordinasi kontraktor, dan pengendalian pekerjaan kritis|proyek gedung;infrastruktur;industrial construction|SMKK;contractor control;critical risk;assurance|organizational
environmental-officer|Environmental Officer|memantau aspek lingkungan, kepatuhan, limbah, emisi, dan respons kejadian lingkungan|manufaktur;tambang;proyek;fasilitas|aspect-impact;waste management;monitoring;reporting|organizational
emergency-response-commander|Koordinator Tanggap Darurat|memimpin struktur komando, menetapkan prioritas, mengalokasikan sumber daya, dan menghubungkan pihak eksternal|pabrik;tambang;gedung;operasi proses|incident command;decision making;resource coordination;external liaison|organizational
safety-data-analyst|Analis Data K3|mengubah data insiden, inspeksi, observasi, dan tindakan menjadi informasi untuk keputusan pencegahan|korporasi;multi-site;manufaktur;logistik|data quality;indicator design;trend analysis;visual communication|organizational
occupational-ergonomist|Praktisi Ergonomi Kerja|menilai interaksi pekerja, tugas, peralatan, dan organisasi kerja untuk mengurangi beban yang tidak sesuai|kantor;manufaktur;logistik;layanan kesehatan|task analysis;posture assessment;work design;intervention evaluation|organizational
industrial-firefighter|Petugas Pemadam Industri|melaksanakan respons kebakaran industri dengan memperhatikan bahan, proses, proteksi, dan keselamatan tim|kimia;migas;manufaktur;pergudangan|fire behavior;hose operation;PPE;team tactics|organizational
rope-access-technician|Teknisi Akses Tali|melaksanakan pekerjaan dengan sistem akses tali dan sistem cadangan sesuai rencana serta rescue readiness|gedung;energi;telekomunikasi;inspeksi|rope system;equipment inspection;work positioning;rescue|scheme
occupational-safety-consultant|Konsultan K3|menganalisis kebutuhan klien, memberi rekomendasi, dan mendukung penerapan program tanpa mengambil alih tanggung jawab organisasi|konsultan;berbagai sektor;proyek transformasi|diagnosis;regulatory research;facilitation;ethical reporting|organizational`;

const competencyRows = `
identifikasi-bahaya|Identifikasi Bahaya|menemukan sumber, situasi, tindakan, atau kombinasi yang dapat menyebabkan cedera maupun gangguan kesehatan|uraian aktivitas;observasi lapangan;data insiden;informasi peralatan|daftar bahaya yang spesifik terhadap aktivitas;catatan kondisi dan skenario paparan|hanya menulis kategori umum;mengabaikan pekerjaan nonrutin;menyamakan bahaya dengan risiko
penilaian-risiko|Penilaian Risiko K3|menentukan prioritas berdasarkan kemungkinan, konsekuensi, pajanan, dan efektivitas kontrol yang ada|skenario kejadian;kriteria organisasi;data pajanan;kontrol eksisting|tingkat risiko awal dan sisa;alasan penilaian;prioritas tindakan|mengalikan angka tanpa skenario;menggunakan kriteria berbeda-beda;menganggap APD selalu cukup
pengendalian-risiko|Pengendalian Risiko|memilih tindakan yang mengurangi kemungkinan atau konsekuensi dengan mengutamakan eliminasi dan rekayasa|hasil penilaian;pilihan teknologi;persyaratan hukum;masukan pekerja|rencana kontrol;penanggung jawab;tenggat;indikator efektivitas|langsung memilih APD;mengabaikan risiko baru;tidak menilai efektivitas
menyusun-hiradc|Menyusun HIRADC|mendokumentasikan aktivitas, bahaya, risiko, kontrol, dan tindakan lanjutan dalam satu register yang dapat ditinjau|proses kerja;task breakdown;kriteria risiko;catatan perubahan|register HIRADC;action plan;riwayat review|mengisi formulir dari meja;menyalin proyek lain;tidak melibatkan pelaksana
menyusun-jsa|Menyusun JSA|memecah pekerjaan menjadi langkah logis dan menetapkan kontrol untuk bahaya pada tiap langkah|metode kerja;observasi;manual peralatan;pengalaman pekerja|JSA yang dapat dipakai briefing dan verifikasi lapangan|langkah terlalu luas;kontrol berupa slogan;tidak memperbarui saat kondisi berubah
investigasi-insiden|Investigasi Insiden|memahami apa yang terjadi, mengapa pertahanan gagal, dan bagaimana mencegah pengulangan|bukti fisik;wawancara;dokumen;data proses|timeline;faktor penyebab;rekomendasi sistemik|mencari orang untuk disalahkan;terlambat mengamankan bukti;hanya memperbaiki gejala
analisis-akar-masalah|Analisis Akar Masalah|menelusuri faktor teknis, organisasi, manusia, dan manajemen yang memungkinkan kejadian|timeline;fakta terverifikasi;barrier analysis;riwayat perubahan|penyebab langsung dan mendasar;hubungan sebab-akibat;tindakan yang dapat diuji|berhenti pada unsafe action;memaksakan satu penyebab;tidak memvalidasi hipotesis
inspeksi-tempat-kerja|Inspeksi Tempat Kerja|menemukan kondisi, praktik, dan kelemahan kontrol sebelum menimbulkan kerugian|kriteria inspeksi;peta area;riwayat temuan;observasi|temuan faktual;prioritas;penanggung jawab;tindak lanjut|checklist tanpa observasi;temuan tidak spesifik;menutup tanpa verifikasi
audit-k3|Audit K3|menilai apakah sistem dirancang, diterapkan, dan dipelihara sesuai kriteria|standar;prosedur;rekaman;wawancara;observasi|kesimpulan audit;temuan berbukti;peluang perbaikan|menyamakan audit dengan inspeksi;opini tanpa bukti;ruang lingkup tidak jelas
penggunaan-apar|Penggunaan APAR|memilih dan menggunakan alat pemadam awal tanpa menempatkan pengguna pada risiko yang tidak dapat diterima|kelas kebakaran;jenis media;jalur evakuasi;kondisi APAR|keputusan menggunakan atau mundur;teknik pemadaman awal yang aman|melawan api yang membesar;media tidak sesuai;tidak menjaga jalur keluar
evakuasi-darurat|Evakuasi Darurat|memindahkan orang menuju tempat aman secara tertib sambil menjaga akuntabilitas|skenario;jalur dan pintu;populasi;alarm;assembly point|rencana evakuasi;daftar peran;hasil drill;perbaikan|jalur terhalang;tidak menghitung penghuni;mengabaikan penyandang disabilitas
pertolongan-pertama|Pertolongan Pertama di Tempat Kerja|memberikan bantuan awal untuk mempertahankan hidup, mencegah perburukan, dan memperoleh bantuan medis|keamanan lokasi;penilaian korban;fasilitas P3K;sistem rujukan|tindakan awal sesuai kompetensi;aktivasi bantuan;catatan kejadian|bertindak di luar kompetensi;tidak memakai proteksi diri;terlambat merujuk
isolasi-energi|Isolasi Energi|mengendalikan energi listrik, mekanik, hidrolik, pneumatik, termal, dan energi tersimpan sebelum pekerjaan|daftar sumber energi;diagram;titik isolasi;prosedur shutdown|kondisi zero energy terverifikasi;kunci dan tag;catatan pelepasan|hanya mematikan tombol;tidak membuang energi tersimpan;tidak menguji isolasi
pengujian-gas|Pengujian Gas Ruang Terbatas|menilai atmosfer untuk oksigen, mudah terbakar, dan zat toksik dengan alat serta metode sampling yang sesuai|identitas bahaya;instrumen;lokasi sampling;kriteria izin masuk|hasil ukur tertelusur;keputusan izin;frekuensi monitoring|tidak melakukan bump test;sampling satu titik;salah urutan pengukuran
inspeksi-scaffolding|Inspeksi Scaffolding|memastikan fondasi, struktur, platform, akses, proteksi jatuh, dan status perancah layak digunakan|desain atau kelas;komponen;kondisi tanah;riwayat perubahan|tag status;temuan rinci;keputusan penggunaan atau isolasi|hanya melihat dari bawah;mengabaikan perubahan;tidak memeriksa akses
inspeksi-forklift|Inspeksi Forklift|memeriksa kondisi keselamatan forklift sebelum operasi dan mencatat kerusakan yang memerlukan isolasi|checklist unit;manual;log kerusakan;kondisi area|keputusan layak operasi;daftar cacat;tindak lanjut pemeliharaan|sekadar mencentang;tetap memakai alat rusak;tidak memeriksa attachment
lifting-plan|Penyusunan Lifting Plan|menetapkan beban, crane, konfigurasi, rigging, lintasan, personel, dan kontrol untuk pengangkatan|berat dan pusat gravitasi;load chart;layout;ground bearing;cuaca|rencana pengangkatan;sketsa;perhitungan;briefing;hold point|berat perkiraan tanpa dasar;salah radius;tidak mengendalikan area
pemilihan-apd|Pemilihan APD|menetapkan APD berdasarkan bahaya sisa, kompatibilitas, ukuran, standar, dan kondisi penggunaan|hasil penilaian risiko;spesifikasi bahan;tugas;profil pengguna|matriks APD;spesifikasi;pemeriksaan;pelatihan pengguna|memilih dari kebiasaan;APD tidak kompatibel;tidak melakukan fit
komunikasi-bahaya|Komunikasi Bahaya|menyampaikan informasi risiko bahan dan pekerjaan melalui label, SDS, briefing, tanda, dan pelatihan|inventaris bahan;SDS;profil pekerja;bahasa kerja|pesan yang dipahami;label akurat;akses SDS;catatan pelatihan|mengandalkan poster;SDS tidak tersedia;bahasa terlalu teknis
pengelolaan-sds|Pengelolaan Safety Data Sheet|memastikan SDS sesuai produk, terbaru, mudah diakses, dan digunakan untuk keputusan pengendalian|daftar bahan;SDS pemasok;lokasi penggunaan;perubahan produk|register SDS;kontrol versi;akses pekerja;data untuk tanggap darurat|SDS tidak cocok produk;dokumen kedaluwarsa;tidak diterjemahkan ke prosedur
pengukuran-kebisingan|Pengukuran Kebisingan Kerja|merancang pengukuran yang mewakili pajanan dan mendukung keputusan pengendalian|proses dan jadwal kerja;sumber bising;kelompok pajanan serupa;alat ukur|peta kebisingan;estimasi pajanan;rekomendasi kontrol;catatan kalibrasi|sampling tidak representatif;mengabaikan durasi;alat tidak dikalibrasi
penilaian-ergonomi|Penilaian Ergonomi|menilai tuntutan postur, gaya, repetisi, durasi, desain alat, dan organisasi kerja|observasi tugas;keluhan;dimensi stasiun;beban;tempo|prioritas perbaikan;opsi desain;indikator evaluasi|mengandalkan foto sesaat;hanya melatih postur;mengabaikan desain kerja
toolbox-meeting|Pelaksanaan Toolbox Meeting|menghubungkan bahaya pekerjaan hari itu dengan kontrol, perubahan, dan tanggung jawab tim|rencana kerja;JSA;kondisi lapangan;perubahan;pelajaran insiden|pemahaman bersama;pertanyaan terjawab;catatan isu dan tindakan|membaca teks tanpa dialog;topik tidak relevan;tidak menutup isu
safety-induction|Pelaksanaan Safety Induction|memberikan informasi minimum agar orang memahami aturan, bahaya utama, darurat, dan batas akses|profil pengunjung;risiko lokasi;aturan;jalur darurat;kontak|pemahaman dasar;otorisasi akses;catatan induksi|materi terlalu umum;tidak menguji pemahaman;tidak membedakan peran
manajemen-perubahan|Management of Change|menilai risiko sebelum perubahan peralatan, bahan, proses, organisasi, atau prosedur diterapkan|deskripsi perubahan;baseline;gambar;data bahaya;pihak terdampak|persetujuan perubahan;action list;dokumen diperbarui;review pasca-implementasi|menganggap perubahan sementara aman;tidak memperbarui prosedur;menutup sebelum verifikasi
analisis-bowtie|Analisis Bowtie|memetakan ancaman, top event, konsekuensi, barrier pencegahan, dan barrier mitigasi|skenario risiko;data insiden;kontrol;standar kinerja|diagram bowtie;daftar barrier kritis;pemilik barrier;assurance plan|mencampur ancaman dan konsekuensi;barrier berupa tujuan;tanpa performance standard
hazop|Hazard and Operability Study|mengkaji penyimpangan proses secara sistematis dengan guideword dan tim multidisiplin|P&ID;design intent;process data;operating procedure|daftar deviasi;cause-consequence;safeguard;recommendation|dokumen desain belum matang;tim tidak lengkap;rekomendasi tidak ditutup
what-if-analysis|What-if Analysis|menggunakan pertanyaan skenario untuk menemukan kegagalan dan kebutuhan kontrol|alur proses;pengalaman tim;riwayat insiden;perubahan|daftar skenario;konsekuensi;kontrol;action|pertanyaan terlalu luas;tidak mencatat asumsi;tanpa prioritas
job-observation|Observasi Pekerjaan|mengamati cara kerja nyata untuk memahami variasi, penghalang, dan peluang perbaikan|pemilihan tugas;persetujuan pekerja;standar kerja;lembar observasi|catatan perilaku dan kondisi;percakapan;perbaikan sistem|observasi tersembunyi;menghakimi pekerja;hanya mencari kesalahan
barrier-management|Manajemen Barrier|menetapkan barrier kritis, standar kinerja, pemilik, pemantauan, dan respons degradasi|skenario mayor;bowtie;data inspeksi;failure mode|register barrier;performance standard;dashboard;degradation response|menyamakan semua kontrol;indikator tidak terkait fungsi;degradasi dibiarkan
emergency-drill-design|Perancangan Simulasi Darurat|menguji tujuan spesifik rencana darurat melalui skenario terkendali dan evaluasi berbukti|rencana darurat;risiko;tujuan latihan;peserta;observer|exercise plan;inject;evaluation sheet;improvement plan|skenario tanpa tujuan;mengejutkan secara tidak aman;menilai individu bukan sistem
contractor-prequalification|Prakualifikasi K3 Kontraktor|menilai kemampuan kontraktor mengelola risiko pekerjaan sebelum kontrak diberikan|ruang lingkup;kelas risiko;dokumen legal;kinerja;kompetensi|hasil evaluasi;gap;syarat kontrak;keputusan seleksi|menilai dokumen saja;kriteria sama untuk semua risiko;konflik kepentingan
incident-trending|Analisis Tren Insiden|mengenali pola kejadian, paparan, lokasi, tugas, dan kelemahan barrier dari data yang berkualitas|data insiden;jam kerja;klasifikasi;exposure data|tren tervalidasi;cluster;hipotesis;pioritas penyelidikan|membandingkan angka tanpa denominator;kategori berubah;menyimpulkan sebab dari korelasi
safety-kpi-design|Perancangan KPI K3|memilih indikator yang menghubungkan risiko kritis, aktivitas pencegahan, hasil, dan kualitas kontrol|tujuan;profil risiko;data tersedia;tanggung jawab|set leading dan lagging KPI;definisi;target;ritme review|terlalu banyak indikator;target mendorong underreporting;KPI tidak dapat ditindaklanjuti
permit-to-work-control|Pengendalian Permit to Work|memastikan izin kerja menjadi proses verifikasi risiko, bukan dokumen administratif|scope kerja;JSA;isolasi;gas test;SIMOPS|izin valid;otorisasi jelas;handover;close-out|izin diterbitkan dari kantor;perubahan scope tidak dinilai;izin kedaluwarsa
hot-work-control|Pengendalian Hot Work|mencegah penyalaan dengan eliminasi, isolasi, pembersihan, gas test, fire watch, dan pemantauan setelah kerja|lokasi;bahan mudah terbakar;ventilasi;alat;durasi|hot-work permit;area siap;fire watch;post-work monitoring|hanya menyediakan APAR;tidak memeriksa area tersembunyi;fire watch pergi terlalu cepat
confined-space-entry|Pengendalian Masuk Ruang Terbatas|mengintegrasikan isolasi, ventilasi, gas test, peran, komunikasi, dan rescue sebelum masuk|klasifikasi ruang;bahaya;isolasi;atmosfer;personel;rescue resource|entry permit;log personel;hasil gas;rescue plan|rescue hanya menelepon bantuan;ventilasi tanpa evaluasi;attendant merangkap tugas
traffic-management|Manajemen Lalu Lintas Internal|memisahkan kendaraan dan pejalan kaki melalui desain rute, aturan, visibilitas, dan pengawasan|layout;jenis kendaraan;volume;blind spot;jam operasi|traffic management plan;segregasi;signage;speed control;review|mengandalkan rompi;persimpangan tidak dinilai;reversing tanpa kontrol
manual-handling-assessment|Penilaian Manual Handling|menilai beban, frekuensi, jarak, postur, pegangan, lingkungan, dan kemampuan pekerja|tugas;berat;dimensi;frekuensi;layout;keluhan|prioritas redesign;alat bantu;perubahan metode;monitoring|hanya menetapkan batas berat;pelatihan angkat sebagai satu-satunya kontrol;mengabaikan repetisi
machine-guarding-assessment|Penilaian Pelindung Mesin|memastikan akses ke bagian bergerak dicegah tanpa menciptakan bahaya baru atau menghambat fungsi pengaman|gambar mesin;task operation;maintenance access;failure history|daftar gap;spesifikasi guard;interlock test;action plan|guard mudah dilepas;celah tidak dinilai;bypass interlock diabaikan
safety-critical-equipment|Pengelolaan Peralatan Kritis K3|mengidentifikasi peralatan yang kegagalannya dapat melepaskan bahaya besar dan memastikan integritasnya|risk scenario;equipment list;failure mode;maintenance data|critical register;performance standard;inspection plan;deviation response|kritis berdasarkan harga;interval tanpa dasar;backlog tidak diprioritaskan
root-cause-interview|Wawancara Investigasi Insiden|memperoleh ingatan dan konteks saksi secara adil, terbuka, dan tidak mengarahkan|timeline awal;daftar saksi;lokasi tenang;pertanyaan terbuka|catatan terverifikasi;fakta tambahan;perbedaan perspektif|mewawancarai berkelompok;pertanyaan menuduh;menunda terlalu lama
safety-leadership|Kepemimpinan K3|membentuk keputusan, sumber daya, perilaku manajemen, dan respons terhadap kabar buruk yang mendukung keselamatan|tujuan organisasi;profil risiko;feedback pekerja;indikator|keputusan konsisten;akuntabilitas;dialog;perbaikan hambatan|kampanye tanpa keputusan;menghukum pelaporan;pesan berbeda dari tindakan
worker-consultation|Konsultasi dan Partisipasi Pekerja|melibatkan pekerja dalam identifikasi masalah, desain kontrol, perubahan, dan evaluasi efektivitas|forum;wakil pekerja;data risiko;rencana perubahan|masukan terdokumentasi;keputusan transparan;kontrol yang dapat digunakan|sekadar sosialisasi;hanya mengundang supervisor;masukan tidak ditanggapi
occupational-health-surveillance|Surveilans Kesehatan Kerja|memantau dampak pajanan pada kesehatan secara etis dan menghubungkannya dengan perbaikan kontrol|profil pajanan;kelompok pekerja;protokol medis;consent;privacy|hasil agregat;rujukan;review kontrol;rekam rahasia|tes tanpa kaitan pajanan;data medis dibuka;hasil tidak memicu perbaikan
noise-control-planning|Perencanaan Pengendalian Kebisingan|memprioritaskan eliminasi, rekayasa sumber-jalur-penerima, administrasi, dan proteksi pendengaran|peta bising;durasi pajanan;mesin;layout;maintenance data|control plan;engineering option;hearing conservation;verification|langsung memberi earplug;tidak mengukur ulang;mengabaikan komunikasi darurat
chemical-inventory|Inventarisasi Bahan Kimia|membuat daftar terkendali bahan, lokasi, jumlah, bahaya, SDS, dan pemilik untuk keputusan risiko dan darurat|daftar pembelian;stock opname;SDS;lokasi;owner|chemical register;gap SDS;prioritas substitusi;emergency information|nama dagang tidak lengkap;bahan sementara tidak dicatat;inventaris tidak diperbarui
emergency-communication|Komunikasi Keadaan Darurat|menyampaikan alarm, instruksi, perubahan, dan status melalui kanal yang tetap berfungsi saat kondisi abnormal|skenario;populasi;alarm;radio;kontak eksternal|communication matrix;message template;backup channel;drill result|pesan ambigu;satu kanal;tidak mengakomodasi kebisingan atau bahasa
management-review|Tinjauan Manajemen K3|menggunakan bukti kinerja, perubahan, risiko, sumber daya, dan tindakan untuk keputusan pimpinan|audit;KPI;incident;compliance;objectives;resources|keputusan;resource allocation;priorities;assigned actions|hanya presentasi statistik;tanpa keputusan;action lama tidak ditinjau
legal-register|Penyusunan Register Peraturan K3|mengidentifikasi aturan yang berlaku, kewajiban, unit terdampak, bukti kepatuhan, dan perubahan status|profil kegiatan;lokasi;peralatan;bahan;daftar regulasi resmi|legal register;obligation mapping;owner;evidence;update log|hanya daftar judul;status tidak diperiksa;tidak menghubungkan kewajiban dengan bukti`;

const split = (value: string) => value.split(';').map((item) => item.trim()).filter(Boolean);

export const professionSeeds: ProfessionSeed[] = professionRows.trim().split('\n').map((line) => {
  const [slug, title, role, contexts, skills, nature] = line.split('|');
  return { slug, title, role, contexts: split(contexts), skills: split(skills), nature: nature as ProfessionSeed['nature'] };
});

export const competencySeeds: CompetencySeed[] = competencyRows.trim().split('\n').map((line) => {
  const [slug, title, purpose, inputs, outputs, errors] = line.split('|');
  return { slug, title, purpose, inputs: split(inputs), outputs: split(outputs), errors: split(errors) };
});
