import type { CompetencySeed, GuideSeed, IndustrySeed, LocationSeed, ProfessionSeed } from './content-types';
import { competencySeeds as detailedCompetencies, professionSeeds as detailedProfessions } from './content-seeds-people';

const acronym: Record<string, string> = { k3:'K3', p3k:'P3K', smk3:'SMK3', hse:'HSE', sds:'SDS', ghs:'GHS', apar:'APAR', hydrant:'Hydrant', loto:'LOTO', hiradc:'HIRADC', jsa:'JSA', hazop:'HAZOP', hazid:'HAZID', lopa:'LOPA', p2k3:'P2K3', apd:'APD', rkk:'RKK', b3:'B3', h2s:'H2S', iso:'ISO', csms:'CSMS', ptw:'PTW' };
export const titleize = (slug: string) => slug.split('-').map((word) => acronym[word] ?? `${word.charAt(0).toUpperCase()}${word.slice(1)}`).join(' ');

const extraRoles = `ahli-k3-listrik,ahli-k3-kebakaran,ahli-k3-konstruksi,ahli-keselamatan-konstruksi,ahli-k3-pesawat-angkat-angkut,ahli-k3-bejana-tekanan,ahli-k3-pesawat-uap,ahli-k3-lingkungan-kerja,safety-inspector,penguji-k3,sekretaris-p2k3,petugas-peran-kebakaran,anggota-regu-kebakaran,koordinator-kebakaran,ahli-k3-spesialis-kebakaran,operator-mobile-crane,operator-tower-crane,operator-overhead-crane,operator-gantry-crane,operator-hoist,operator-gondola,operator-manlift,operator-excavator,operator-bulldozer,operator-wheel-loader,operator-dump-truck,operator-pesawat-uap,operator-bejana-tekanan,operator-kompresor,operator-refrigerasi,teknisi-pesawat-uap,teknisi-bejana-tekanan,teknisi-pesawat-tenaga-produksi,teknisi-deteksi-gas,teknisi-ruang-terbatas,penyelamat-ruang-terbatas,entrant-ruang-terbatas,attendant-ruang-terbatas,entry-supervisor-ruang-terbatas,tkpk-tingkat-1,tkpk-tingkat-2,tkpk-tingkat-3,tkbt-tingkat-1,tkbt-tingkat-2,teknisi-akses-tali,supervisor-lifting,inspektor-scaffolding,supervisor-scaffolding,petugas-k3-konstruksi,supervisor-k3-konstruksi,ahli-muda-k3-konstruksi,ahli-madya-k3-konstruksi,ahli-utama-k3-konstruksi,safetyman-migas,pengawas-k3-migas,ahli-k3-migas,petugas-k3-laboratorium,pengawas-k3-laboratorium,petugas-k3-rumah-sakit,koordinator-k3-rumah-sakit,petugas-proteksi-radiasi,petugas-limbah-b3,koordinator-csms,contractor-safety-officer,fleet-safety-officer,road-safety-officer,marine-safety-officer,aviation-safety-officer,petugas-biosafety,petugas-konservasi-pendengaran,petugas-program-respirator,petugas-surveilans-kesehatan-kerja,emergency-planner,fire-safety-manager,incident-commander,first-responder,spill-response-leader,confined-space-rescue-leader`;

const generatedProfessions: ProfessionSeed[] = extraRoles.split(',').map((slug) => {
  const title = titleize(slug);
  const regulated = /ahli-k3|operator|teknisi|tkpk|tkbt|petugas-peran|regu-kebakaran|koordinator-kebakaran/.test(slug);
  const scheme = /muda|madya|utama|akses-tali|inspektor|supervisor/.test(slug);
  return { slug, title, role: `menjalankan tanggung jawab ${title.toLowerCase()} pada pekerjaan, peralatan, atau sistem yang menjadi ruang lingkupnya`, contexts: ['operasi industri','proyek','fasilitas dengan risiko terkait'], skills: ['identifikasi bahaya','pengendalian operasional','pemeriksaan bukti','komunikasi dan pelaporan'], nature: regulated ? 'regulated' : scheme ? 'scheme' : 'organizational' };
});
export const professionSeeds: ProfessionSeed[] = [...new Map([...detailedProfessions, ...generatedProfessions].map((seed) => [seed.slug, seed])).values()].slice(0, 95);

const inspectTargets = `apar,hydrant,sprinkler,alarm-kebakaran,pintu-darurat,jalur-evakuasi,kotak-p3k,eyewash,safety-shower,full-body-harness,lanyard,lifeline,anchor-point,scaffolding,tangga,platform-kerja,forklift,reach-truck,mobile-crane,overhead-crane,tower-crane,gantry-crane,hoist,sling,shackle,wire-rope,gas-detector,respirator,scba,panel-listrik,grounding,rcd,mesin-produksi,machine-guard,boiler,bejana-tekanan,tangki-timbun,kompresor,refrigerasi,silinder-gas,gudang-bahan-kimia,rak-gudang,alat-berat,kendaraan-perusahaan,area-kerja`;
const controlTargets = `pekerjaan-panas,pekerjaan-ketinggian,ruang-terbatas,penggalian,pembongkaran,pekerjaan-listrik,isolasi-energi,operasi-lifting,operasi-forklift,lalu-lintas-internal,bahan-kimia,limbah-b3,pajanan-kebisingan,pajanan-getaran,iklim-kerja,pencahayaan,udara-tempat-kerja,ergonomi,manual-handling,kelelahan-kerja,bahaya-psikososial,kontraktor,perubahan-proses,simops,shutdown-turnaround,temporary-works,pekerjaan-atap,pekerjaan-beton,pekerjaan-baja,pekerjaan-pengelasan,pekerjaan-grinding,penyimpanan-gas,penyimpanan-bahan-mudah-terbakar,reaksi-kimia,operasi-laboratorium,infeksi-okupasi,benda-tajam,radiasi,alat-berat,blind-spot,kendaraan-mundur,kerja-malam,kerja-sendiri,akses-pengunjung,housekeeping`;
const documentTargets = `kebijakan-k3,sasaran-k3,program-kerja-k3,legal-register-k3,hiradc,jsa,sop-k3,instruksi-kerja,permit-to-work,izin-kerja-panas,izin-ruang-terbatas,izin-kerja-ketinggian,izin-penggalian,prosedur-loto,lifting-plan,rigging-plan,traffic-management-plan,rencana-tanggap-darurat,peta-evakuasi,pre-incident-plan,rencana-rescue,program-inspeksi,program-pemeliharaan,program-kesehatan-kerja,program-konservasi-pendengaran,program-respirator,program-ergonomi,program-manajemen-kontraktor,matriks-kompetensi,training-needs-analysis,toolbox-meeting,safety-induction,laporan-insiden,kronologi-insiden,analisis-akar-masalah,tindakan-korektif,laporan-p2k3,laporan-audit,checklist-inspeksi,register-bahan-kimia,register-sds,register-peralatan-kritis,register-izin,register-pelatihan,register-pemeriksaan-kesehatan`;
const assessTargets = `risiko-k3,risiko-kimia,risiko-ergonomi,risiko-kesehatan-kerja,risiko-kontraktor,risiko-proyek,risiko-lifting,risiko-ruang-terbatas,risiko-ketinggian,risiko-kebakaran,risiko-listrik,risiko-mesin,risiko-transportasi,risiko-psikososial,risiko-perubahan,efektivitas-pengendalian,kepatuhan-k3,kinerja-smk3,kinerja-kontraktor,kualitas-hiradc,kualitas-jsa,kualitas-izin-kerja,kesiapan-darurat,kesiapan-rescue,kesiapan-audit,kompetensi-pekerja,kebutuhan-pelatihan,pajanan-kebisingan,pajanan-getaran,pajanan-panas,pajanan-bahan-kimia,kualitas-udara,postur-kerja,beban-angkat-manual,fit-to-work,return-to-work,integritas-barrier,critical-control,backlog-pemeliharaan,budaya-k3,partisipasi-pekerja,kualitas-data-insiden,tren-insiden,risiko-rantai-pasok,risiko-pekerjaan-nonrutin`;
const manageTargets = `smk3,p2k3,audit-k3,inspeksi-k3,legal-register,dokumen-k3,rekaman-k3,tindakan-korektif,perubahan,kontraktor,kompetensi,pelatihan,kinerja-k3,indikator-k3,komunikasi-k3,konsultasi-pekerja,izin-kerja,isolasi-energi,barrier-kritis,peralatan-kritis,darurat,evakuasi,rescue,kesehatan-kerja,surveilans-kesehatan,pajanan,respirator,konservasi-pendengaran,ergonomi,kelelahan,bahan-kimia,sds,limbah-b3,proteksi-kebakaran,lalu-lintas,alat-angkat,scaffolding,pekerjaan-ketinggian,ruang-terbatas,insiden,near-miss,lesson-learned,kontraktor-multi-tier,shutdown,housekeeping`;

const makeCompetency = (slug: string, action: string): CompetencySeed => {
  const object = slug.replace(`${action}-`, '');
  const title = titleize(slug);
  const actionText: Record<string,string> = { memeriksa:'memastikan kondisi dan bukti keselamatan', mengendalikan:'menetapkan serta memverifikasi pengendalian', menyusun:'menghasilkan dokumen yang mencerminkan kondisi nyata', menilai:'membuat keputusan berbasis kriteria dan bukti', mengelola:'merencanakan, menjalankan, memantau, dan memperbaiki sistem' };
  return { slug, title, purpose: `${actionText[action]} untuk ${titleize(object).toLowerCase()}`, inputs: [`ruang lingkup ${titleize(object).toLowerCase()}`,'kriteria atau prosedur yang berlaku','observasi dan data aktual','masukan pekerja atau pemilik proses'], outputs: [`hasil ${title.toLowerCase()} yang tertelusur`,'daftar kesenjangan dan prioritas','tindakan dengan penanggung jawab','catatan verifikasi efektivitas'], errors: ['menggunakan checklist tanpa melihat kondisi','menyalin hasil lokasi lain','tidak menyatakan asumsi','menutup tindakan tanpa bukti'] };
};

const generatedCompetencies = [
  ...inspectTargets.split(',').map((target) => makeCompetency(`memeriksa-${target}`,'memeriksa')),
  ...controlTargets.split(',').map((target) => makeCompetency(`mengendalikan-${target}`,'mengendalikan')),
  ...documentTargets.split(',').map((target) => makeCompetency(`menyusun-${target}`,'menyusun')),
  ...assessTargets.split(',').map((target) => makeCompetency(`menilai-${target}`,'menilai')),
  ...manageTargets.split(',').map((target) => makeCompetency(`mengelola-${target}`,'mengelola')),
];
export const competencySeeds: CompetencySeed[] = [...new Map([...detailedCompetencies, ...generatedCompetencies].map((seed) => [seed.slug, seed])).values()].slice(0, 260);

const guideFromCompetency = (seed: CompetencySeed): GuideSeed => ({ slug:`cara-${seed.slug}`, title:`Cara ${seed.title}`, purpose:seed.purpose, inputs:seed.inputs, steps:[`tetapkan tujuan dan ruang lingkup ${seed.title.toLowerCase()}`,'kumpulkan data serta verifikasi kondisi lapangan','jalankan metode secara berurutan','catat hasil, asumsi, dan kesenjangan','tetapkan tindakan dan periksa efektivitas'], output:seed.outputs[0] });
const artifacts = competencySeeds.slice(0, 70).flatMap((seed) => [
  { slug:`contoh-${seed.slug}`, title:`Contoh ${seed.title}`, purpose:`memahami bentuk hasil ${seed.title.toLowerCase()} melalui contoh terisi`, inputs:seed.inputs, steps:['tetapkan skenario contoh','isi setiap bagian dengan data yang konsisten','jelaskan alasan keputusan','bedakan contoh dari data perusahaan','tinjau hasil bersama pemilik proses'], output:`contoh terisi ${seed.title.toLowerCase()} beserta catatan adaptasi` },
  { slug:`checklist-${seed.slug}`, title:`Checklist ${seed.title}`, purpose:`memeriksa kelengkapan dan mutu ${seed.title.toLowerCase()}`, inputs:seed.inputs, steps:['tentukan kriteria checklist','kelompokkan item menurut urutan kerja','catat ya, tidak, atau tidak berlaku beserta bukti','eskalasi kondisi kritis','ubah temuan menjadi tindakan'], output:`checklist ${seed.title.toLowerCase()} dengan bukti dan tindakan` },
  { slug:`template-${seed.slug}`, title:`Template ${seed.title}`, purpose:`menyusun struktur dokumen ${seed.title.toLowerCase()} yang dapat diisi dan ditinjau`, inputs:seed.inputs, steps:['buat identitas dokumen','tambahkan kolom data dan kriteria','sediakan bagian keputusan serta persetujuan','uji template pada satu kasus','revisi kolom yang tidak membantu keputusan'], output:`template ${seed.title.toLowerCase()} dengan petunjuk pengisian` },
  { slug:`kesalahan-umum-${seed.slug}`, title:`Kesalahan Umum ${seed.title}`, purpose:`mengenali dan memperbaiki kegagalan mutu pada ${seed.title.toLowerCase()}`, inputs:seed.inputs, steps:['kumpulkan contoh hasil bermasalah','kelompokkan kesalahan data, metode, dan tindak lanjut','telusuri penyebab proses','tetapkan perbaikan','uji kembali pada kasus baru'], output:`daftar kesalahan ${seed.title.toLowerCase()} dan tindakan pencegahannya` },
] satisfies GuideSeed[]);
export const guideSeeds: GuideSeed[] = [...competencySeeds.map(guideFromCompetency), ...artifacts];

const industryGroups: Record<string,string[]> = {
  manufacturing: 'manufaktur-otomotif,komponen-otomotif,elektronik,semikonduktor,tekstil,garmen,alas-kaki,makanan,minuman,farmasi,kosmetik,kimia,pupuk,cat-dan-coating,plastik,karet,pulp-dan-kertas,percetakan,kemasan,semen,baja,pengecoran-logam,kaca,keramik,furnitur'.split(','),
  construction: 'gedung-tinggi,perumahan,jalan-raya,jembatan,perkeretaapian,bandar-udara,pelabuhan,bendungan,terowongan,infrastruktur-air,pipa-transmisi,menara-telekomunikasi,transmisi-listrik,instalasi-surya,pembongkaran-bangunan'.split(','),
  energy: 'pertambangan-batubara,pertambangan-nikel,pertambangan-emas,quarry,migas-hulu,migas-hilir,kilang-minyak,petrokimia,panas-bumi,pltu,pltg,plta,pembangkit-surya,pembangkit-angin,bioenergi'.split(','),
  logistics: 'pergudangan,trucking,transportasi-bus,perkeretaapian-operasi,operasi-bandara,ground-handling,operasi-pelabuhan,pelayaran,galangan-kapal,kurir,logistik-rantai-dingin,depo-kontainer'.split(','),
  healthcare: 'rumah-sakit,klinik,puskesmas,laboratorium-diagnostik,laboratorium-riset,fasilitas-farmasi,klinik-gigi,fasilitas-veteriner,bank-darah,pengelolaan-limbah-medis'.split(','),
  services: 'perkantoran,ritel,pusat-perbelanjaan,hotel,restoran,sekolah,universitas,perbankan,pusat-data,call-center,jasa-kebersihan,event-organizer'.split(','),
  agriculture: 'perkebunan-kelapa-sawit,pabrik-kelapa-sawit,perkebunan-karet,perkebunan-teh-kopi,kehutanan,penggergajian-kayu,perikanan,budidaya-perairan,peternakan-unggas,rumah-potong-hewan'.split(','),
  utilities: 'pengolahan-air-minum,pengolahan-air-limbah,pengelolaan-sampah,pengelolaan-limbah-b3,daur-ulang,distribusi-listrik'.split(','),
};
const industryProfiles: Record<string,Omit<IndustrySeed,'slug'|'title'>> = {
  manufacturing:{activities:['operasi mesin','pemindahan material','pemeliharaan','penyimpanan'],hazards:['bagian mesin bergerak','energi berbahaya','kendaraan internal','kebakaran dan pajanan'],controls:['machine guarding dan LOTO','segregasi lalu lintas','pemeliharaan kritis','pengendalian pajanan'],roles:['operator','teknisi','supervisor','personel K3']},
  construction:{activities:['mobilisasi','pekerjaan struktur','lifting','temporary works'],hazards:['jatuh dari ketinggian','alat berat','runtuh','listrik sementara'],controls:['RKK dan izin kerja','proteksi jatuh','lifting plan','inspeksi temporary works'],roles:['site manager','supervisor','kontraktor','personel keselamatan konstruksi']},
  energy:{activities:['ekstraksi atau pembangkitan','operasi proses','pemeliharaan','transportasi material'],hazards:['energi besar','kebakaran atau ledakan','alat berat','paparan kesehatan'],controls:['barrier kritis','permit dan isolasi','integritas aset','tanggap darurat'],roles:['operator','teknisi','engineer','tim HSE']},
  logistics:{activities:['penerimaan','penyimpanan','pemindahan','pengiriman'],hazards:['interaksi kendaraan','jatuhnya material','rak','kelelahan'],controls:['traffic plan','inspeksi alat','racking safety','journey management'],roles:['operator','driver','warehouse supervisor','koordinator K3']},
  healthcare:{activities:['pelayanan','diagnostik','sterilisasi','pengelolaan limbah'],hazards:['infeksi','benda tajam','bahan kimia','ergonomi dan kekerasan'],controls:['standard precaution','sharps safety','ventilasi','program K3 fasilitas'],roles:['tenaga kesehatan','teknisi fasilitas','tim K3','pengelola limbah']},
  services:{activities:['pelayanan pelanggan','kerja komputer','pemeliharaan fasilitas','kegiatan publik'],hazards:['ergonomi','kebakaran','listrik','psikososial'],controls:['desain kerja','proteksi kebakaran','inspeksi fasilitas','kesiapsiagaan'],roles:['facility manager','HR','security','personel K3']},
  agriculture:{activities:['budidaya','panen','pengolahan awal','transportasi'],hazards:['mesin dan alat','pestisida','biologi','panas dan medan'],controls:['pengamanan mesin','pengelolaan pestisida','higiene','rencana transportasi'],roles:['pekerja lapangan','operator','mandor','personel K3']},
  utilities:{activities:['operasi instalasi','pemeliharaan jaringan','pengolahan','respons gangguan'],hazards:['energi','ruang terbatas','bahan kimia','biologi'],controls:['isolasi','permit ruang terbatas','pengendalian bahan','emergency response'],roles:['operator','teknisi','supervisor','tim K3']},
};
export const industrySeeds: IndustrySeed[] = Object.entries(industryGroups).flatMap(([group,slugs]) => slugs.map((slug) => ({slug,title:`K3 ${titleize(slug)}`,...industryProfiles[group]})));

export const locationSeeds: LocationSeed[] = [
  {slug:'yogyakarta',name:'Yogyakarta',province:'Daerah Istimewa Yogyakarta',sectors:['pendidikan','manufaktur','layanan','konstruksi'],ownerLocation:true},
  {slug:'sleman',name:'Sleman',province:'Daerah Istimewa Yogyakarta',sectors:['pendidikan','layanan','manufaktur','konstruksi'],ownerLocation:true},
  {slug:'semarang',name:'Semarang',province:'Jawa Tengah',sectors:['manufaktur','logistik','pelabuhan','konstruksi'],ownerLocation:true},
];
