import type { ProgramSeed, SourceRef } from './content-types';

export const officialSources: Record<string, SourceRef> = {
  uu1: { label: 'UU Nomor 1 Tahun 1970', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/47614/uu-no-1-tahun-1970' },
  pp50: { label: 'PP Nomor 50 Tahun 2012 tentang SMK3', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/5263/pp-no-50-tahun-2012' },
  bnsp: { label: 'Direktori LSP dan skema sertifikasi', publisher: 'BNSP', url: 'https://bnsp.go.id/lsp' },
  ak3u: { label: 'Pedoman sertifikasi calon Ahli K3 Umum', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/download.php?id=494' },
  p3k: { label: 'Permenaker PER.15/MEN/VIII/2008 tentang P3K', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  ruang: { label: 'Permenaker Nomor 11 Tahun 2023 tentang K3 Ruang Terbatas', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/283638/permenaker-no-11-tahun-2023' },
  tinggi: { label: 'Permenaker Nomor 9 Tahun 2016 tentang K3 Pekerjaan pada Ketinggian', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  angkat: { label: 'Permenaker Nomor 8 Tahun 2020 tentang K3 Pesawat Angkat dan Angkut', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/166211/permenaker-no-8-tahun-2020' },
  listrik: { label: 'Permenaker Nomor 12 Tahun 2015 tentang K3 Listrik', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  lingkungan: { label: 'Permenaker Nomor 5 Tahun 2018 tentang K3 Lingkungan Kerja', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan/detail/1546/peraturan-menteri-ketenagakerjaan-nomor-5-tahun-2018' },
  kimia: { label: 'Kepmenaker KEP.187/MEN/1999 tentang bahan kimia berbahaya', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  apd: { label: 'Permenaker PER.08/MEN/VII/2010 tentang APD', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  smk3audit: { label: 'Permenaker Nomor 26 Tahun 2014 tentang penilaian SMK3', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/145618/permenaker-no-26-tahun-2014' },
  bejana: { label: 'Permenaker Nomor 37 Tahun 2016 tentang bejana tekanan dan tangki timbun', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  produksi: { label: 'Permenaker Nomor 38 Tahun 2016 tentang pesawat tenaga dan produksi', publisher: 'JDIH Kemnaker', url: 'https://jdih.kemnaker.go.id/peraturan' },
  konstruksi: { label: 'Permen PUPR Nomor 10 Tahun 2021 tentang Pedoman SMKK', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/216875/permen-pupr-no-10-tahun-2021' },
  rumahsakit: { label: 'Permenkes Nomor 66 Tahun 2016 tentang K3 Rumah Sakit', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/114482/permenkes-no-66-tahun-2016' },
  tambang: { label: 'Permen ESDM Nomor 26 Tahun 2018', publisher: 'Database Peraturan BPK', url: 'https://peraturan.bpk.go.id/Details/142457/permen-esdm-no-26-tahun-2018' },
};

const rows = `
ahli-k3-umum|Pelatihan Ahli K3 Umum|penerapan norma K3 lintas bidang, pengawasan tempat kerja, dan peran calon Ahli K3 Umum|calon praktisi K3;pengawas;anggota P2K3;personel perusahaan yang diproyeksikan menjalankan fungsi K3|menjelaskan dasar hukum K3;mengidentifikasi bahaya lintas bidang;menyusun rekomendasi pengawasan;memahami proses evaluasi dan penunjukan|dasar K3;kelembagaan dan pengawasan;mekanik;listrik;kebakaran;konstruksi;lingkungan kerja;SMK3;manajemen risiko|kemnaker|uu1;pp50;ak3u
auditor-smk3|Pelatihan Auditor SMK3|perencanaan, pelaksanaan, pelaporan, dan tindak lanjut audit penerapan SMK3|auditor internal;personel HSE;wakil manajemen;anggota tim evaluasi sistem|menyusun rencana audit;mengumpulkan bukti objektif;menulis temuan;memantau tindakan perbaikan|kriteria SMK3;prinsip audit;program audit;wawancara dan sampling;klasifikasi temuan;laporan;tindak lanjut|kemnaker|pp50;smk3audit
petugas-p3k-tempat-kerja|Pelatihan Petugas P3K di Tempat Kerja|kesiapsiagaan pertolongan pertama, penilaian awal korban, dan pengelolaan fasilitas P3K|pekerja yang ditunjuk perusahaan;anggota tim tanggap darurat;pengawas area|mengamankan lokasi;melakukan penilaian awal;memberikan bantuan sesuai batas kompetensi;mengaktifkan rujukan|sistem P3K;penilaian korban;cedera dan kondisi medis;resusitasi sesuai pedoman;evakuasi;pelaporan|kemnaker|p3k;uu1
k3-kebakaran|Pelatihan K3 Penanggulangan Kebakaran|pencegahan kebakaran, organisasi tanggap darurat, dan respons awal yang aman|petugas kebakaran tempat kerja;fire warden;anggota tim tanggap darurat;pengawas fasilitas|mengenali kelas kebakaran;memilih media pemadam;melakukan respons awal;menata evakuasi|teori api;sumber penyalaan;proteksi aktif dan pasif;APAR;alarm;evakuasi;latihan darurat|kemnaker|uu1
petugas-k3-kimia|Pelatihan Petugas K3 Kimia|pengendalian bahan kimia berbahaya, komunikasi bahaya, penyimpanan, dan tanggap tumpahan|petugas K3 kimia;operator proses;petugas gudang;pengawas laboratorium|membaca SDS;menginventarisasi bahan;menilai kompatibilitas penyimpanan;merespons paparan dan tumpahan|klasifikasi bahaya;SDS dan label;inventaris;penyimpanan;APD;pemantauan pajanan;tanggap darurat|kemnaker|kimia;lingkungan;apd
ahli-k3-kimia|Pelatihan Ahli K3 Kimia|perancangan program pengendalian risiko kimia dan evaluasi kepatuhan di tempat kerja|praktisi K3;higienis industri;supervisor proses;personel yang diproyeksikan pada fungsi ahli K3 kimia|menilai risiko kimia;menetapkan pengendalian;merancang pemantauan;mengaudit pengelolaan bahan|toksikologi dasar;penilaian pajanan;ventilasi;substitusi;monitoring;emergency planning;dokumentasi|kemnaker|kimia;lingkungan;uu1
k3-listrik|Pelatihan K3 Listrik|pengenalan bahaya listrik dan praktik kerja aman pada instalasi serta peralatan listrik|teknisi;operator;pengawas pemeliharaan;pekerja nonlistrik yang terpapar bahaya listrik|mengenali sumber energi;memilih pengamanan;menerapkan izin kerja;merespons keadaan darurat listrik|sengatan dan arc flash;proteksi;grounding;isolasi energi;alat ukur;izin kerja;pertolongan awal|practical|listrik;uu1
teknisi-k3-listrik|Pelatihan Teknisi K3 Listrik|kompetensi teknis keselamatan untuk pemeriksaan, pemeliharaan, dan pekerjaan kelistrikan|teknisi listrik;personel pemeliharaan;pengawas instalasi|memeriksa kondisi instalasi;mengendalikan energi;memilih alat kerja;menyusun catatan pemeriksaan|regulasi listrik;proteksi;pengujian;LOTO;pekerjaan bertegangan;APD;pelaporan|kemnaker|listrik;apd
k3-konstruksi|Pelatihan K3 Konstruksi|pengelolaan keselamatan proyek sejak perencanaan sampai pengendalian pekerjaan berisiko tinggi|personel proyek;site engineer;supervisor;kontraktor;tim HSE|menyusun rencana keselamatan;mengendalikan pekerjaan kritis;mengelola kontraktor;memantau kepatuhan|SMKK;HIRADC proyek;pekerjaan tinggi;lifting;galian;listrik sementara;housekeeping;tanggap darurat|mixed|konstruksi;tinggi;angkat
k3-ruang-terbatas|Pelatihan K3 Ruang Terbatas|perencanaan masuk ruang terbatas, pengujian atmosfer, pengawasan, dan penyelamatan|entrant;attendant;supervisor masuk;gas tester;tim penyelamat|mengklasifikasikan ruang;menerbitkan izin;memantau atmosfer;menjaga komunikasi;mengaktifkan rescue|identifikasi ruang;permit entry;gas testing;ventilasi;isolasi;peran personel;rescue plan|mixed|ruang;bnsp
bekerja-di-ketinggian|Pelatihan Bekerja di Ketinggian|pencegahan jatuh melalui perencanaan, sistem akses, proteksi kolektif, dan perlindungan personal|pekerja ketinggian;pengawas;teknisi;petugas rescue|memilih sistem akses;memeriksa peralatan;menetapkan anchor;menghitung clearance;menyiapkan rescue|hirarki proteksi jatuh;scaffold;platform;tangga;full body harness;anchor;rescue|mixed|tinggi;bnsp;apd
scaffolding|Pelatihan Scaffolding|pemasangan, penggunaan, pemeriksaan, dan pembongkaran perancah secara aman|scaffolder;inspektor;pengawas konstruksi;pengguna perancah|mengenali komponen;memeriksa fondasi dan bracing;menilai akses;menetapkan status penggunaan|jenis perancah;beban;fondasi;ereksi;bracing;platform;tagging;inspeksi;pembongkaran|mixed|tinggi;konstruksi;bnsp
operator-forklift|Pelatihan Operator Forklift|operasi forklift, pemeriksaan harian, stabilitas beban, dan pengendalian lalu lintas internal|calon operator;operator gudang;pengawas logistik|melakukan pre-use check;membaca kapasitas;mengangkat dan memindahkan beban;parkir aman|komponen;load chart;stability triangle;inspeksi;rute;stacking;charging/refueling;pelaporan|kemnaker|angkat;bnsp
operator-crane|Pelatihan Operator Crane|operasi crane sesuai kapasitas, kondisi alat, rencana pengangkatan, dan komunikasi isyarat|calon operator crane;operator;pengawas lifting|memeriksa crane;membaca load chart;menilai konfigurasi;berkomunikasi dengan rigger;menghentikan operasi tidak aman|jenis crane;komponen;load chart;outrigger;radius;rigging;signal;inspeksi;cuaca|kemnaker|angkat;bnsp
juru-ikat-rigger|Pelatihan Juru Ikat dan Rigger|pemilihan alat bantu angkat, teknik pengikatan, pusat gravitasi, dan komunikasi lifting|rigger;juru ikat;signalman;anggota tim lifting|memilih sling;menghitung sudut;memeriksa aksesori;mengendalikan beban;memberikan isyarat|sling dan hardware;WLL;sling angle;center of gravity;hitch;tag line;signal;inspection|mixed|angkat;bnsp
pesawat-angkat-angkut|Pelatihan K3 Pesawat Angkat dan Angkut|pengawasan keselamatan berbagai peralatan angkat dan angkut di tempat kerja|pengawas;praktisi K3;personel pemeliharaan;penanggung jawab operasi|mengidentifikasi klasifikasi alat;memeriksa dokumen;menilai kondisi operasi;menetapkan tindak lanjut|jenis alat;persyaratan operator;inspeksi;pengujian;zona operasi;maintenance;pelaporan|kemnaker|angkat;uu1
boiler-pesawat-uap|Pelatihan K3 Boiler dan Pesawat Uap|operasi aman boiler, pengendalian tekanan, kualitas air, pembakaran, dan respons abnormal|operator boiler;teknisi utilitas;pengawas pemeliharaan|memeriksa perangkat pengaman;memantau parameter;merespons kondisi abnormal;menjaga log operasi|prinsip uap;komponen;water treatment;pembakaran;safety valve;start-stop;emergency;inspection|kemnaker|bejana;uu1
bejana-tekan|Pelatihan K3 Bejana Tekan|bahaya tekanan, perangkat proteksi, inspeksi, dan pengoperasian bejana serta tangki tertentu|operator;teknisi;inspektor internal;pengawas fasilitas|mengenali mode kegagalan;memeriksa pengaman;menilai korosi;menjaga batas operasi|jenis bejana;tekanan dan temperatur;relief device;korosi;NDT;operasi;isolasi;dokumentasi|kemnaker|bejana;uu1
juru-las-welder|Pelatihan Juru Las|praktik pengelasan aman, pengendalian panas, radiasi, asap las, listrik, dan kebakaran|juru las;fitter;pengawas fabrikasi;petugas hot work|memeriksa mesin dan kabel;menata area hot work;memilih APD;mengendalikan asap;menilai hasil awal|proses las;bahaya listrik;gas cylinder;fume;fire watch;WPS dasar;APD;housekeeping|mixed|apd;lingkungan;bnsp
higiene-industri|Pelatihan Higiene Industri|antisipasi, rekognisi, evaluasi, dan pengendalian pajanan faktor lingkungan kerja|higienis industri;praktisi K3;petugas kesehatan kerja;supervisor|menyusun strategi sampling;memahami hasil ukur;menilai pajanan;merekomendasikan kontrol|bahaya fisika;kimia;biologi;ergonomi;sampling;NAB;ventilasi;pelaporan|mixed|lingkungan;bnsp
k3-laboratorium|Pelatihan K3 Laboratorium|pengendalian bahan, peralatan, reaksi, limbah, dan keadaan darurat laboratorium|analis;laboran;peneliti;mahasiswa;pengawas laboratorium|menilai prosedur eksperimen;menyimpan bahan kompatibel;menggunakan fume hood;merespons tumpahan|SDS;segregasi bahan;fume hood;gas cylinder;sharps;limbah;spill kit;emergency shower|practical|kimia;lingkungan;apd
k3-rumah-sakit|Pelatihan K3 Rumah Sakit|pengelolaan risiko pekerja, pasien, fasilitas, bahan, infeksi, dan keadaan darurat rumah sakit|tim K3RS;tenaga kesehatan;teknisi fasilitas;manajemen unit|memetakan risiko unit;mengendalikan pajanan;menata kesiapsiagaan;memantau insiden pekerja|K3RS;infeksi okupasi;sharps;gas medis;radiasi;ergonomi;kebakaran;limbah;evakuasi|practical|rumahsakit;lingkungan
k3-pertambangan|Pelatihan K3 Pertambangan|pengendalian risiko operasi tambang, alat berat, geoteknik, peledakan, lalu lintas, dan kesehatan kerja|pekerja tambang;pengawas operasional;kontraktor;tim HSE|mengenali bahaya kritis;menetapkan kontrol fatal risk;melakukan inspeksi;menganalisis insiden|kaidah pertambangan;ground control;mobile equipment;blasting;fatigue;dust;emergency response|mixed|tambang;bnsp
k3-migas|Pelatihan K3 Minyak dan Gas|pengendalian energi proses, hidrokarbon, pekerjaan berizin, integritas aset, dan tanggap darurat|operator migas;kontraktor;teknisi;pengawas;tim HSE|memahami process safety;menerapkan PTW dan isolasi;mengendalikan gas;menyiapkan respons kebakaran|process hazard;flammable atmosphere;gas testing;PTW;LOTO;SIMOPS;integrity;emergency|mixed|uu1;bnsp
hiradc|Pelatihan HIRADC|identifikasi bahaya, penilaian risiko, penetapan pengendalian, dan pemeliharaan register risiko|praktisi K3;supervisor;anggota tim risiko;process owner|menguraikan aktivitas;menulis skenario risiko;menilai risiko;memilih kontrol;menilai risiko sisa|konteks;task breakdown;hazard-event-impact;risk matrix;hierarchy of controls;action plan;review|practical|pp50;uu1
job-safety-analysis|Pelatihan Job Safety Analysis|analisis langkah kerja untuk mengenali bahaya dan menetapkan cara kerja aman sebelum tugas dilakukan|supervisor;pelaksana;permit issuer;anggota tim K3|memecah pekerjaan;mengidentifikasi bahaya tiap langkah;menetapkan kontrol;menyelenggarakan briefing|pemilihan pekerjaan;job steps;hazards;controls;responsibility;communication;field verification|practical|uu1
investigasi-kecelakaan-kerja|Pelatihan Investigasi Kecelakaan Kerja|pengumpulan fakta, analisis penyebab, dan perancangan tindakan korektif setelah insiden|investigator;supervisor;anggota P2K3;praktisi K3|mengamankan bukti;melakukan wawancara;membuat timeline;menganalisis akar masalah;menetapkan tindakan|initial response;evidence;interview;timeline;causal analysis;corrective action;reporting|practical|uu1;pp50
lockout-tagout|Pelatihan Lockout Tagout|isolasi dan pengendalian energi berbahaya sebelum servis, inspeksi, atau pemeliharaan|authorized employee;affected employee;teknisi;supervisor pemeliharaan|mengidentifikasi sumber energi;menentukan titik isolasi;memasang kunci;memverifikasi zero energy;memulihkan sistem|energy survey;shutdown;isolation;lock-tag;stored energy;verification;group LOTO;restoration|practical|listrik;produksi
permit-to-work|Pelatihan Permit to Work|pengendalian pekerjaan berisiko melalui izin, verifikasi lapangan, koordinasi, dan penutupan pekerjaan|permit issuer;permit receiver;area authority;supervisor;kontraktor|mengklasifikasikan pekerjaan;memeriksa prasyarat;menetapkan isolasi;melakukan handover;menutup izin|PTW roles;hot work;confined space;excavation;electrical;isolation;SIMOPS;close-out|practical|uu1
inspeksi-k3|Pelatihan Inspeksi K3|perencanaan inspeksi, observasi kondisi, pencatatan bukti, prioritas temuan, dan tindak lanjut|inspektor internal;supervisor;anggota P2K3;praktisi K3|menyusun checklist;melakukan observasi;menulis temuan faktual;menilai prioritas;memverifikasi perbaikan|scope;criteria;observation;interview;evidence;classification;action tracking;verification|practical|pp50;uu1
iso-45001|Pelatihan ISO 45001|pemahaman sistem manajemen K3 berbasis konteks, kepemimpinan, risiko, operasi, evaluasi, dan perbaikan|manajemen;tim implementasi;auditor internal;process owner|memetakan klausul;menilai konteks;mengelola risiko dan peluang;menyiapkan bukti implementasi|context;leadership;planning;support;operation;performance evaluation;improvement|practical|pp50
internal-audit-iso-45001|Pelatihan Internal Audit ISO 45001|audit internal sistem manajemen K3 terhadap kriteria organisasi dan ISO 45001|auditor internal;wakil manajemen;HSE;process owner|menyiapkan audit;menelusuri bukti;mengembangkan pertanyaan;menulis ketidaksesuaian;memantau koreksi|audit principles;program;plan;checklist;interview;sampling;findings;report;follow-up|practical|pp50
ergonomi-tempat-kerja|Pelatihan Ergonomi Tempat Kerja|penilaian kesesuaian tuntutan pekerjaan, postur, beban, repetisi, durasi, dan rancangan stasiun kerja|praktisi K3;HR;supervisor;engineer;tenaga kesehatan kerja|menyaring faktor ergonomi;mengamati tugas;memilih perbaikan;memantau keluhan dan efektivitas|musculoskeletal risk;posture;manual handling;repetition;workstation;administrative and engineering controls|practical|lingkungan
penanganan-bahan-kimia|Pelatihan Penanganan Bahan Kimia|praktik penerimaan, pemindahan, penggunaan, penyimpanan, dan pembuangan bahan kimia secara terkendali|operator;petugas gudang;laboran;cleaning team;supervisor|membaca label dan SDS;memeriksa kompatibilitas;memilih wadah dan APD;menangani tumpahan awal|GHS;SDS;label;segregation;transfer;ventilation;PPE;spill response;waste|practical|kimia;apd
keselamatan-radiasi|Pelatihan Keselamatan Radiasi|prinsip proteksi radiasi, pembatasan pajanan, pemantauan, zona kerja, dan respons kejadian|pekerja radiasi;tenaga kesehatan;operator peralatan;pengawas fasilitas|memahami waktu-jarak-perisai;mematuhi zona;memakai dosimeter;merespons penyimpangan|jenis radiasi;biological effects;ALARA;shielding;monitoring;signage;source security;emergency|practical|uu1
defensive-driving|Pelatihan Defensive Driving|pengambilan keputusan berkendara untuk mengantisipasi bahaya jalan, kendaraan, muatan, dan kondisi pengemudi|pengemudi perusahaan;driver logistik;supervisor transportasi;fleet coordinator|melakukan pemeriksaan kendaraan;mengelola jarak aman;membaca konflik lalu lintas;mengendalikan kelelahan|vehicle check;hazard perception;space management;speed;weather;fatigue;journey management;incident response|practical|uu1
tanggap-darurat|Pelatihan Tanggap Darurat|pembentukan sistem komando, komunikasi, evakuasi, pertolongan, dan pemulihan keadaan darurat|anggota ERT;koordinator darurat;security;supervisor;manajemen krisis|menilai skenario;menetapkan peran;mengaktifkan alarm;mengelola evakuasi;mengevaluasi latihan|risk scenario;organization;alarm;communication;evacuation;accountability;liaison;drill evaluation|practical|pp50;uu1
pemadaman-kebakaran|Pelatihan Pemadaman Kebakaran|keterampilan respons awal kebakaran dengan pemilihan media, pendekatan aman, dan batas penghentian tindakan|fire team;security;operator;anggota ERT|menilai kelas api;memilih APAR;menjaga jalur mundur;mengoperasikan alat;melaporkan kondisi|fire triangle;classes;extinguishing media;APAR inspection;PASS technique;hose basics;withdrawal criteria|practical|uu1
manajemen-kontraktor-k3|Pelatihan Manajemen Kontraktor K3|pengendalian risiko kontraktor sejak prakualifikasi, mobilisasi, pelaksanaan, evaluasi, sampai demobilisasi|contract owner;procurement;project manager;HSE;pengawas kontraktor|menetapkan kriteria K3;menilai dokumen;melakukan orientasi;mengawasi pekerjaan;mengevaluasi kinerja|prequalification;scope risk;contract clauses;mobilization;PTW;monitoring;incident reporting;close-out|practical|pp50;uu1
behavior-based-safety|Pelatihan Behavior Based Safety|observasi perilaku kerja, percakapan keselamatan, analisis penghalang, dan perbaikan sistem tanpa budaya menyalahkan|supervisor;observer;praktisi K3;team leader|mendefinisikan perilaku kritis;melakukan observasi;memberi umpan balik;menganalisis tren;memperbaiki penghalang|behavior and system;critical behavior;observation;feedback;data quality;barrier analysis;program ethics|practical|pp50
operator-gondola|Pelatihan Operator Gondola|operasi gondola atau suspended access equipment, pemeriksaan, komunikasi, dan penyelamatan|calon operator;operator façade;teknisi gedung;pengawas pekerjaan tinggi|memeriksa platform dan wire rope;menguji pengaman;menjaga kapasitas;merespons gangguan|komponen;pre-use check;anchor and suspension;wire rope;load;communication;emergency lowering;rescue|mixed|tinggi;angkat;bnsp
operator-excavator|Pelatihan Operator Excavator|operasi excavator, inspeksi, stabilitas, blind spot, penggalian, dan interaksi dengan pekerja darat|calon operator;operator alat berat;pengawas proyek;spotter|melakukan walk-around;menilai tanah;menjaga swing radius;berkomunikasi dengan spotter;parkir aman|controls;inspection;ground condition;lifting limits;excavation;exclusion zone;transport;shutdown|mixed|angkat;produksi;bnsp
operator-bulldozer|Pelatihan Operator Bulldozer|operasi bulldozer pada pekerjaan pemindahan tanah, lereng, tepi galian, dan area terbatas|calon operator;operator alat berat;pengawas earthwork|memeriksa alat;menilai lereng;menjaga jarak tepi;mengelola visibilitas;memarkir alat|components;inspection;traction;slope;edge protection;blind spots;reversing;maintenance isolation|mixed|produksi;bnsp
operator-wheel-loader|Pelatihan Operator Wheel Loader|operasi wheel loader, stabilitas, pemuatan, lalu lintas area, dan keselamatan attachment|calon operator;operator quarry;operator stockyard;pengawas logistik|memeriksa unit;menilai kapasitas bucket;mengatur rute;menghindari overload;parkir aman|pre-start;bucket and attachment;load stability;travel;stockpile;truck loading;visibility;shutdown|mixed|angkat;produksi;bnsp
operator-reach-truck|Pelatihan Operator Reach Truck|operasi reach truck di lorong sempit, penyimpanan rak tinggi, dan pengendalian pejalan kaki|operator gudang;calon operator;supervisor warehouse|memeriksa unit;membaca kapasitas sisa;memposisikan pallet;menjaga clearance;mengisi baterai aman|pre-use check;capacity plate;racking;aisle rules;load placement;pedestrian segregation;battery charging|practical|angkat
teknisi-akses-tali|Pelatihan Teknisi Akses Tali|perencanaan akses tali, sistem dua tali, pemeriksaan peralatan, manuver, dan penyelamatan|teknisi rope access;pekerja façade;inspektor;tim rescue|memeriksa harness dan rope;membangun sistem cadangan;melakukan manuver;menilai anchor;menyiapkan rescue|equipment;anchor;two-rope system;knots;ascent-descent;work positioning;edge protection;rescue|mixed|tinggi;bnsp
petugas-gas-tester|Pelatihan Petugas Penguji Gas|pengujian atmosfer sebelum dan selama pekerjaan berisiko, termasuk ruang terbatas dan hot work|gas tester;permit issuer;attendant;operator proses|memilih sensor;melakukan bump test;menentukan titik ukur;membaca hasil;menetapkan tindakan|oxygen;flammable gas;toxic gas;instrument check;sampling order;stratification;continuous monitoring;records|mixed|ruang;bnsp
industrial-rescue|Pelatihan Industrial Rescue|penyelamatan industri berbasis skenario, penilaian risiko penolong, sistem tim, dan evakuasi korban|anggota rescue team;ERT;fire team;pekerja akses khusus|menilai adegan;menetapkan komando;membangun sistem evakuasi;menjaga keselamatan tim;melakukan serah terima medis|incident command;scene safety;rope basics;confined-space rescue;casualty packaging;communications;drills|practical|ruang;tinggi
chemical-spill-response|Pelatihan Penanganan Tumpahan Bahan Kimia|respons tumpahan berdasarkan identitas bahan, skala kejadian, ventilasi, APD, penahanan, dan limbah|ERT;operator kimia;petugas gudang;laboran;security|mengidentifikasi bahan;mengisolasi area;memilih APD;menahan sebaran;mengelola dekontaminasi dan limbah|SDS;spill classification;isolation;PPE;containment;absorbent;decontamination;reporting|practical|kimia;apd
contractor-safety-management|Pelatihan Contractor Safety Management System|sistem tata kelola K3 kontraktor yang menghubungkan risiko pekerjaan dengan seleksi, kontrak, pengawasan, dan evaluasi|procurement;contract owner;project manager;HSE;manajemen vendor|menetapkan persyaratan;menilai kapabilitas;menyelaraskan kontrol;memantau indikator;menutup pekerjaan|risk classification;prequalification;contract requirement;bridging;mobilization;monitoring;performance review|practical|pp50;uu1`;

const list = (value: string) => value.split(';').map((item) => item.trim()).filter(Boolean);

const detailedProgramSeeds: ProgramSeed[] = rows.trim().split('\n').map((line) => {
  const [slug, title, scope, audience, outcomes, syllabus, pathway, sourceKeys] = line.split('|');
  return { slug, title, scope, audience: list(audience), outcomes: list(outcomes), syllabus: list(syllabus), pathway: pathway as ProgramSeed['pathway'], sourceKeys: list(sourceKeys) };
});

const compactPrograms: Record<string, string[]> = {
  general: ['ahli-k3-umum-kemnaker|Ahli K3 Umum Kemnaker','ahli-k3-bnsp|Ahli K3 BNSP','ahli-k3-muda-bnsp|Ahli K3 Muda BNSP','ahli-k3-madya-bnsp|Ahli K3 Madya BNSP','ahli-k3-utama-bnsp|Ahli K3 Utama BNSP','operator-k3-bnsp|Operator K3 BNSP','petugas-k3-bnsp|Petugas K3 BNSP','teknisi-k3-bnsp|Teknisi K3 BNSP','analis-k3-bnsp|Analis K3 BNSP','penguji-k3-bnsp|Penguji K3 BNSP','safety-officer-bnsp|Safety Officer BNSP','safety-inspector-bnsp|Safety Inspector BNSP','ahli-smk3-bnsp|Ahli SMK3 BNSP','auditor-internal-smk3|Auditor Internal SMK3','penilai-risiko-k3|Penilai Risiko K3','investigasi-insiden-lanjutan|Investigasi Insiden Lanjutan','pengawas-smk3-kontraktor|Pengawas SMK3 Kontraktor','sekretaris-p2k3|Pembekalan Sekretaris P2K3'],
  height: ['tkpk-tingkat-1-kemnaker|TKPK Tingkat 1 Kemnaker','tkpk-tingkat-2-kemnaker|TKPK Tingkat 2 Kemnaker','tkpk-tingkat-3-kemnaker|TKPK Tingkat 3 Kemnaker','tkbt-tingkat-1-kemnaker|TKBT Tingkat 1 Kemnaker','tkbt-tingkat-2-kemnaker|TKBT Tingkat 2 Kemnaker','operator-akses-tali|Operator Akses Tali','teknisi-akses-tali-tingkat-1|Teknisi Akses Tali Tingkat 1','teknisi-akses-tali-tingkat-2|Teknisi Akses Tali Tingkat 2','ahli-akses-tali|Ahli Akses Tali','operator-akses-struktur-tingkat-1|Operator Akses Struktur Tingkat 1','operator-akses-struktur-tingkat-2|Operator Akses Struktur Tingkat 2','teknisi-akses-struktur|Teknisi Akses Struktur','ahli-akses-struktur|Ahli Akses Struktur','teknisi-k3-bekerja-di-ketinggian|Teknisi K3 Bekerja di Ketinggian','pengawas-k3-bekerja-di-ketinggian|Pengawas K3 Bekerja di Ketinggian','penyelamatan-di-ketinggian|Penyelamatan di Ketinggian'],
  confined: ['teknisi-k3-ruang-terbatas-kemnaker|Teknisi K3 Ruang Terbatas Kemnaker','teknisi-deteksi-gas-ruang-terbatas-kemnaker|Teknisi Deteksi Gas Ruang Terbatas Kemnaker','petugas-k3-penyelamat-ruang-terbatas-kemnaker|Petugas K3 Penyelamat Ruang Terbatas Kemnaker','authorized-gas-tester-bnsp|Authorized Gas Tester BNSP','operator-luar-ruang-terbatas|Operator Luar Ruang Terbatas','entrant-ruang-terbatas|Entrant Ruang Terbatas','petugas-jaga-ruang-terbatas|Petugas Jaga Ruang Terbatas','standby-man-ruang-terbatas|Standby Man Ruang Terbatas','supervisor-ruang-terbatas|Supervisor Ruang Terbatas','rescuer-ruang-terbatas|Rescuer Ruang Terbatas','ahli-ruang-terbatas|Ahli Ruang Terbatas','ahli-muda-ruang-terbatas|Ahli Muda Ruang Terbatas','ahli-madya-ruang-terbatas|Ahli Madya Ruang Terbatas','ahli-utama-ruang-terbatas|Ahli Utama Ruang Terbatas','penanganan-bahaya-gas-h2s|Penanganan Bahaya Gas H2S'],
  lifting: ['teknisi-k3-pesawat-angkat-angkut|Teknisi K3 Pesawat Angkat dan Angkut','supervisor-k3-pesawat-angkat-angkut|Supervisor K3 Pesawat Angkat dan Angkut','ahli-k3-pesawat-angkat-angkut|Ahli K3 Pesawat Angkat dan Angkut','operator-pallet-stacker|Operator Pallet Stacker','operator-crane-jembatan|Operator Crane Jembatan','operator-overhead-crane|Operator Overhead Crane','operator-gantry-crane|Operator Gantry Crane','operator-mobile-crane|Operator Mobile Crane','operator-truck-crane|Operator Truck Crane','operator-tower-crane|Operator Tower Crane','operator-crane-putar-tetap|Operator Crane Putar Tetap','operator-pedestal-crane|Operator Pedestal Crane','operator-hoist|Operator Hoist','operator-manlift|Operator Manlift','operator-scissor-lift|Operator Scissor Lift','operator-personal-platform|Operator Personal Platform','operator-personal-basket|Operator Personal Basket','operator-backhoe-loader|Operator Backhoe Loader','operator-motor-grader|Operator Motor Grader','operator-road-roller|Operator Road Roller','operator-dump-truck|Operator Dump Truck','operator-konveyor|Operator Konveyor','operator-alat-pengatur-posisi-benda-kerja|Operator Alat Pengatur Posisi Benda Kerja'],
  electrical: ['teknisi-k3-listrik-kemnaker|Teknisi K3 Listrik Kemnaker','ahli-k3-listrik-kemnaker|Ahli K3 Listrik Kemnaker','teknisi-k3-ketenagalistrikan-bnsp|Teknisi K3 Ketenagalistrikan BNSP','ahli-k3-ketenagalistrikan-bnsp|Ahli K3 Ketenagalistrikan BNSP','operator-k3-listrik|Operator K3 Listrik','supervisor-teknik-listrik|Supervisor Teknik Listrik','keselamatan-listrik-untuk-pekerja-nonlistrik|Keselamatan Listrik untuk Pekerja Nonlistrik','lockout-tagout-listrik|Lockout Tagout Listrik','keselamatan-kerja-dekat-instalasi-bertegangan|Keselamatan Kerja Dekat Instalasi Bertegangan'],
  pressure: ['operator-pesawat-uap-kelas-1|Operator Pesawat Uap Kelas 1','operator-pesawat-uap-kelas-2|Operator Pesawat Uap Kelas 2','teknisi-pesawat-uap|Teknisi Pesawat Uap','operator-bejana-tekanan|Operator Bejana Tekanan','teknisi-bejana-tekanan|Teknisi Bejana Tekanan','operator-tangki-timbun|Operator Tangki Timbun','teknisi-tangki-timbun|Teknisi Tangki Timbun','operator-kompresor|Operator Kompresor','operator-refrigerasi|Operator Refrigerasi','teknisi-refrigerasi|Teknisi Refrigerasi','operator-pesawat-tenaga-produksi|Operator Pesawat Tenaga dan Produksi','teknisi-pesawat-tenaga-produksi|Teknisi Pesawat Tenaga dan Produksi'],
  fire: ['petugas-peran-kebakaran-kelas-d|Petugas Peran Kebakaran Kelas D','anggota-regu-kebakaran-kelas-c|Anggota Regu Kebakaran Kelas C','koordinator-kebakaran-kelas-b|Koordinator Kebakaran Kelas B','ahli-k3-kebakaran-kelas-a|Ahli K3 Kebakaran Kelas A','pengkaji-teknis-proteksi-kebakaran|Pengkaji Teknis Proteksi Kebakaran','fireman-tingkat-1|Fireman Tingkat 1','fireman-tingkat-2|Fireman Tingkat 2','fire-officer|Fire Officer','fire-engineer|Fire Engineer','operator-pemadam-kebakaran|Operator Pemadam Kebakaran','pengawas-pemadam-kebakaran|Pengawas Pemadam Kebakaran','manajer-keselamatan-kebakaran-bangunan-gedung|Manajer Keselamatan Kebakaran Bangunan Gedung','fire-warden|Fire Warden','tim-tanggap-darurat|Tim Tanggap Darurat'],
  health: ['petugas-p3k-kemnaker|Petugas P3K Kemnaker','petugas-p3k-bnsp|Petugas P3K BNSP','dokter-perusahaan|Dokter Perusahaan','paramedis-perusahaan|Paramedis Perusahaan','paramedis-k3-muda|Paramedis K3 Muda','paramedis-k3-madya|Paramedis K3 Madya','paramedis-k3-utama|Paramedis K3 Utama','hiperkes-untuk-dokter|Hiperkes untuk Dokter','hiperkes-untuk-paramedis|Hiperkes untuk Paramedis','pengkaji-risiko-kesehatan-kerja|Pengkaji Risiko Kesehatan Kerja','pencegahan-hiv-aids-di-tempat-kerja|Pencegahan HIV/AIDS di Tempat Kerja','penanggulangan-tuberkulosis-di-tempat-kerja|Penanggulangan Tuberkulosis di Tempat Kerja','ergonomi-tempat-kerja|Ergonomi Tempat Kerja'],
  hygiene: ['higiene-industri-muda|Higiene Industri Muda','higiene-industri-madya|Higiene Industri Madya','higiene-industri-utama|Higiene Industri Utama','ahli-higiene-industri-muda|Ahli Higiene Industri Muda','ahli-higiene-industri-madya|Ahli Higiene Industri Madya','ahli-higiene-industri-utama|Ahli Higiene Industri Utama','pengukuran-kebisingan-tempat-kerja|Pengukuran Kebisingan Tempat Kerja','pengukuran-getaran-tempat-kerja|Pengukuran Getaran Tempat Kerja','pengukuran-iklim-kerja|Pengukuran Iklim Kerja','pengukuran-pencahayaan-tempat-kerja|Pengukuran Pencahayaan Tempat Kerja','pengukuran-kualitas-udara-tempat-kerja|Pengukuran Kualitas Udara Tempat Kerja','sampling-bahan-kimia-di-tempat-kerja|Sampling Bahan Kimia di Tempat Kerja','pengelolaan-sds-dan-ghs|Pengelolaan SDS dan GHS','penanganan-tumpahan-bahan-kimia|Penanganan Tumpahan Bahan Kimia','penyimpanan-bahan-berbahaya|Penyimpanan Bahan Berbahaya','penggunaan-respirator|Penggunaan Respirator'],
  construction: ['petugas-k3-konstruksi|Petugas K3 Konstruksi','petugas-keselamatan-konstruksi|Petugas Keselamatan Konstruksi','supervisor-k3-konstruksi-level-5|Supervisor K3 Konstruksi Level 5','supervisor-k3-konstruksi-level-6|Supervisor K3 Konstruksi Level 6','ahli-muda-k3-konstruksi|Ahli Muda K3 Konstruksi','ahli-madya-k3-konstruksi|Ahli Madya K3 Konstruksi','ahli-utama-k3-konstruksi|Ahli Utama K3 Konstruksi','ahli-muda-keselamatan-konstruksi|Ahli Muda Keselamatan Konstruksi','ahli-madya-keselamatan-konstruksi|Ahli Madya Keselamatan Konstruksi','ahli-utama-keselamatan-konstruksi|Ahli Utama Keselamatan Konstruksi','ahli-muda-k3-konstruksi-fresh-graduate|Ahli Muda K3 Konstruksi Fresh Graduate','operator-scaffolding|Operator Scaffolding','teknisi-scaffolding|Teknisi Scaffolding','supervisor-scaffolding|Supervisor Scaffolding','inspektor-scaffolding|Inspektor Scaffolding'],
  process: ['safetyman-migas|Safetyman Migas','operator-k3-migas|Operator K3 Migas','pengawas-k3-migas|Pengawas K3 Migas','pengawas-utama-k3-migas|Pengawas Utama K3 Migas','ahli-k3-migas|Ahli K3 Migas','authorized-work-permit-migas|Authorized Work Permit Migas','kepala-teknik-migas|Kepala Teknik Migas','wakil-kepala-teknik-migas|Wakil Kepala Teknik Migas','keselamatan-spbu|Keselamatan SPBU','hazop|HAZOP','hazid|HAZID','lopa|LOPA','process-safety-management|Process Safety Management'],
  facilities: ['petugas-k3-fasilitas-kesehatan|Petugas K3 Fasilitas Kesehatan','pengawas-k3-rumah-sakit-dan-fasyankes|Pengawas K3 Rumah Sakit dan Fasyankes','petugas-k3-laboratorium|Petugas K3 Laboratorium','pengawas-k3-laboratorium|Pengawas K3 Laboratorium','biosafety-laboratorium|Biosafety Laboratorium'],
};

const profiles: Record<string, Omit<ProgramSeed, 'slug' | 'title'>> = {
  general: { scope:'fungsi umum, pengawasan, analisis, dan penerapan sistem K3', audience:['praktisi K3','supervisor','personel perusahaan'], outcomes:['menerapkan prinsip K3','menyusun bukti kerja','menjelaskan batas kewenangan'], syllabus:['dasar hukum','identifikasi bahaya','pengendalian risiko','komunikasi','pelaporan'], pathway:'mixed', sourceKeys:['uu1','pp50','bnsp'] },
  height: { scope:'kompetensi kerja aman pada ketinggian sesuai tingkat dan sistem akses', audience:['pekerja ketinggian','pengawas','tim penyelamat'], outcomes:['memeriksa sistem akses','menggunakan proteksi jatuh','menyiapkan rescue'], syllabus:['perencanaan','anchor','fall protection','alat akses','rescue'], pathway:'mixed', sourceKeys:['tinggi','bnsp'] },
  confined: { scope:'peran khusus, pengujian atmosfer, izin masuk, isolasi, komunikasi, dan penyelamatan ruang terbatas', audience:['entrant','attendant','gas tester','supervisor','rescuer'], outcomes:['menjalankan peran','memverifikasi atmosfer','merespons darurat'], syllabus:['klasifikasi ruang','permit','gas test','ventilasi','isolasi','rescue'], pathway:'mixed', sourceKeys:['ruang','bnsp'] },
  lifting: { scope:'operasi atau pengawasan pesawat angkat-angkut dan alat berat sesuai jenis alat', audience:['operator','rigger','teknisi','pengawas'], outcomes:['memeriksa alat','menilai kapasitas','mengendalikan zona operasi'], syllabus:['komponen','kapasitas','inspeksi','operasi','komunikasi','pelaporan'], pathway:'mixed', sourceKeys:['angkat','bnsp'] },
  electrical: { scope:'pengendalian bahaya listrik sesuai peran teknis dan tingkat kewenangan', audience:['teknisi','operator','pengawas','pekerja sekitar listrik'], outcomes:['mengidentifikasi bahaya listrik','menerapkan isolasi','memeriksa proteksi'], syllabus:['sengatan','arc flash','proteksi','LOTO','pengujian','darurat'], pathway:'mixed', sourceKeys:['listrik','bnsp'] },
  pressure: { scope:'operasi, pemeriksaan, dan pemeliharaan peralatan uap, tekanan, refrigerasi, dan produksi', audience:['operator','teknisi','pengawas utilitas'], outcomes:['memantau parameter','memeriksa pengaman','merespons kondisi abnormal'], syllabus:['komponen','batas operasi','perangkat pengaman','inspeksi','emergency'], pathway:'kemnaker', sourceKeys:['bejana','produksi'] },
  fire: { scope:'pencegahan dan penanggulangan kebakaran sesuai kelas atau fungsi personel', audience:['petugas kebakaran','fire team','pengawas fasilitas'], outcomes:['menilai kebakaran','mengoperasikan proteksi','mengoordinasikan evakuasi'], syllabus:['teori api','media pemadam','proteksi','organisasi','evakuasi','drill'], pathway:'mixed', sourceKeys:['uu1','bnsp'] },
  health: { scope:'kesehatan kerja, pertolongan pertama, dan pencegahan gangguan kesehatan pekerja', audience:['tenaga kesehatan','petugas P3K','praktisi K3','HR'], outcomes:['menilai kebutuhan kesehatan','memberikan respons awal','mengelola program'], syllabus:['kesehatan kerja','P3K','surveilans','rujukan','promosi kesehatan'], pathway:'mixed', sourceKeys:['p3k','lingkungan','bnsp'] },
  hygiene: { scope:'antisipasi, evaluasi, dan pengendalian pajanan lingkungan kerja', audience:['higienis industri','praktisi K3','petugas kesehatan'], outcomes:['menyusun strategi pengukuran','menafsirkan hasil','merekomendasikan kontrol'], syllabus:['fisika','kimia','biologi','ergonomi','sampling','NAB','pengendalian'], pathway:'mixed', sourceKeys:['lingkungan','kimia','bnsp'] },
  construction: { scope:'keselamatan konstruksi sesuai jenjang peran, pekerjaan, atau sistem akses', audience:['personel proyek','kontraktor','supervisor','praktisi K3'], outcomes:['mengendalikan pekerjaan kritis','memeriksa struktur sementara','mengoordinasikan kontraktor'], syllabus:['SMKK','HIRADC','temporary works','ketinggian','lifting','inspeksi'], pathway:'mixed', sourceKeys:['konstruksi','tinggi','bnsp'] },
  process: { scope:'pengendalian risiko migas dan keselamatan proses pada operasi berbahaya', audience:['operator proses','pengawas','engineer','tim HSE'], outcomes:['menganalisis bahaya proses','mengelola barrier','menerapkan izin kerja'], syllabus:['process hazard','PTW','isolasi','barrier','MOC','emergency'], pathway:'mixed', sourceKeys:['uu1','bnsp'] },
  facilities: { scope:'pengendalian risiko fasilitas kesehatan dan laboratorium', audience:['petugas fasilitas','tenaga kesehatan','laboran','pengawas'], outcomes:['memetakan risiko','mengendalikan pajanan','menyiapkan keadaan darurat'], syllabus:['biological safety','chemical safety','sharps','facility risk','waste','emergency'], pathway:'mixed', sourceKeys:['rumahsakit','lingkungan','bnsp'] },
};

const compactSeeds = Object.entries(compactPrograms).flatMap(([category, items]) => items.map((row) => {
  const [slug, title] = row.split('|');
  return { slug, title, ...profiles[category] } satisfies ProgramSeed;
}));

export const programSeeds: ProgramSeed[] = [...new Map([...detailedProgramSeeds, ...compactSeeds].map((seed) => [seed.slug, seed])).values()].slice(0, 180);
