export interface BatchItem {
  id: string;
  category: 'ak3u' | 'smk3' | 'darurat' | 'teknis';
  programName: string;
  level: string;
  batchCode: string;
  startDate: string;
  endDate: string;
  dateRange: string;
  duration: string;
  method: string;
  location: string;
  quotaStatus: 'urgent' | 'open' | 'early_bird';
  quotaLabel: string;
}

export const batchScheduleData: BatchItem[] = [
  // Ahli K3 Umum (Flagship)
  {
    id: 'ak3u-sep-2026',
    category: 'ak3u',
    programName: 'Pelatihan Ahli K3 Umum (Kemnaker RI)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 09',
    startDate: '2026-09-15',
    endDate: '2026-09-28',
    dateRange: '15 – 28 September 2026',
    duration: '120 JP (12 Hari)',
    method: 'Blended Learning (Zoom + PKL Lapangan)',
    location: 'Nasional (Online Zoom + PKL Industri)',
    quotaStatus: 'urgent',
    quotaLabel: 'Sisa 4 Kursi',
  },
  {
    id: 'ak3u-okt-2026',
    category: 'ak3u',
    programName: 'Pelatihan Ahli K3 Umum (Kemnaker RI)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 10',
    startDate: '2026-10-06',
    endDate: '2026-10-19',
    dateRange: '06 – 19 Oktober 2026',
    duration: '120 JP (12 Hari)',
    method: 'Blended Learning (Zoom + PKL Lapangan)',
    location: 'Nasional (Online Zoom + PKL Industri)',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },
  {
    id: 'ak3u-nov-2026',
    category: 'ak3u',
    programName: 'Pelatihan Ahli K3 Umum (Kemnaker RI)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 11',
    startDate: '2026-11-03',
    endDate: '2026-11-16',
    dateRange: '03 – 16 November 2026',
    duration: '120 JP (12 Hari)',
    method: 'Blended Learning (Zoom + PKL Lapangan)',
    location: 'Nasional (Online Zoom + PKL Industri)',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },
  {
    id: 'ak3u-des-2026',
    category: 'ak3u',
    programName: 'Pelatihan Ahli K3 Umum (Kemnaker RI)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 12',
    startDate: '2026-12-01',
    endDate: '2026-12-14',
    dateRange: '01 – 14 Desember 2026',
    duration: '120 JP (12 Hari)',
    method: 'Blended Learning (Zoom + PKL Lapangan)',
    location: 'Nasional (Online Zoom + PKL Industri)',
    quotaStatus: 'early_bird',
    quotaLabel: 'Early Bird Dibuka',
  },

  // Auditor SMK3 PP 50/2012
  {
    id: 'auditor-sep-2026',
    category: 'smk3',
    programName: 'Pelatihan Auditor SMK3 (PP 50/2012)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 05',
    startDate: '2026-09-22',
    endDate: '2026-09-25',
    dateRange: '22 – 25 September 2026',
    duration: '40 JP (4 Hari)',
    method: 'Virtual Classroom Interaktif',
    location: 'Nasional via Zoom',
    quotaStatus: 'urgent',
    quotaLabel: 'Sisa 3 Kursi',
  },
  {
    id: 'auditor-okt-2026',
    category: 'smk3',
    programName: 'Pelatihan Auditor SMK3 (PP 50/2012)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 06',
    startDate: '2026-10-20',
    endDate: '2026-10-23',
    dateRange: '20 – 23 Oktober 2026',
    duration: '40 JP (4 Hari)',
    method: 'Virtual Classroom Interaktif',
    location: 'Nasional via Zoom',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },
  {
    id: 'auditor-nov-2026',
    category: 'smk3',
    programName: 'Pelatihan Auditor SMK3 (PP 50/2012)',
    level: 'Sertifikasi Kemnaker RI',
    batchCode: 'Batch 07',
    startDate: '2026-11-17',
    endDate: '2026-11-20',
    dateRange: '17 – 20 November 2026',
    duration: '40 JP (4 Hari)',
    method: 'Virtual Classroom Interaktif',
    location: 'Nasional via Zoom',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },

  // Tanggap Darurat & Medis (P3K & Damkar)
  {
    id: 'p3k-sep-2026',
    category: 'darurat',
    programName: 'Petugas P3K di Tempat Kerja',
    level: 'Lisensi Kemnaker RI',
    batchCode: 'Batch 08',
    startDate: '2026-09-18',
    endDate: '2026-09-20',
    dateRange: '18 – 20 September 2026',
    duration: '30 JP (3 Hari)',
    method: 'Tatap Muka & Praktik Simulasi Medis',
    location: 'Training Center Yogyakarta / Sleman',
    quotaStatus: 'urgent',
    quotaLabel: 'Sisa 5 Kursi',
  },
  {
    id: 'damkar-sep-2026',
    category: 'darurat',
    programName: 'K3 Penanggulangan Kebakaran (Kelas D/C/B/A)',
    level: 'Kepmenaker 186/1999',
    batchCode: 'Batch 07',
    startDate: '2026-09-24',
    endDate: '2026-09-26',
    dateRange: '24 – 26 September 2026',
    duration: '3 Hari Kerja',
    method: 'Teori Interaktif + Fire Drill Simulasi',
    location: 'Fasilitas Drill Pemadaman Api',
    quotaStatus: 'urgent',
    quotaLabel: 'Sisa 2 Kursi',
  },
  {
    id: 'p3k-okt-2026',
    category: 'darurat',
    programName: 'Petugas P3K di Tempat Kerja',
    level: 'Lisensi Kemnaker RI',
    batchCode: 'Batch 09',
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    dateRange: '16 – 18 Oktober 2026',
    duration: '30 JP (3 Hari)',
    method: 'Tatap Muka & Praktik RJP Balut Bidai',
    location: 'Training Center Semarang',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },

  // Teknis Spesialis (Listrik & Ketinggian)
  {
    id: 'listrik-okt-2026',
    category: 'teknis',
    programName: 'Teknisi K3 Listrik Industri',
    level: 'Permenaker 12/2015',
    batchCode: 'Batch 04',
    startDate: '2026-10-12',
    endDate: '2026-10-17',
    dateRange: '12 – 17 Oktober 2026',
    duration: '6 Hari Kerja',
    method: 'Blended (Teori Online + Uji Grounding)',
    location: 'Lab Listrik & Online Zoom',
    quotaStatus: 'urgent',
    quotaLabel: 'Sisa 4 Kursi',
  },
  {
    id: 'ketinggian-okt-2026',
    category: 'teknis',
    programName: 'K3 Bekerja di Ketinggian (TKPK Tingkat 1)',
    level: 'Permenaker 09/2016',
    batchCode: 'Batch 06',
    startDate: '2026-10-28',
    endDate: '2026-10-30',
    dateRange: '28 – 30 Oktober 2026',
    duration: '3 Hari Kerja',
    method: 'Praktik Lapangan Rope Access & Tower',
    location: 'Training Ground Ketinggian Yogyakarta',
    quotaStatus: 'open',
    quotaLabel: 'Pendaftaran Dibuka',
  },
];
