import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Breadcrumbs } from '@/src/components/SiteChrome';
import { JsonLd } from '@/src/components/JsonLd';
import { findRecord, records, sectionLabels } from '@/src/lib/content';
import { site, waUrl } from '@/src/lib/site';

export const dynamicParams = false;
export function generateStaticParams(){ return records.map(({section,slug})=>({section,slug})); }
export async function generateMetadata({params}:{params:Promise<{section:string;slug:string}>}):Promise<Metadata>{ const {section,slug}=await params; const r=findRecord(section,slug); if(!r)return{}; return {title:r.title,description:r.description,alternates:{canonical:`/${section}/${slug}`},robots:r.indexable?{index:true,follow:true}:{index:false,follow:true},openGraph:{title:r.title,description:r.description,url:`/${section}/${slug}`,images:[]},twitter:{title:r.title,description:r.description,images:[]}}; }

export default async function DetailPage({params}:{params:Promise<{section:string;slug:string}>}){
 const {section,slug}=await params; const r=findRecord(section,slug); if(!r)notFound(); const related=r.related.map(path=>{const [s,l]=path.split('/');return findRecord(s,l)}).filter(Boolean);
 const schema = r.section==='regulasi-k3' ? {'@context':'https://schema.org','@type':'Legislation',name:r.title,url:`${site.url}/${r.section}/${r.slug}`,legislationLegalStatus:r.status,legislationDate:r.verifiedAt} : r.section==='kamus-k3' ? {'@context':'https://schema.org','@type':'DefinedTerm',name:r.title,description:r.answer,url:`${site.url}/${r.section}/${r.slug}`} : {'@context':'https://schema.org','@type':r.section==='pelatihan'?'Course':'Article',headline:r.title,description:r.description,url:`${site.url}/${r.section}/${r.slug}`,inLanguage:'id-ID'};
 return <main className="content-main"><JsonLd data={[schema,{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Beranda',item:site.url},{'@type':'ListItem',position:2,name:sectionLabels[r.section],item:`${site.url}/${r.section}`},{'@type':'ListItem',position:3,name:r.title,item:`${site.url}/${r.section}/${r.slug}`}]}]}/><Breadcrumbs items={[{label:'Beranda',href:'/'},{label:sectionLabels[r.section],href:`/${r.section}`},{label:r.title}]}/><article className="article-layout"><div><header className="article-hero"><p className="eyebrow">{sectionLabels[r.section].toUpperCase()}</p><h1>{r.title}</h1><p>{r.description}</p>{r.status&&<span className="status-pill">Status sumber: {r.status}</span>}</header><section className="answer-box"><small>JAWABAN RINGKAS</small><p>{r.answer}</p></section><section><h2>Apa yang perlu dipahami?</h2><div className="feature-list">{r.highlights.map((h,i)=><div key={h}><b>0{i+1}</b><h3>{h}</h3><p>Bagian ini membantu menilai kebutuhan, batas penerapan, bukti yang diperlukan, dan tindakan lanjutan secara sistematis.</p></div>)}</div></section>{r.sourceUrl&&<section className="source-box"><h2>Sumber dan verifikasi</h2><p>Status ditinjau pada {r.verifiedAt}. Selalu periksa naskah dan status terbaru pada penerbit resmi sebelum membuat keputusan kepatuhan.</p><a href={r.sourceUrl} rel="noopener noreferrer">Buka {r.sourceLabel} ↗</a></section>}<section><h2>Hal yang tidak boleh diasumsikan</h2><p>Informasi pada halaman ini tidak membuktikan bahwa Kreasi Ultimate Berjaya memiliki penunjukan PJK3, lisensi LSP, otorisasi BNSP/Kemnaker, jadwal, harga, atau instruktur tertentu. Data operasional ditampilkan hanya setelah tersedia dan dapat diverifikasi.</p></section></div><aside className="article-side"><div className="consult-card"><small>BUTUH ARAHAN?</small><h2>Konsultasikan kebutuhan Anda.</h2><p>Jelaskan tujuan individu atau perusahaan. Kami akan membantu memetakan informasi yang perlu dikonfirmasi.</p><a className="button" href={waUrl(`Halo, saya ingin berkonsultasi tentang ${r.title}.`)}>Konsultasi WhatsApp →</a></div>{related.length>0&&<div className="related-box"><h2>Terkait</h2>{related.map(x=><Link key={x!.slug} href={`/${x!.section}/${x!.slug}`}>{x!.title}<span>→</span></Link>)}</div>}</aside></article></main>;
}
