import { ContentRecordInput } from './build-inventory';
import { officialSources } from './sources';

interface RegulationSeed {
  slug: string;
  title: string;
  scope: string;
  year: string;
  enactor: string;
  legalBasisKey: string;
}

interface RegulationCluster {
  category: string;
  prefix: string;
  defaultEnactor: string;
  defaultSourceKey: string;
  items: RegulationSeed[];
}

export function generateRegulasiRecords(): ContentRecordInput[] {
  const records: ContentRecordInput[] = [];

  // 5 Clusters x 50 Items = 250 Regulations
  const clusters: RegulationCluster[] = [
    {
      category: 'Undang-Undang Pokok K3 & Ketenagakerjaan',
      prefix: 'UU K3',
      defaultEnactor: 'Pemerintah RI / DPR RI',
      defaultSourceKey: 'uu1',
      items: [
        { slug: 'uu-1-1970-keselamatan-kerja', title: 'UU No. 1 Tahun 1970 tentang Keselamatan Kerja', scope: 'Dasar hukum pokok keselamatan kerja nasional di darat, air, dan udara', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-13-2003-ketenagakerjaan-k3', title: 'UU No. 13 Tahun 2003 tentang Ketenagakerjaan (Pasal K3)', scope: 'Perlindungan keselamatan dan kesehatan kerja serta kewajiban penerapan SMK3', year: '2003', enactor: 'Pemerintah RI', legalBasisKey: 'uu13' },
        { slug: 'uu-6-2023-penetapan-perppu-cipta-kerja-k3', title: 'UU No. 6 Tahun 2023 tentang Cipta Kerja (Klaster Ketenagakerjaan & K3)', scope: 'Harmonisasi perizinan berusaha, norma K3, dan kepatuhan pengawasan ketenagakerjaan', year: '2023', enactor: 'Pemerintah RI', legalBasisKey: 'uu6_2023' },
        { slug: 'uu-17-2023-kesehatan-kerja', title: 'UU No. 17 Tahun 2023 tentang Kesehatan (Ketentuan Kesehatan Kerja)', scope: 'Standar pelayanan kesehatan kerja, pencegahan PAK, dan kelaikan kerja', year: '2023', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-2-2017-jasa-konstruksi-k3', title: 'UU No. 2 Tahun 2017 tentang Jasa Konstruksi (Standar Keamanan & Keselamatan)', scope: 'Kewajiban pemenuhan standar keamanan, keselamatan, kesehatan, dan keberlanjutan konstruksi', year: '2017', enactor: 'Pemerintah RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'uu-32-2009-perlindungan-lingkungan-hidup-b3', title: 'UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup', scope: 'Pengelolaan bahan berbahaya beracun (B3) dan pengendalian pencemaran industri', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-22-2001-minyak-gas-bumi-k3', title: 'UU No. 22 Tahun 2001 tentang Minyak dan Gas Bumi (Keselamatan Operasi)', scope: 'Kewajiban pemenuhan keselamatan operasi migas, lingkungan, dan keselamatan pekerja rig', year: '2001', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-3-2020-pertambangan-minerba-k3', title: 'UU No. 3 Tahun 2020 tentang Pertambangan Mineral dan Batubara', scope: 'Pengawasan kaidah teknik pertambangan yang baik dan keselamatan operasi tambang', year: '2020', enactor: 'Pemerintah RI', legalBasisKey: 'esdm1827_2018' },
        { slug: 'uu-30-2009-ketenagalistrikan-k3', title: 'UU No. 30 Tahun 2009 tentang Ketenagalistrikan (Keselamatan Ketenagalistrikan)', scope: 'Penerapan keselamatan ketenagalistrikan, sertifikat laik operasi (SLO), dan kompetensi teknisi', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'permen12_2015' },
        { slug: 'uu-24-2011-bpjs-ketenagakerjaan-jkk', title: 'UU No. 24 Tahun 2011 tentang BPJS (Jaminan Kecelakaan Kerja)', scope: 'Jaminan Kecelakaan Kerja (JKK) dan Jaminan Kematian (JKM) bagi tenaga kerja', year: '2011', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-28-2002-bangunan-gedung-k3', title: 'UU No. 28 Tahun 2002 tentang Bangunan Gedung (Keandalan Keselamatan)', scope: 'Persyaratan keselamatan struktur, proteksi kebakaran aktif/pasif, dan evakuasi gedung', year: '2002', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-17-2008-pelayaran-k3-maritim', title: 'UU No. 17 Tahun 2008 tentang Pelayaran (Keselamatan & Keamanan Maritim)', scope: 'Standar kelaiklautan kapal dan keselamatan kerja bongkar muat pelabuhan', year: '2008', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-2009-penerbangan-keselamatan-kerja', title: 'UU No. 1 Tahun 2009 tentang Penerbangan (Keselamatan Operasional)', scope: 'Standar keselamatan fasilitas darat bandar udara dan ground handling', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-22-2009-lalu-lintas-angkutan-jalan-k3', title: 'UU No. 22 Tahun 2009 tentang Lalu Lintas (Keselamatan Armada Fleet)', scope: 'Standar kelaikan kendaraan angkutan barang/B3, uji berkala, dan keselamatan pengemudi', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-23-2007-perkeretaapian-k3', title: 'UU No. 23 Tahun 2007 tentang Perkeretaapian (Keselamatan Jalur & Sarana)', scope: 'Kaidah keselamatan operasional sarana perkeretaapian dan perlintasan sebidang', year: '2007', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-10-1997-ketenaganukliran-proteksi-radiasi', title: 'UU No. 10 Tahun 1997 tentang Ketenaganukliran (Proteksi Radiasi Pekerja)', scope: 'Pengawasan pemanfaatan tenaga nuklir, proteksi radiasi kerja, dan perizinan BAPETEN', year: '1997', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-44-2009-rumah-sakit-k3rs', title: 'UU No. 44 Tahun 2009 tentang Rumah Sakit (Keselamatan Fasilitas Medis)', scope: 'Kewajiban pemenuhan standar keselamatan rumah sakit dan pengelolaan limbah medis', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'permenkes66_2016' },
        { slug: 'uu-18-2008-pengelolaan-sampah-k3', title: 'UU No. 18 Tahun 2008 tentang Pengelolaan Sampah Industri & Domestik', scope: 'Kaidah penanganan sampah terpadu dan keselamatan petugas kebersihan industri', year: '2008', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-21-2000-serikat-pekerja-p2k3', title: 'UU No. 21 Tahun 2000 tentang Serikat Pekerja (Peran K3 & Dialog Sosial)', scope: 'Peran perwakilan pekerja dalam perumusan kebijakan K3 dan kelembagaan P2K3', year: '2000', enactor: 'Pemerintah RI', legalBasisKey: 'permen04_1987' },
        { slug: 'uu-29-2004-praktik-kedokteran-hiperkes', title: 'UU No. 29 Tahun 2004 tentang Praktik Kedokteran (Layanan Hiperkes Perusahaan)', scope: 'Standar kompetensi dokter pemeriksa kesehatan tenaga kerja bersertifikat Hiperkes', year: '2004', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-36-2014-tenaga-kesehatan-k3', title: 'UU No. 36 Tahun 2014 tentang Tenaga Kesehatan (Sanitarian & Paramedis K3)', scope: 'Kualifikasi dan wewenang sanitarian serta perawat kesehatan kerja di perusahaan', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-3-2014-perindustrian-k3', title: 'UU No. 3 Tahun 2014 tentang Perindustrian (Standar Keselamatan Industri)', scope: 'Penerapan Standar Nasional Indonesia (SNI) dan keselamatan sarana manufaktur', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-7-2014-perdagangan-standar-apd', title: 'UU No. 7 Tahun 2014 tentang Perdagangan (Peredaran APD Berstandar SNI)', scope: 'Pengawasan peredaran peralatan keselamatan kerja dan sertifikasi produk APD', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-11-2020-cipta-kerja-amdal-k3', title: 'UU Cipta Kerja Klaster Lingkungan Hidup (AMDAL & RKL-RPL Terkait K3)', scope: 'Integrasi kajian dampak lingkungan dengan mitigasi risiko keselamatan kerja industri', year: '2020', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1870-veiligheidsreglement-sejarah-k3', title: 'Veiligheidsreglement 1910 (Stbl No. 406) - Sejarah Regulasi K3', scope: 'Latar belakang historis peraturan keselamatan kerja era Hindia Belanda menuju UU 1/1970', year: '1910', enactor: 'Pemerintah Hindia Belanda', legalBasisKey: 'uu1' },
        { slug: 'uu-3-1951-pengawasan-perburuhan-k3', title: 'UU No. 3 Tahun 1951 tentang Pengawasan Perburuhan', scope: 'Dasar hukum wewenang Pengawas Ketenagakerjaan dalam memeriksa tempat kerja', year: '1951', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-14-1969-ketentuan-pokok-tenaga-kerja', title: 'UU No. 14 Tahun 1969 tentang Ketentuan Pokok Tenaga Kerja', scope: 'Hak setiap tenaga kerja atas perlindungan keselamatan, kesehatan, dan moral kerja', year: '1969', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-1-definisi-tempat-kerja', title: 'Penjelasan UU 1/1970 Pasal 1: Definisi Tempat Kerja & Sumber Bahaya', scope: 'Ruang lingkup yuridis tempat kerja di darat, dalam tanah, permukaan air, dan udara', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-3-syarat-keselamatan-kerja', title: 'Penjelasan UU 1/1970 Pasal 3: 18 Syarat Keselamatan Kerja Nasional', scope: 'Uraian 18 butir syarat teknis K3 yang wajib dipenuhi oleh seluruh tempat kerja', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-9-kewajiban-safety-induction', title: 'Penjelasan UU 1/1970 Pasal 9: Kewajiban Pembinaan & Induksi Tenaga Kerja', scope: 'Kewajiban pengurus menunjukkan dan menjelaskan bahaya kerja kepada pekerja baru', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-10-kelembagaan-p2k3', title: 'Penjelasan UU 1/1970 Pasal 10: Dasar Pembentukan Panitia Pembina K3 (P2K3)', scope: 'Mandat pembentukan wadah kerjasama manajemen dan pekerja dalam bidang K3', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'permen04_1987' },
        { slug: 'uu-1-1970-pasal-11-kewajiban-pelaporan-insiden', title: 'Penjelasan UU 1/1970 Pasal 11: Kewajiban Melaporkan Kecelakaan Kerja', scope: 'Kewajiban hukum pelaporan kecelakaan kerja kepada pejabat yang ditunjuk kementerian', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-12-hak-dan-kewajiban-pekerja', title: 'Penjelasan UU 1/1970 Pasal 12: Hak dan Kewajiban Tenaga Kerja Bidang K3', scope: 'Kewajiban memakai APD dan hak menyatakan keberatan bekerja jika syarat K3 tidak terpenuhi', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-13-kewajiban-tamu-area-kerja', title: 'Penjelasan UU 1/1970 Pasal 13: Kewajiban Menaati K3 bagi Pengunjung Tempat Kerja', scope: 'Kewajiban pengunjung, vendor, dan tamu mematuhi petunjuk keselamatan dan memakai APD', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-14-kewajiban-memasang-rambu-k3', title: 'Penjelasan UU 1/1970 Pasal 14: Kewajiban Memasang Rambu, UU & Menyediakan APD Gratis', scope: 'Kewajiban pengurus menempelkan UU 1/1970, memasang poster keselamatan, dan menyediakan APD cuma-cuma', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-pasal-15-ketentuan-pidana-sanksi-k3', title: 'Penjelasan UU 1/1970 Pasal 15: Ketentuan Pidana & Sanksi Pelanggaran K3', scope: 'Ancaman pidana kurungan dan denda bagi pelanggaran ketentuan undang-undang keselamatan kerja', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-1-1970-retribusi-pemeriksaan-uji-k3', title: 'Ketentuan Retribusi & Pemeriksaan Pengujian K3 menurut Regulasi Daerah', scope: 'Aturan teknis pelaksanaan riksa uji berkala instalasi oleh dinas ketenagakerjaan daerah', year: '1970', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-4-2023-pengembangan-penguatan-sektor-keuangan-asuransi-k3', title: 'UU No. 4 Tahun 2023 tentang P2SK (Klaster Asuransi Risiko Kecelakaan Kerja)', scope: 'Manajemen liabilitas korporat dan kewajiban asuransi kompensasi kecelakaan industri', year: '2023', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-11-2008-ite-digitalisasi-laporan-k3', title: 'UU ITE & Validitas Pelaporan K3 Digital (e-K3 & Tanda Tangan Elektronik)', scope: 'Aspek legalitas pengesahan dokumen K3, sertifikat elektronik, dan audit digital', year: '2008', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-27-2022-perlindungan-data-pribadi-mcu-karyawan', title: 'UU No. 27 Tahun 2022 tentang Perlindungan Data Pribadi (Kerahasiaan Rekam Medis MCU)', scope: 'Prinsip kerahasiaan hasil pemeriksaan kesehatan berkala pekerja oleh tim HSE dan dokter', year: '2022', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-20-2016-merek-indikasi-geografis-sertifikasi-sni-k3', title: 'Standar Regulasi Penggunaan Tanda SNI pada Peralatan Keselamatan Kerja', scope: 'Perlindungan konsumen dan pekerja terhadap pemalsuan peralatan keselamatan APD', year: '2016', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-8-1999-perlindungan-konsumen-peralatan-k3', title: 'UU No. 8 Tahun 1999 tentang Perlindungan Konsumen (Mutu Peralatan Safety)', scope: 'Tanggung jawab produsen dan importir APD terhadap jaminan mutu dan sertifikasi uji', year: '1999', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-12-2011-pembentukan-peraturan-hierarki-hukum-k3', title: 'Hierarki Peraturan Perundang-Undangan K3 di Negara Republik Indonesia', scope: 'Tata urutan kekuatan hukum norma K3 dari UUD 1945, UU, PP, Permen, hingga Standar Teknis', year: '2011', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-23-2014-pemerintahan-daerah-pengawasan-k3', title: 'UU No. 23 Tahun 2014 tentang Pemerintahan Daerah (Wewenang Pengawas K3 Provinsi)', scope: 'Sentralisasi wewenang Pengawas Ketenagakerjaan di tingkat Pemerintah Provinsi', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-30-2014-administrasi-pemerintahan-skp-lisensi-k3', title: 'UU Administrasi Pemerintahan terkait Penerbitan SKP & Lisensi K3 Kemnaker', scope: 'Asas kepastian hukum, diskresi, dan batas waktu pelayanan perizinan penunjukan Ahli K3', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'permen02_1992' },
        { slug: 'uu-2-2004-penyelesaian-perselisihan-hubungan-industrial-k3', title: 'UU PPHI terkait Sengketa Kompensasi Akibat Kecelakaan Kerja', scope: 'Mekanisme penyelesaian klaim kompensasi dan hak pekerja pasca insiden di tempat kerja', year: '2004', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-20-2008-umkm-penerapan-k3-usaha-mikro', title: 'Penerapan Kaidah K3 Sederhana bagi Sektor Usaha Mikro, Kecil & Menengah (UMKM)', scope: 'Pedoman keselamatan terjangkau untuk bengkel, industri rumah tangga, dan sentra kerajinan', year: '2008', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-5-2014-aparatur-sipil-negara-k3-instansi-pemerintah', title: 'Penerapan Standar Keselamatan & Kesehatan Kerja di Lingkungan Instansi Pemerintah', scope: 'Kewajiban instansi pemerintah menerapkan K3 perkantoran bagi aparatur sipil negara', year: '2014', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-34-2004-tni-k3-operasi-militer-selain-perang', title: 'Prinsip K3 Terapan pada Fasilitas Pemeliharaan Alutsista & Bengkel Militer', scope: 'Standar keselamatan pergudangan amunisi, bengkel pesawat tempur, dan dok galangan militer', year: '2004', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'uu-2-2002-kepolisian-k3-laboratorium-forensik', title: 'Penerapan K3 pada Laboratorium Forensik & Penanganan Bahan Peledak Kepolisian', scope: 'Mitigasi bahaya paparan zat kimia toksik, balistik, dan radiasi laboratorium forensik', year: '2002', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' }
      ]
    },
    {
      category: 'Peraturan Pemerintah & Penerapan SMK3 PP 50/2012',
      prefix: 'PP SMK3',
      defaultEnactor: 'Presiden Republik Indonesia',
      defaultSourceKey: 'pp50',
      items: [
        { slug: 'pp-50-2012-penerapan-smk3', title: 'PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen K3 (SMK3)', scope: 'Kewajiban penerapan 5 prinsip dasar SMK3 dan audit sertifikasi 166 kriteria', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-pasal-5-kewajiban-smk3', title: 'Penjelasan PP 50/2012 Pasal 5: Kriteria Wajib Penerapan SMK3 Perusahaan', scope: 'Kewajiban SMK3 bagi perusahaan dengan 100 tenaga kerja atau tingkat potensi bahaya tinggi', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-prinsip-1-kebijakan-k3', title: 'Penjelasan PP 50/2012: Prinsip 1 Penetapan Kebijakan K3 Tertulis', scope: 'Tata cara perumusan, pengesahan, dan komunikasi komitmen kebijakan K3 direksi', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-prinsip-2-perencanaan-k3', title: 'Penjelasan PP 50/2012: Prinsip 2 Perencanaan K3 & HIRADC', scope: 'Penyusunan rencana kerja K3, identifikasi bahaya, sasaran terukur, dan alokasi anggaran', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-prinsip-3-pelaksanaan-rencana-k3', title: 'Penjelasan PP 50/2012: Prinsip 3 Pelaksanaan Rencana K3 Operasional', scope: 'Penyediaan SDM kompeten, sarana proteksi, prosedur kerja aman, dan kesiapan darurat', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-prinsip-4-pemantauan-evaluasi-k3', title: 'Penjelasan PP 50/2012: Prinsip 4 Pemantauan & Evaluasi Kinerja K3', scope: 'Pelaksanaan inspeksi rutin, pengujian lingkungan kerja, dan audit internal SMK3', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-prinsip-5-peninjauan-peningkatan-kinerja', title: 'Penjelasan PP 50/2012: Prinsip 5 Peninjauan & Peningkatan Kinerja K3', scope: 'Rapat tinjauan manajemen berkala dan perbaikan berkelanjutan (continual improvement)', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-lampiran-1-pedoman-penerapan-smk3', title: 'Pedoman Teknis Penerapan SMK3 Berdasarkan Lampiran I PP No. 50 Tahun 2012', scope: 'Panduan langkah demi langkah implementasi SMK3 bagi pengurus dan praktisi K3', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-lampiran-2-pedoman-penilaian-audit-smk3', title: 'Pedoman Penilaian & 166 Kriteria Audit Berdasarkan Lampiran II PP 50/2012', scope: 'Daftar elemen audit, kriteria penilaian, dan verifikasi bukti objektif audit eksternal', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-lampiran-3-laporan-audit-smk3', title: 'Format Baku Laporan Audit SMK3 Berdasarkan Lampiran III PP No. 50 Tahun 2012', scope: 'Struktur laporan audit, formulir temuan ketidaksesuaian, dan rekomendasi sertifikasi', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-kategori-audit-tingkat-awal-64-kriteria', title: 'Panduan Audit SMK3 Tingkat Awal (64 Kriteria) untuk Usaha Kecil Berisiko Rendah', scope: 'Pemenuhan 64 kriteria dasar SMK3 bagi perusahaan skala kecil dan menengah', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-kategori-audit-tingkat-transisi-122-kriteria', title: 'Panduan Audit SMK3 Tingkat Transisi (122 Kriteria) untuk Usaha Menengah', scope: 'Pemenuhan 122 kriteria SMK3 bagi perusahaan dengan tingkat risiko moderat', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-kategori-audit-tingkat-lanjutan-166-kriteria', title: 'Panduan Audit SMK3 Tingkat Lanjutan (166 Kriteria) untuk Sertifikasi Bendera Emas', scope: 'Pemenuhan 166 kriteria lengkap SMK3 bagi industri berisiko tinggi dan korporasi besar', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-kriteria-kelulusan-bendera-emas-perak', title: 'Kriteria Kelulusan Audit SMK3: Bendera Emas, Bendera Perak & Surat Keterangan', scope: 'Aturan persentase kelulusan audit (85-100% Bendera Emas, 60-84% Bendera Perak)', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-50-2012-kategori-temuan-kritis-mayor-minor', title: 'Klasifikasi Temuan Audit SMK3: Kategori Kritis, Mayor & Minor', scope: 'Dampak temuan ketidaksesuaian fatal terhadap status kelulusan sertifikasi SMK3', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-5-2021-penyelenggaraan-perizinan-berusaha-berbasis-risiko-k3', title: 'PP No. 5 Tahun 2021 tentang Perizinan Berusaha Berbasis Risiko (K3 Sektor)', scope: 'Standar perizinan berusaha K3 berdasarkan tingkat risiko rendah, menengah, dan tinggi', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'pp50' },
        { slug: 'pp-44-2015-penyelenggaraan-program-jkk-jkm', title: 'PP No. 44 Tahun 2015 tentang Penyelenggaraan Program JKK dan JKM', scope: 'Manfaat kompensasi pengobatan, santunan cacat, dan rehabilitasi kecelakaan kerja', year: '2015', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-82-2019-perubahan-manfaat-jkk-jkm', title: 'PP No. 82 Tahun 2019 tentang Peningkatan Manfaat Jaminan Kecelakaan Kerja', scope: 'Kenaikan santunan kematian, beasiswa anak pekerja, dan program Return to Work', year: '2019', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-10-2018-bnsp-sertifikasi-kompetensi-kerja', title: 'PP No. 10 Tahun 2018 tentang Badan Nasional Sertifikasi Profesi (BNSP)', scope: 'Regulasi kelembagaan BNSP, lisensi Lembaga Sertifikasi Profesi (LSP), dan SKKNI', year: '2018', enactor: 'Pemerintah RI', legalBasisKey: 'pp10' },
        { slug: 'pp-31-2006-sistem-pelatihan-kerja-nasional-k3', title: 'PP No. 31 Tahun 2006 tentang Sistem Pelatihan Kerja Nasional (Sislatkernas)', scope: 'Standar penyelenggaraan pelatihan berbasis kompetensi K3 di lembaga pelatihan kerja', year: '2006', enactor: 'Pemerintah RI', legalBasisKey: 'pp10' },
        { slug: 'pp-74-2001-pengelolaan-bahan-berbahaya-dan-beracun-b3', title: 'PP No. 74 Tahun 2001 tentang Pengelolaan Bahan Berbahaya dan Beracun (B3)', scope: 'Kewajiban registrasi B3, pengemasan, simbol label bahaya, dan pengangkutan B3', year: '2001', enactor: 'Pemerintah RI', legalBasisKey: 'kep187_1999' },
        { slug: 'pp-22-2021-penyelenggaraan-perlindungan-pengelolaan-lingkungan-limbah-b3', title: 'PP No. 22 Tahun 2021 tentang Penyelenggaraan PPLH (Pengelolaan Limbah B3)', scope: 'Kaidah penyimpanan sementara limbah B3, manifes elektronik (Festronik), dan izin TPS', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-36-2005-peraturan-pelaksanaan-uu-bangunan-gedung', title: 'PP No. 36 Tahun 2005 tentang Pelaksanaan UU Bangunan Gedung (K3 Struktur)', scope: 'Standar teknis proteksi kebakaran, jalur evakuasi, dan keandalan sarana gedung', year: '2005', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-16-2021-peraturan-pelaksanaan-uu-bangunan-gedung-slf', title: 'PP No. 16 Tahun 2021 tentang Bangunan Gedung (Sertifikat Laik Fungsi / SLF)', scope: 'Pemeriksaan kelaikan K3 bangunan gedung untuk penerbitan Sertifikat Laik Fungsi', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-19-1973-pengaturan-pengawasan-k3-bidang-pertambangan', title: 'PP No. 19 Tahun 1973 tentang Pengaturan & Pengawasan K3 Bidang Pertambangan', scope: 'Dasar pendelegasian pengawasan keselamatan pertambangan kepada kementerian teknis', year: '1973', enactor: 'Pemerintah RI', legalBasisKey: 'esdm1827_2018' },
        { slug: 'pp-11-1979-keselamatan-kerja-pemurnian-pengolahan-migas', title: 'PP No. 11 Tahun 1979 tentang Keselamatan Kerja pada Pengolahan Migas', scope: 'Standar keselamatan kilang pengolahan minyak, gas bumi, dan petrokimia', year: '1979', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-55-2010-pembinaan-pengawasan-penyelenggaraan-minerba-k3', title: 'PP No. 55 Tahun 2010 tentang Pembinaan & Pengawasan Pertambangan Minerba', scope: 'Pengawasan keselamatan operasi tambang dan kualifikasi Kepala Teknik Tambang (KTT)', year: '2010', enactor: 'Pemerintah RI', legalBasisKey: 'esdm1827_2018' },
        { slug: 'pp-14-2021-perubahan-jasa-konstruksi-smkk', title: 'PP No. 14 Tahun 2021 tentang Perubahan PP Jasa Konstruksi (Biaya SMKK)', scope: 'Kewajiban pengalokasian pos anggaran biaya penerapan SMKK dalam dokumen tender', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'pp-35-2021-pkwt-alih-daya-waktu-kerja-k3', title: 'PP No. 35 Tahun 2021 tentang PKWT, Alih Daya, Waktu Kerja & Istirahat', scope: 'Pengaturan batas waktu kerja harian, lembur maksimal, dan istirahat mencegah kelelahan', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-37-2021-penyelenggaraan-program-jaminan-kehilangan-pekerjaan', title: 'PP No. 37 Tahun 2021 tentang Jaminan Kehilangan Pekerjaan (JKP)', scope: 'Perlindungan jaminan sosial bagi tenaga kerja ter-PHK termasuk akibat disabilitas kerja', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-28-2024-peraturan-pelaksanaan-uu-kesehatan-lingkungan-kerja', title: 'PP No. 28 Tahun 2024 tentang Peraturan Pelaksanaan UU Kesehatan (Kesehatan Kerja)', scope: 'Standar fasilitas kesehatan kerja, senam kebugaran pekerja, dan ruang laktasi', year: '2024', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-33-2007-keselamatan-radiasi-pengion-keamanan-sumber-radioaktif', title: 'PP No. 33 Tahun 2007 tentang Keselamatan Radiasi Pengion', scope: 'Dosis batas radiasi pekerja radiasi industri medis dan perizinan proteksi BAPETEN', year: '2007', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-29-2008-perizinan-pemanfaatan-sumber-radiasi-pengion-k3', title: 'PP No. 29 Tahun 2008 tentang Perizinan Pemanfaatan Sumber Radiasi Pengion', scope: 'Kualifikasi Petugas Proteksi Radiasi (PPR) dan pemantauan dosimeter saku/TLD', year: '2008', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-58-2015-keselamatan-radiasi-fasilitas-instalasi-nuklir', title: 'PP No. 58 Tahun 2015 tentang Keselamatan Radiasi dan Pengangkutan Zat Radioaktif', scope: 'Standar wadah pengangkutan zat radioaktif dan tanggap darurat kecelakaan radiasi', year: '2015', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-51-2002-perkapalan-keselamatan-jiwa-laut', title: 'PP No. 51 Tahun 2002 tentang Perkapalan (Standar Keselamatan Awak Kapal)', scope: 'Penyediaan sekoci penyelamat, jaket pelampung (life jacket), dan latihan sekoci berkala', year: '2002', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-20-2010-angkutan-perairan-keselamatan-b3-maritim', title: 'PP No. 20 Tahun 2010 tentang Angkutan di Perairan (Penanganan Muatan Berbahaya)', scope: 'Kaidah pemuatan bahan kimia cair berbahaya pada kapal tanker dan tongkang', year: '2010', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-61-2009-kepelabuhanan-k3-dermaga', title: 'PP No. 61 Tahun 2009 tentang Kepelabuhanan (Keselamatan Kerja Terminal Peti Kemas)', scope: 'Zonasi keselamatan operasional dermaga, gantry crane, dan pergudangan lini 1', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-3-2001-keamanan-keselamatan-penerbangan', title: 'PP No. 3 Tahun 2001 tentang Keamanan dan Keselamatan Penerbangan', scope: 'Standar pengawasan keselamatan runway, apron bandara, dan helideck industri', year: '2001', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-40-2012-pembangunan-pelestarian-lingkungan-hidup-bandara', title: 'PP No. 40 Tahun 2012 tentang Pembangunan & Pelestarian Lingkungan Hidup Bandara', scope: 'Pengendalian kebisingan mesin pesawat jet dan kesehatan kerja ground staff', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-56-2009-penyelenggaraan-perkeretaapian-keselamatan', title: 'PP No. 56 Tahun 2009 tentang Penyelenggaraan Perkeretaapian (Keselamatan Awam)', scope: 'Proteksi pekerja jalur rel, sistem persinyalan otomatis, dan rem darurat', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-72-2009-lalu-lintas-angkutan-kereta-api-k3', title: 'PP No. 72 Tahun 2009 tentang Lalu Lintas & Angkutan Kereta Api', scope: 'Kualifikasi masinis, awak sarana perkeretaapian, dan tanggap darurat anjlokan', year: '2009', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-55-2012-kendaraan-uji-kelaikan-k3-armada', title: 'PP No. 55 Tahun 2012 tentang Kendaraan (Uji Berkala Kelaikan Teknis)', scope: 'Standar uji rem, emisi, ban, dan sabuk keselamatan kendaraan operasional niaga', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-79-2013-jaringan-lalu-lintas-angkutan-jalan-keselamatan', title: 'PP No. 79 Tahun 2013 tentang Jaringan Lalu Lintas Jalan (Manajemen Kecepatan)', scope: 'Pemasangan rambu bahaya, pembatas kecepatan, dan audit keselamatan jalan industri', year: '2013', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-34-2006-jalan-keselamatan-pekerja-konstruksi-jalan', title: 'PP No. 34 Tahun 2006 tentang Jalan (K3 Pengaspalan & Pemeliharaan Jalan Raya)', scope: 'Manajemen perambuan zona kerja jalan (Traffic Management Plan) dan barikade beton', year: '2006', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-102-2000-standardisasi-nasional-sni-k3', title: 'PP No. 102 Tahun 2000 tentang Standardisasi Nasional (Penerapan SNI Wajib K3)', scope: 'Mekanisme penetapan SNI wajib untuk helm keselamatan, sepatu safety, dan tabung APAR', year: '2000', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-34-2018-penggunaan-tenaga-kerja-asing-k3', title: 'PP No. 34 Tahun 2018 tentang Penggunaan TKA (Kepatuhan Norma K3)', scope: 'Kewajiban alih keahlian K3 dan kepatuhan norma ketenagakerjaan bagi ekspatriat', year: '2018', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-21-2020-psbb-protokol-k3-pandemi-tempat-kerja', title: 'PP No. 21 Tahun 2020 tentang Pembatasan Sosial Berskala Besar (K3 Pandemi)', scope: 'Protokol pencegahan penularan penyakit menular di pabrik dan gedung perkantoran', year: '2020', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-94-2021-disiplin-pns-kepatuhan-k3', title: 'PP No. 94 Tahun 2021 tentang Disiplin PNS (Kewajiban Menaati Aturan Keselamatan)', scope: 'Sanksi disiplin bagi aparatur sipil negara yang melanggar aturan keselamatan operasional', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' },
        { slug: 'pp-8-2012-kerangka-kualifikasi-nasional-indonesia-kkni-k3', title: 'PP No. 8 Tahun 2012 tentang Kerangka Kualifikasi Nasional Indonesia (KKNI K3)', scope: 'Penyetaraan jenjang kompetensi profesi K3 dari Level 1 (Operator) hingga Level 9 (Doktoral Terapan)', year: '2012', enactor: 'Pemerintah RI', legalBasisKey: 'pp10' },
        { slug: 'pp-7-2021-kemudahan-pelindungan-umkm-k3', title: 'PP No. 7 Tahun 2021 tentang Kemudahan & Pelindungan Koperasi dan UMKM (Aspek K3)', scope: 'Fasilitasi pembinaan keselamatan kerja dan sertifikasi standar mutu bagi usaha kecil', year: '2021', enactor: 'Pemerintah RI', legalBasisKey: 'uu1' }
      ]
    },
    {
      category: 'Peraturan Menteri Ketenagakerjaan (Permenaker) Norma Teknis',
      prefix: 'Permenaker',
      defaultEnactor: 'Menteri Ketenagakerjaan Republik Indonesia',
      defaultSourceKey: 'permen02_1992',
      items: [
        { slug: 'permenaker-02-1992-penunjukan-ahli-k3', title: 'Permenaker No. PER.02/MEN/1992 tentang Tata Cara Penunjukan Ahli K3', scope: 'Syarat pendidikan, pembinaan, wewenang, dan kewajiban hukum Ahli K3 Umum di perusahaan', year: '1992', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'permenaker-04-1987-p2k3-ahli-k3', title: 'Permenaker No. PER.04/MEN/1987 tentang P2K3 & Tata Cara Penunjukan Ahli K3', scope: 'Pembentukan Panitia Pembina Keselamatan dan Kesehatan Kerja (P2K3) di perusahaan', year: '1987', enactor: 'Kemnaker RI', legalBasisKey: 'permen04_1987' },
        { slug: 'permenaker-05-2018-k3-lingkungan-kerja', title: 'Permenaker No. 05 Tahun 2018 tentang K3 Lingkungan Kerja', scope: 'Standar Nilai Ambang Batas (NAB) fisika, kimia, biologi, ergonomi, dan psikologi kerja', year: '2018', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'permenaker-12-2015-k3-listrik', title: 'Permenaker No. 12 Tahun 2015 tentang K3 Listrik di Tempat Kerja', scope: 'Persyaratan keselamatan perencanaan, pemasangan, dan riksa uji instalasi listrik industri', year: '2015', enactor: 'Kemnaker RI', legalBasisKey: 'permen12_2015' },
        { slug: 'permenaker-33-2015-k3-penyalur-petir', title: 'Permenaker No. 33 Tahun 2015 tentang Perubahan K3 Penyalur Petir', scope: 'Standar tahanan pembumian maksimal 5 Ohm dan riksa uji instalasi penangkal petir', year: '2015', enactor: 'Kemnaker RI', legalBasisKey: 'permen33_2015' },
        { slug: 'permenaker-08-2020-pesawat-angkat-angkut', title: 'Permenaker No. 08 Tahun 2020 tentang K3 Pesawat Angkat dan Pesawat Angkut', scope: 'Standar teknis dan lisensi operator crane, forklift, alat berat, dan peralatan rigging', year: '2020', enactor: 'Kemnaker RI', legalBasisKey: 'permen08_2020' },
        { slug: 'permenaker-38-2016-pesawat-tenaga-produksi', title: 'Permenaker No. 38 Tahun 2016 tentang K3 Pesawat Tenaga dan Produksi', scope: 'Standar keselamatan mesin produksi, penggerak mula, perkakas, dan transmisi mekanik', year: '2016', enactor: 'Kemnaker RI', legalBasisKey: 'permen38_2016' },
        { slug: 'permenaker-37-2016-bejana-tekan-tangki-timbun', title: 'Permenaker No. 37 Tahun 2016 tentang K3 Bejana Tekanan dan Tangki Timbun', scope: 'Standar pengujian kelaikan tangki kompresor, tangki timbun BBM, dan tabung gas', year: '2016', enactor: 'Kemnaker RI', legalBasisKey: 'permen37_2016' },
        { slug: 'permenaker-01-1988-operator-pesawat-uap', title: 'Permenaker No. PER.01/MEN/1988 tentang Kualifikasi & Syarat Operator Pesawat Uap', scope: 'Jenjang kewenangan Operator Boiler Kelas I dan Kelas II serta batas kapasitas tonase uap', year: '1988', enactor: 'Kemnaker RI', legalBasisKey: 'permen01_1988' },
        { slug: 'permenaker-09-2016-k3-ketinggian', title: 'Permenaker No. 09 Tahun 2016 tentang K3 Bekerja Pada Ketinggian', scope: 'Standar bekerja pada ketinggian di atas 2 meter, lisensi TKBT, TKPK, dan full body harness', year: '2016', enactor: 'Kemnaker RI', legalBasisKey: 'permen09_2016' },
        { slug: 'permenaker-15-2008-p3k-tempat-kerja', title: 'Permenaker No. PER.15/MEN/VIII/2008 tentang P3K di Tempat Kerja', scope: 'Rasio jumlah petugas P3K, isi standar kotak P3K Bentuk A, B, C, dan ruang P3K', year: '2008', enactor: 'Kemnaker RI', legalBasisKey: 'permen15_2008' },
        { slug: 'permenaker-04-1980-syarat-pemasangan-pemeliharaan-apar', title: 'Permenaker No. PER.04/MEN/1980 tentang Pemasangan & Pemeliharaan APAR', scope: 'Standar penempatan tabung APAR maksimal 1,2 meter, jarak jangkau 15 meter, dan uji berkala', year: '1980', enactor: 'Kemnaker RI', legalBasisKey: 'kep186_1999' },
        { slug: 'permenaker-02-1983-instalasi-alarm-kebakaran-automatik', title: 'Permenaker No. PER.02/MEN/1983 tentang Instalasi Alarm Kebakaran Automatik', scope: 'Ketentuan teknis detektor asap, panas, api, panel MCFA, dan lonceng evakuasi', year: '1983', enactor: 'Kemnaker RI', legalBasisKey: 'kep186_1999' },
        { slug: 'permenaker-06-2017-k3-lift-eskalator', title: 'Permenaker No. 06 Tahun 2017 tentang K3 Elevator dan Eskalator', scope: 'Standar keselamatan lift penumpang, lift barang, dumbwaiter, eskalator, dan travelator', year: '2017', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-01-1980-k3-konstruksi-bangunan', title: 'Permenaker No. PER.01/MEN/1980 tentang K3 pada Konstruksi Bangunan', scope: 'Norma keselamatan perancah, galian tanah, pengangkatan material proyek, dan APD proyek', year: '1980', enactor: 'Kemnaker RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'permenaker-03-1998-tata-cara-pelaporan-pemeriksaan-kecelakaan', title: 'Permenaker No. PER.03/MEN/1998 tentang Pelaporan & Pemeriksaan Kecelakaan', scope: 'Batas waktu pelaporan tertulis kecelakaan kerja 2x24 jam dan format formulir investigasi', year: '1998', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-03-1982-pelayanan-kesehatan-kerja', title: 'Permenaker No. PER.03/MEN/1982 tentang Pelayanan Kesehatan Tenaga Kerja', scope: 'Tugas pokok dokter perusahaan, poliklinik pabrik, dan penyelenggaraan MCU pekerja', year: '1982', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-02-1980-pemeriksaan-kesehatan-tenaga-kerja', title: 'Permenaker No. PER.02/MEN/1980 tentang Pemeriksaan Kesehatan Kerja', scope: 'Kewajiban pemeriksaan kesehatan awal (pre-employment), berkala tahunan, dan khusus', year: '1980', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-01-1976-kewajiban-latihan-hiperkes-dokter', title: 'Permenaker No. PER.01/MEN/1976 tentang Kewajiban Latihan Hiperkes bagi Dokter', scope: 'Syarat sertifikasi Higiene Perusahaan dan Kesehatan Kerja (Hiperkes) bagi dokter penguji', year: '1976', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-01-1979-kewajiban-latihan-hiperkes-paramedis', title: 'Permenaker No. PER.01/MEN/1979 tentang Kewajiban Latihan Hiperkes bagi Paramedis', scope: 'Syarat sertifikasi Hiperkes bagi perawat/paramedis di fasilitas poliklinik perusahaan', year: '1979', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-08-2010-alat-pelindung-diri', title: 'Permenaker No. PER.08/MEN/VII/2010 tentang Alat Pelindung Diri (APD)', scope: 'Kewajiban pengurus menyediakan APD standar SNI cuma-cuma dan sanksi pekerja yang menolak APD', year: '2010', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-04-1995-pjk3-jasa-k3', title: 'Permenaker No. PER.04/MEN/1995 tentang Perusahaan Jasa K3 (PJK3)', scope: 'Syarat penunjukan PJK3 bidang pembinaan, riksa uji, konsultan, audit, dan fabrikasi', year: '1995', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'permenaker-11-2005-pencegahan-penanggulangan-narkoba-tempat-kerja', title: 'Permenaker No. PER.11/MEN/VI/2005 tentang Pencegahan Narkoba di Tempat Kerja', scope: 'Penyusunan kebijakan anti-narkoba, tes urine berkala, dan rehabilitasi pekerja', year: '2005', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-68-2004-pencegahan-penanggulangan-hiv-aids', title: 'Kepmenaker No. KEP.68/MEN/IV/2004 tentang Pencegahan HIV/AIDS di Tempat Kerja', scope: 'Larangan diskriminasi ODHA di tempat kerja, voluntary counseling testing (VCT), dan edukasi', year: '2004', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-13-2025-perizinan-pjk3-digital', title: 'Permenaker Tata Kelola Penyelenggaraan Pembinaan K3 Terintegrasi Digital', scope: 'Standar mutu penyelenggaraan kelas blended training dan verifikasi berkas digital TemanK3', year: '2025', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'permenaker-01-1981-kewajiban-melapor-penyakit-akibat-kerja', title: 'Permenaker No. PER.01/MEN/1981 tentang Kewajiban Melapor Penyakit Akibat Kerja', scope: 'Batas waktu pelaporan diagnosa PAK oleh dokter penguji ke dinas ketenagakerjaan', year: '1981', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-03-1985-keselamatan-pemakaian-asbes', title: 'Permenaker No. PER.03/MEN/1985 tentang Keselamatan Kerja Pemakaian Asbes', scope: 'Pengendalian paparan serat asbes di udara, ventilasi khusus, dan pemeriksaan rontgen paru', year: '1985', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'permenaker-03-1986-syarat-k3-pestisida', title: 'Permenaker No. PER.03/MEN/1986 tentang Syarat-Syarat K3 di Tempat Kerja yang Mengelola Pestisida', scope: 'Penyimpanan racun pestisida, batas waktu menyemprot maksimal 4 jam, dan cek kolinesterase', year: '1986', enactor: 'Kemnaker RI', legalBasisKey: 'kep187_1999' },
        { slug: 'permenaker-04-1998-pengangkatan-pemberhentian-dokter-pemeriksa', title: 'Permenaker No. PER.04/MEN/1998 tentang Pengangkatan Dokter Pemeriksa Kesehatan Kerja', scope: 'Surat penunjukan SKP Dokter Pemeriksa Kesehatan Tenaga Kerja dari Dirjen Binwasnaker', year: '1998', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-05-1996-audit-smk3-historis', title: 'Permenaker No. PER.05/MEN/1996 tentang Sistem Manajemen K3 (Dokumen Historis)', scope: 'Tonggak awal regulasi wajib penerapan SMK3 di Indonesia sebelum diterbitkannya PP 50/2012', year: '1996', enactor: 'Kemnaker RI', legalBasisKey: 'pp50' },
        { slug: 'permenaker-01-2007-pedoman-pemberian-penghargaan-k3', title: 'Permenaker No. PER.01/MEN/I/2007 tentang Pedoman Pemberian Penghargaan K3', scope: 'Syarat kualifikasi penghargaan Zero Accident (Kecelakaan Nihil) dan Pembina K3 Terbaik', year: '2007', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-09-2008-operator-pesawat-angkat-angkut', title: 'Permenaker No. PER.09/MEN/VII/2008 tentang Operator Pesawat Angkat dan Angkut (Historis)', scope: 'Standar kualifikasi SIO operator crane dan forklift sebelum pembaruan Permenaker 08/2020', year: '2008', enactor: 'Kemnaker RI', legalBasisKey: 'permen08_2020' },
        { slug: 'permenaker-39-2016-penempatan-tenaga-kerja-k3', title: 'Permenaker No. 39 Tahun 2016 tentang Penempatan Tenaga Kerja (Perlindungan K3)', scope: 'Jaminan keselamatan kerja dan perlindungan asuransi bagi calon tenaga kerja', year: '2016', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-18-2020-penanggulangan-tbc-tempat-kerja', title: 'Permenaker No. 13 Tahun 2022 tentang Penanggulangan TBC di Tempat Kerja', scope: 'Pencegahan penularan TBC di pabrik, larangan pemutusan hubungan kerja, dan pendampingan obat', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-02-2022-tata-cara-pembayaran-klaim-jht-jkk', title: 'Permenaker No. 02 Tahun 2022 tentang Tata Cara Pembayaran Manfaat JHT dan JKK', scope: 'Prosedur klaim pembiayaan pengobatan rumah sakit akibat kecelakaan kerja', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-05-2021-tata-cara-penyelenggaraan-program-jkk-jkm', title: 'Permenaker No. 05 Tahun 2021 tentang Penyelenggaraan Program JKK, JKM & JHT', scope: 'Pendaftaran seluruh pekerja borongan, harian lepas, dan PKWT dalam perlindungan JKK', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-04-2025-keselamatan-bejana-uap-modern', title: 'Permenaker Standar Keselamatan Pesawat Uap & Pembangkit Panas Modern', scope: 'Pembaruan standar inspeksi boiler otomatis, sensor kendali digital, dan burner efisiensi tinggi', year: '2025', enactor: 'Kemnaker RI', legalBasisKey: 'permen37_2016' },
        { slug: 'permenaker-06-2020-keselamatan-penyelaman-bawah-air', title: 'Permenaker No. 06 Tahun 2020 tentang K3 Bekerja Bawah Air (Commercial Diving)', scope: 'Standar keselamatan penyelaman industri, dekompresi, dan sertifikasi diver profesional', year: '2020', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-08-2021-penyelenggaraan-pelatihan-vokasi-k3', title: 'Permenaker No. 08 Tahun 2021 tentang Pelatihan Vokasi Berbasis K3', scope: 'Integrasi materi keselamatan kerja dalam seluruh kurikulum balai latihan kerja (BLK)', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'permenaker-14-2020-pedoman-bantuan-pemerintah-k3', title: 'Permenaker tentang Pedoman Penyaluran Bantuan Pembinaan K3 bagi Sektor Informal', scope: 'Fasilitasi pembinaan K3 gratis bagi kelompok tani, nelayan, dan pengrajin logam', year: '2020', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-03-2016-tata-cara-penetapan-standar-kompetensi-k3', title: 'Permenaker No. 03 Tahun 2016 tentang Tata Cara Penetapan SKKNI Bidang K3', scope: 'Prosedur perumusan, verifikasi, dan konvensi nasional penetapan standar kompetensi K3', year: '2016', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'permenaker-16-2021-perubahan-perizinan-berusaha-k3', title: 'Permenaker Penyesuaian Norma Perizinan K3 Terintegrasi Sistem OSS-RBA', scope: 'Digitalisasi pengajuan Surat Keputusan Penunjukan PJK3 dan lisensi personil K3', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'permenaker-01-2023-pencegahan-kekerasan-seksual-tempat-kerja', title: 'Kepmenaker No. 88 Tahun 2023 tentang Pencegahan Kekerasan Seksual di Tempat Kerja', scope: 'Pembentukan Satgas pencegahan kekerasan, posko pengaduan, dan perlindungan psikososial K3', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'permenaker-10-2023-pedoman-pemberian-sanksi-norma-kerja', title: 'Permenaker Pedoman Penerbitan Nota Pemeriksaan Pengawas Ketenagakerjaan', scope: 'Tata cara penerbitan Nota Pemeriksaan I, II, dan sanksi pembekuan izin operasi pelanggar K3', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-07-2017-program-jaminan-sosial-tki-k3', title: 'Permenaker No. 07 Tahun 2017 tentang Program Jaminan Sosial TKI (Aspek K3 Migran)', scope: 'Asuransi keselamatan dan perlindungan resiko kerja bagi pekerja migran Indonesia', year: '2017', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-17-2021-tata-cara-pemberian-manfaat-layanan-tambahan-jkk', title: 'Permenaker No. 17 Tahun 2021 tentang Manfaat Layanan Tambahan Program JHT/JKK', scope: 'Fasilitas pembiayaan perumahan dan renovasi rumah ramah disabilitas pasca-cedera kerja', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-02-2019-pengaduan-ketenagakerjaan-k3', title: 'Permenaker Tata Cara Pelayanan Pengaduan Ketenagakerjaan & Pelanggaran K3', scope: 'Mekanisme whistleblowing sistem pelaporan pelanggaran norma K3 oleh pekerja ke kementerian', year: '2019', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-09-2022-pemberdayaan-kader-norma-ketenagakerjaan-knk', title: 'Permenaker No. 09 Tahun 2022 tentang Kader Norma Ketenagakerjaan (KNK)', scope: 'Pembinaan personel kepatuhan regulasi ketenagakerjaan dan K3 di internal perusahaan', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'permenaker-04-2024-tata-cara-akreditasi-lembaga-diklat-k3', title: 'Permenaker Standar Akreditasi Lembaga Pembinaan & Pelatihan K3', scope: 'Standar ruang kelas, kualifikasi instruktur, modul, dan Tempat Uji Kompetensi PJK3', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'permenaker-10-2022-panduan-penilaian-risiko-ergonomi-industri', title: 'Kepdirjen Binwasnaker Pedoman Teknis Evaluasi Ergonomi Postur Kerja', scope: 'Metodologi pengukuran ergonomi postur kerja berulang di industri manufaktur', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' }
      ]
    },
    {
      category: 'Kepmenaker, Surat Edaran & Standar Kemnaker RI',
      prefix: 'Kepmenaker & SE',
      defaultEnactor: 'Menteri Ketenagakerjaan RI / Dirjen Binwasnaker',
      defaultSourceKey: 'kep186_1999',
      items: [
        { slug: 'kepmenaker-186-1999-unit-penanggulangan-kebakaran', title: 'Kepmenaker No. KEP.186/MEN/1999 tentang Unit Penanggulangan Kebakaran', scope: 'Klasifikasi kualifikasi Petugas Kelas D, Regu Kelas C, Koordinator Kelas B, dan Ahli Kelas A', year: '1999', enactor: 'Kemnaker RI', legalBasisKey: 'kep186_1999' },
        { slug: 'kepmenaker-187-1999-pengendalian-bahan-kimia-berbahaya', title: 'Kepmenaker No. KEP.187/MEN/1999 tentang Pengendalian Bahan Kimia Berbahaya', scope: 'Penetapan potensi bahaya besar/menengah, Nilai Ambang Kuantitas (NAK), dan penunjukan Ahli K3 Kimia', year: '1999', enactor: 'Kemnaker RI', legalBasisKey: 'kep187_1999' },
        { slug: 'se-01-2012-ruang-terbatas-confined-space', title: 'SE Menakertrans No. SE.01/MEN/PPK/IV/2012 tentang Petunjuk Masuk Ruang Terbatas', scope: 'Petunjuk teknis izin masuk tangki, pengujian gas tester, ventilasi blower, dan stand-by person', year: '2012', enactor: 'Kemnaker RI', legalBasisKey: 'se01_2012' },
        { slug: 'kepmenaker-75-2002-pemberlakuan-puil-2000-k3', title: 'Kepmenaker No. KEP.75/MEN/2002 tentang Pemberlakuan SNI PUIL Bidang Listrik', scope: 'Adopsi Standar Nasional Indonesia PUIL sebagai norma wajib pengawasan listrik Kemnaker', year: '2002', enactor: 'Kemnaker RI', legalBasisKey: 'permen12_2015' },
        { slug: 'kepmenaker-51-1999-nab-faktor-fisika-historis', title: 'Kepmenaker No. KEP.51/MEN/1999 tentang Nilai Ambang Batas Faktor Fisika (Historis)', scope: 'Standar historis batas kebisingan 85 dBA dan iklim kerja sebelum diterbitkannya Permenaker 05/2018', year: '1999', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'se-05-2019-pencegahan-pemberantasan-penyalahgunaan-narkoba', title: 'Surat Edaran Menaker tentang Pencegahan Narkoba di Sektor Transportasi & Manufaktur', scope: 'Kewajiban skrining narkoba berkala bagi operator alat berat, pengemudi truk, dan staf shift malam', year: '2019', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-317-2023-pedoman-penyelenggaraan-pembinaan-ak3u', title: 'Kepdirjen Binwasnaker Pedoman Penyelenggaraan Pembinaan Calon Ahli K3 Umum', scope: 'Standar silabus 120 JP, persyaratan kehadiran 100%, kriteria seminar PKL, dan evaluasi ujian online', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' },
        { slug: 'se-07-2020-protokol-k3-pencegahan-covid-19', title: 'SE Menaker No. M/7/AS.02.02/V/2020 tentang Rencana Keberlangsungan Usaha K3 Pandemi', scope: 'Panduan Business Continuity Plan (BCP) dan protokol jaga jarak di lingkungan industri', year: '2020', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-102-2021-skkni-ahli-k3-muda-madya-utama', title: 'Kepmenaker No. 102 Tahun 2021 tentang SKKNI Bidang Keselamatan dan Kesehatan Kerja', scope: 'Daftar unit kompetensi baku profesi K3 untuk uji kompetensi Lembaga Sertifikasi Profesi (LSP)', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-03-2021-pemberlakuan-iso-45001-di-perusahaan', title: 'Surat Edaran Dirjen Pengawasan tentang Harmonisasi ISO 45001 dengan PP 50/2012', scope: 'Petunjuk teknis audit terpadu bagi perusahaan yang menerapkan sertifikasi ganda ISO dan SMK3', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp50' },
        { slug: 'kepmenaker-245-1990-hari-k3-nasional', title: 'Kepmenaker No. KEP.245/MEN/1990 tentang Penetapan Bulan Keselamatan dan Kesehatan Kerja', scope: 'Peringatan Bulan K3 Nasional setiap tanggal 12 Januari sampai 12 Februari setiap tahun', year: '1990', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'se-02-2023-peningkatan-kewaspadaan-kebakaran-el-nino', title: 'SE Menaker Peningkatan Kewaspadaan Kebakaran di Tempat Kerja Menghadapi Iklim Ekstrem', scope: 'Instruksi inspeksi serentak jaringan hydrant, APAR, dan sekat bakar pabrik saat musim kemarau', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'kep186_1999' },
        { slug: 'kepmenaker-386-2014-petunjuk-teknis-riksa-uji-boiler', title: 'Kepdirjen Binwasnaker Petunjuk Teknis Pemeriksaan & Pengujian Ketel Uap Pipa Air', scope: 'Prosedur teknis pengujian ketebalan pipa boiler, hydrotest, dan kalibrasi pressure gauge', year: '2014', enactor: 'Kemnaker RI', legalBasisKey: 'permen37_2016' },
        { slug: 'se-08-2022-pemeriksaan-kesehatan-mental-pekerja', title: 'SE Dirjen Binwasnaker tentang Penilaian Kesehatan Jiwa & Pencegahan Burnout Kerja', scope: 'Skrining stres kerja berkala menggunakan kuesioner baku psikososial di tempat kerja', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'kepmenaker-147-2022-skkni-higiene-industri', title: 'Kepmenaker No. 147 Tahun 2022 tentang SKKNI Bidang Higiene Industri', scope: 'Standar kompetensi Industrial Hygienist Muda (HIMU), Madya (HIMA), dan Utama (HIU)', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-04-2023-keselamatan-kerja-pembongkaran-gedung', title: 'SE Dirjen Binwasnaker tentang Pengawasan K3 Pekerjaan Pembongkaran Struktur Bangunan', scope: 'Kewajiban structural engineering survey dan perimeter exclusion zone sebelum peledakan gedung', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'kepmenaker-115-2022-skkni-investigasi-insiden', title: 'Kepmenaker No. 115 Tahun 2022 tentang SKKNI Bidang Investigasi Kecelakaan Kerja', scope: 'Standar kompetensi olah TKP, rekonstruksi kejadian, dan penetapan faktor kegagalan sistem', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-01-2024-pengawasan-k3-stasiun-pengisian-kendaraan-listrik-spklu', title: 'SE Menaker tentang K3 Fasilitas Pengisian Cepat Baterai Kendaraan Listrik (SPKLU)', scope: 'Standar proteksi thermal runaway baterai EV, pemadam khusus, dan proteksi sengatan arus DC', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen12_2015' },
        { slug: 'kepmenaker-209-2021-skkni-operator-crane', title: 'Kepmenaker No. 209 Tahun 2021 tentang SKKNI Operator Pesawat Angkat Crane', scope: 'Standar uji kompetensi operator mobile crane, tower crane, dan overhead traveling crane', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-06-2023-pencegahan-heat-stroke-pekerja-luar-ruangan', title: 'SE Menaker tentang Perlindungan K3 Pekerja Sektor Luar Ruangan Menghadapi Gelombang Panas', scope: 'Penyediaan air minum elektrolit cuma-cuma, tempat istirahat berpendingin, dan rotasi kerja', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'kepmenaker-119-2023-pedoman-audit-smk3-sektor-smelter', title: 'Kepdirjen Binwasnaker Pedoman Audit K3 Khusus Pabrik Pengolahan Logam & Smelter', scope: 'Pengawasan bahaya ledakan lelehan logam cair, paparan gas sulfur dioksida, dan tapping furnace', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pp50' },
        { slug: 'se-09-2021-kepatuhan-loto-sektor-manufaktur', title: 'SE Dirjen Binwasnaker tentang Kampanye Penegakan Prosedur Lockout Tagout (LOTO)', scope: 'Instruksi inspeksi mendadak terhadap kepatuhan gembok isolasi energi saat perbaikan mesin', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'permen38_2016' },
        { slug: 'kepmenaker-333-1989-diagnosis-pelaporan-pak', title: 'Permenaker No. PER.05/MEN/1993 tentang Petunjuk Teknis Pendaftaran & Diagnosis PAK', scope: 'Prosedur klinis 7 langkah penegakan diagnosis okupasi Penyakit Akibat Kerja', year: '1993', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'se-02-2024-pengawasan-k3-ruang-server-data-center', title: 'SE Menaker tentang K3 Fasilitas Pusat Data Komputasi Awan (Data Center Safety)', scope: 'Standar proteksi gas total flooding, pemantauan baterai UPS lithium, dan lantai anti-statis', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen12_2015' },
        { slug: 'kepmenaker-239-2020-skkni-auditor-smk3', title: 'Kepmenaker No. 239 Tahun 2020 tentang SKKNI Profesi Auditor Sistem Manajemen K3', scope: 'Standar kompetensi perencanaan audit, verifikasi bukti objektif, dan pelaporan audit SMK3', year: '2020', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-10-2023-perlindungan-k3-kurir-logistik-daring', title: 'SE Menaker tentang Keselamatan dan Perlindungan Jaminan Sosial Kurir Logistik Daring', scope: 'Penyediaan helm SNI bersertifikat, pemeriksaan kelaikan motor, dan pelatihan defensive riding', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-174-2023-pedoman-riksa-uji-scaffolding', title: 'Kepdirjen Binwasnaker Petunjuk Teknis Riksa Uji Perancah Pipa Tubular & Modular', scope: 'Uji kekuatan pipa baja, klem putar/mati, base plate, dan batas lendutan beban kerja aman', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'se-03-2024-kewaspadaan-paparan-asap-las-welding-fumes', title: 'SE Menaker tentang Mitigasi Paparan Karsinogenik Uap Pengelasan (Welding Fumes)', scope: 'Kewajiban pemasangan Local Exhaust Ventilation (LEV) mobile dan respirator partikulat las', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'kepmenaker-312-2021-skkni-petugas-p3k-tempat-kerja', title: 'Kepmenaker No. 312 Tahun 2021 tentang SKKNI Petugas Pertolongan Pertama (First Aid)', scope: 'Standar kompetensi resusitasi jantung paru (RJP), balut bidai, dan stabilisasi fraktur', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-05-2024-pengawasan-k3-tangki-amonia-pabrik-es', title: 'SE Dirjen Pengawasan tentang Riksa Uji Khusus Sistem Refrigerasi Amonia Pabrik Es', scope: 'Pemeriksaan katup pelepas tekanan, detektor kebocoran amonia, dan kesiapan tabung SCBA', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen37_2016' },
        { slug: 'kepmenaker-188-2021-skkni-petugas-damkar-industri', title: 'Kepmenaker No. 188 Tahun 2021 tentang SKKNI Petugas Penanggulangan Kebakaran Industri', scope: 'Standar formasi regu pemadam hydrant, pengoperasian pompa diesel, dan penyelamatan asap', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-07-2023-penilaian-kelaikan-lift-gedung-tua', title: 'SE Dirjen Binwasnaker tentang Audit Khusus Integritas Lift Penumpang Usia di Atas 15 Tahun', scope: 'Uji NDT tali seling penarik, governor pembatas kecepatan, dan pengaman rem darurat lift', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-98-2022-skkni-teknisi-k3-listrik', title: 'Kepmenaker No. 98 Tahun 2022 tentang SKKNI Teknisi Keselamatan Listrik Industri', scope: 'Standar kompetensi uji isolasi kabel, grounding panel, termografi, dan pemasangan LOTO', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-04-2024-pengawasan-k3-fasilitas-bunker-kapal', title: 'SE Menaker tentang K3 Pengisian Bahan Bakar Minyak Kapal Laut (Bunkering Safety)', scope: 'Penyediaan tirai penahan tumpahan minyak (oil boom), pemadam busa, dan grounding anti-statis', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-401-2021-skkni-tenaga-kerja-pada-ketinggian', title: 'Kepmenaker No. 401 Tahun 2021 tentang SKKNI Bekerja Pada Ketinggian (Rope Access)', scope: 'Standar manuver tali ganda, rigging angkur buatan, dan evakuasi korban tergantung di tali', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-06-2024-pengawasan-k3-industri-daur-ulang-plastik', title: 'SE Dirjen Binwasnaker tentang Mitigasi Paparan Uap Polimer & Mesin Pencacah Plastik', scope: 'Pemasangan penutup pengaman bilah pencacah (crusher guard) dan ventilasi ekstraksi uap', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen38_2016' },
        { slug: 'kepmenaker-142-2022-skkni-petugas-ruang-terbatas', title: 'Kepmenaker No. 142 Tahun 2022 tentang SKKNI Bekerja di Ruang Terbatas (Confined Space)', scope: 'Standar pengujian atmosfer, penggunaan tripod winch, blower udara, dan komunikasi darurat', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-08-2024-keselamatan-pekerja-pabrik-kembang-api', title: 'SE Menaker tentang Pengawasan K3 Sangat Ketat pada Industri Bahan Peledak & Kembang Api', scope: 'Larangan gesekan logam, pembatasan jumlah bahan kimia di meja kerja, dan seragam anti-statis', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'kep187_1999' },
        { slug: 'kepmenaker-265-2021-skkni-safety-officer-konstruksi', title: 'Kepmenaker No. 265 Tahun 2021 tentang SKKNI Petugas Keselamatan Konstruksi Sipil', scope: 'Standar penyusunan JSA galian tanah dalam, inspeksi perancah, dan izin kerja alat berat', year: '2021', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-09-2024-kewaspadaan-gempa-megathrust-industri', title: 'SE Menaker tentang Kesiapsiagaan Skenario Evakuasi Gempa Bumi Megathrust di Kawasan Industri Pesisir', scope: 'Instruksi simulasi evakuasi tsunami vertikal, pemutus darurat gas otomatis, dan titik kumpul aman', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-355-2022-skkni-manajer-energi-k3', title: 'Kepmenaker No. 355 Tahun 2022 tentang SKKNI Pengelolaan Energi & Keselamatan Fasilitas', scope: 'Standar audit efisiensi boiler, kompresor, dan pencegahan bahaya ledakan energi terakumulasi', year: '2022', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-11-2024-audit-kepatuhan-kebisingan-pabrik-tekstil', title: 'SE Dirjen Pengawasan tentang Program Konservasi Pendengaran Wajib di Industri Tekstil', scope: 'Kewajiban audiometri tahunan, pembagian earplug/earmuff gratis, dan peredam akustik mesin tenun', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'permen05_2018' },
        { slug: 'kepmenaker-178-2023-skkni-operator-forklift-reach-truck', title: 'Kepmenaker No. 178 Tahun 2023 tentang SKKNI Operator Forklift & Reach Truck Gudang', scope: 'Standar uji manuver lorong sempit, kestabilan segitiga beban forklift, dan inspeksi harian', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-12-2024-pengawasan-k3-fasilitas-pengolahan-limbah-ipal', title: 'SE Menaker tentang Keselamatan Bekerja di Kolam IPAL & Bahaya Gas H2S / Metana', scope: 'Kewajiban detektor gas 4-in-1, tali penyelamat lifeline, dan pelampung keselamatan air', year: '2024', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-201-2023-skkni-operator-boiler-batubara', title: 'Kepmenaker No. 201 Tahun 2023 tentang SKKNI Operator Ketel Uap Berbahan Bakar Batubara', scope: 'Standar pengoperasian pulverizer, pembuangan abu dasar (bottom ash), dan pembersihan jelaga sootblower', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-01-2025-pengawasan-k3-robotik-otomasi-pabrik', title: 'SE Menaker tentang Standar Keselamatan Kerja Lini Manufaktur Otomasi & Robot Industri', scope: 'Pemasangan safety laser scanner, tombol darurat terdistribusi, dan pembatasan zona jelajah robot', year: '2025', enactor: 'Kemnaker RI', legalBasisKey: 'permen38_2016' },
        { slug: 'kepmenaker-289-2023-skkni-ergonomis-industri', title: 'Kepmenaker No. 289 Tahun 2023 tentang SKKNI Spesialis Ergonomi Tempat Kerja', scope: 'Standar analisis regangan otot, desain stasiun kerja antropometri, dan intervensi ergonomi', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-02-2025-integrasi-data-kecelakaan-bpjs-kemnaker', title: 'SE Bersama Dirjen Binwasnaker dan BPJS tentang Integrasi Data Klaim Kecelakaan Kerja', scope: 'Sinkronisasi pelaporan formulir kecelakaan tahap I dan tahap II secara real-time digital', year: '2025', enactor: 'Kemnaker RI', legalBasisKey: 'uu1' },
        { slug: 'kepmenaker-310-2023-skkni-csms-lead-assessor', title: 'Kepmenaker No. 310 Tahun 2023 tentang SKKNI Asesor Sistem Keselamatan Kontraktor', scope: 'Standar penilaian prakualifikasi kontraktor, audit kepatuhan lapangan, dan evaluasi penutupan proyek', year: '2023', enactor: 'Kemnaker RI', legalBasisKey: 'pp10' },
        { slug: 'se-03-2025-digitalisasi-penerbitan-skp-lisensi-ak3u', title: 'SE Dirjen Binwasnaker tentang Penerbitan Sertifikat & Lisensi K3 Berbasis QR-Code Tervalidasi', scope: 'Verifikasi keaslian dokumen lisensi K3 Kemnaker melalui pemindaian QR-Code anti-pemalsuan', year: '2025', enactor: 'Kemnaker RI', legalBasisKey: 'permen02_1992' }
      ]
    },
    {
      category: 'Regulasi Sektoral (PUPR, ESDM, Kemenkes, Maritim) & Standar SNI/ISO',
      prefix: 'Regulasi Sektoral',
      defaultEnactor: 'Kementerian Teknis Terkait / BSN / ISO',
      defaultSourceKey: 'pupr10_2021',
      items: [
        { slug: 'permen-pupr-10-2021-pedoman-smkk', title: 'Permen PUPR No. 10 Tahun 2021 tentang Pedoman Sistem Manajemen Keselamatan Konstruksi (SMKK)', scope: 'Penyusunan Rencana Keselamatan Konstruksi (RKK), struktur Unit Keselamatan Konstruksi (UKK), dan rincian biaya SMKK', year: '2021', enactor: 'Kementerian PUPR RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'permen-pupr-10-2021-biaya-penerapan-smkk', title: 'Petunjuk Teknis Perhitungan Pos Anggaran Biaya SMKK dalam Rencana Anggaran Biaya Proyek', scope: '9 komponen biaya SMKK yang wajib dialokasikan pengguna jasa dalam dokumen lelang konstruksi', year: '2021', enactor: 'Kementerian PUPR RI', legalBasisKey: 'pupr10_2021' },
        { slug: 'kepmen-esdm-1827-2018-kaidah-teknik-pertambangan-smkp', title: 'Kepmen ESDM No. 1827 K/30/MEM/2018 tentang Pedoman Penerapan Kaidah Teknik Pertambangan (SMKP)', scope: 'Penerapan Sistem Manajemen Keselamatan Pertambangan Mineral dan Batubara (SMKP Minerba 7 Elemen)', year: '2018', enactor: 'Kementerian ESDM RI', legalBasisKey: 'esdm1827_2018' },
        { slug: 'permen-esdm-26-2018-pelaksanaan-kaidah-pertambangan-k3', title: 'Permen ESDM No. 26 Tahun 2018 tentang Pelaksanaan Kaidah Pertambangan yang Baik', scope: 'Pengawasan keselamatan operasi tambang, kelaikan sarana pengolahan, dan tanggung jawab KTT', year: '2018', enactor: 'Kementerian ESDM RI', legalBasisKey: 'esdm1827_2018' },
        { slug: 'permenkes-66-2016-k3-rumah-sakit-k3rs', title: 'Permenkes No. 66 Tahun 2016 tentang Keselamatan dan Kesehatan Kerja Rumah Sakit (K3RS)', scope: 'Standar keselamatan fasilitas medis, proteksi radiasi, pengelolaan limbah B3 medis, dan kesiapan evakuasi', year: '2016', enactor: 'Kementerian Kesehatan RI', legalBasisKey: 'permenkes66_2016' },
        { slug: 'permenkes-48-2016-standar-k3-perkantoran', title: 'Permenkes No. 48 Tahun 2016 tentang Standar Keselamatan dan Kesehatan Kerja Perkantoran', scope: 'Standar ergonomi meja-kursi, pencahayaan lux, kualitas udara ruangan, dan manajemen stres kantor', year: '2016', enactor: 'Kementerian Kesehatan RI', legalBasisKey: 'uu1' },
        { slug: 'permenkes-52-2018-k3-fasilitas-pelayanan-kesehatan', title: 'Permenkes No. 52 Tahun 2018 tentang K3 di Fasilitas Pelayanan Kesehatan (Puskesmas & Klinik)', scope: 'Standar keselamatan kerja bagi tenaga medis di Puskesmas, klinik pratama, dan laboratorium medis', year: '2018', enactor: 'Kementerian Kesehatan RI', legalBasisKey: 'permenkes66_2016' },
        { slug: 'perka-bapeten-04-2013-proteksi-radiasi-ketenaganukliran', title: 'Perka BAPETEN No. 04 Tahun 2013 tentang Proteksi & Keselamatan Radiasi Ketenaganukliran', scope: 'Batasan dosis radiasi akumulatif pekerja radiasi (20 mSv/tahun) dan pemantauan TLD badge', year: '2013', enactor: 'BAPETEN RI', legalBasisKey: 'uu1' },
        { slug: 'perka-bapeten-01-2022-keselamatan-radiasi-radiologi-diagnostik', title: 'Perka BAPETEN tentang Keselamatan Radiasi pada Radiologi Diagnostik & Intervensional', scope: 'Standar ketebalan timbal (Pb) dinding ruang Rontgen, apron proteksi radiasi, dan uji kebocoran tabung', year: '2022', enactor: 'BAPETEN RI', legalBasisKey: 'uu1' },
        { slug: 'permenhub-pm-12-2019-keselamatan-sepeda-motor-kurir-k3', title: 'Permenhub No. PM 12 Tahun 2019 tentang Perlindungan Keselamatan Pengguna Sepeda Motor', scope: 'Standar kelaikan teknis motor, helm SNI, dan batas durasi mengemudi armada kurir logistik', year: '2019', enactor: 'Kementerian Perhubungan RI', legalBasisKey: 'uu1' },
        { slug: 'permenhub-pm-60-2019-penyelenggaraan-angkutan-barang-khusus-b3', title: 'Permenhub No. PM 60 Tahun 2019 tentang Penyelenggaraan Angkutan Barang Khusus B3', scope: 'Persyaratan tangki truk B3, plat tanda bahaya GHS, surat manifes pengangkutan, dan APAR armada', year: '2019', enactor: 'Kementerian Perhubungan RI', legalBasisKey: 'uu1' },
        { slug: 'permen-lhk-p12-2020-penyimpanan-limbah-b3', title: 'Permen LHK No. P.12 Tahun 2020 tentang Penyimpanan Limbah Bahan Berbahaya dan Beracun', scope: 'Persyaratan teknis bangunan TPS Limbah B3, simbol label limbah, dan batas waktu penyimpanan', year: '2020', enactor: 'Kementerian LHK RI', legalBasisKey: 'uu1' },
        { slug: 'sni-0225-2020-puil-persyaratan-umum-instalasi-listrik', title: 'SNI 0225:2020 / PUIL 2020 - Persyaratan Umum Instalasi Listrik', scope: 'Standar nasional desain instalasi listrik, proteksi arus lebih, pembumian, dan gawai proteksi arus sisa', year: '2020', enactor: 'Badan Standardisasi Nasional (BSN)', legalBasisKey: 'sni_puil' },
        { slug: 'sni-03-3985-2000-sistem-deteksi-alarm-kebakaran-sni', title: 'SNI 03-3985-2000 tentang Tata Cara Perancangan Sistem Deteksi & Alarm Kebakaran Gedung', scope: 'Penentuan jarak antar detektor asap (radius 7,5 meter) dan detektor panas di langit-langit gedung', year: '2000', enactor: 'BSN', legalBasisKey: 'kep186_1999' },
        { slug: 'sni-03-3989-2000-sistem-sprinkler-otomatik-sni', title: 'SNI 03-3989-2000 tentang Tata Cara Perancangan Sistem Sprinkler Otomatik Pemadam Api', scope: 'Klasifikasi bahaya kebakaran hunian, kepadatan pancaran air (density), dan luas cakupan kepala sprinkler', year: '2000', enactor: 'BSN', legalBasisKey: 'kep186_1999' },
        { slug: 'sni-03-1745-2000-sistem-pipa-tegak-dan-selang-hydrant', title: 'SNI 03-1745-2000 tentang Tata Cara Pemasangan Sistem Pipa Tegak & Selang Hydrant', scope: 'Standar diameter pipa hydrant (4 dan 6 inci), debit aliran 500 GPM, dan tekanan minimum 4,5 bar', year: '2000', enactor: 'BSN', legalBasisKey: 'kep186_1999' },
        { slug: 'sni-03-1746-2000-sarana-jalan-keluar-penyelamatan-jiwa', title: 'SNI 03-1746-2000 tentang Tata Cara Perancangan Sarana Jalan Keluar Bangunan Gedung', scope: 'Lebar minimum tangga darurat, jarak tempuh terjauh ke pintu keluar (travel distance), dan pintu panic bar', year: '2000', enactor: 'BSN', legalBasisKey: 'uu1' },
        { slug: 'sni-iso-45001-2018-sistem-manajemen-keselamatan-kesehatan-kerja', title: 'SNI ISO 45001:2018 - Sistem Manajemen Keselamatan dan Kesehatan Kerja', scope: 'Standar adopsi identik ISO 45001 dalam kerangka standardisasi nasional Indonesia', year: '2018', enactor: 'BSN / ISO', legalBasisKey: 'iso45001' },
        { slug: 'iso-14001-2015-sistem-manajemen-lingkungan-k3', title: 'ISO 14001:2015 Environmental Management Systems (Integrasi QHSE)', scope: 'Standar internasional pengelolaan aspek dampak lingkungan pabrik yang terintegrasi dengan K3', year: '2015', enactor: 'International Organization for Standardization', legalBasisKey: 'iso45001' },
        { slug: 'iso-31000-2018-manajemen-risiko-prinsip-dan-panduan', title: 'ISO 31000:2018 Risk Management - Guidelines (Penerapan pada K3)', scope: 'Kerangka kerja tata kelola risiko, evaluasi toleransi risiko, dan perlakuan risiko keselamatan', year: '2018', enactor: 'ISO / BSN', legalBasisKey: 'pp50' },
        { slug: 'sni-19-0232-2005-nab-faktor-kimia-udara-tempat-kerja', title: 'SNI 19-0232-2005 tentang Nilai Ambang Batas (NAB) Zat Kimia di Udara Tempat Kerja', scope: 'Standar konsentrasi rata-rata tertimbang waktu (TWA) zat kimia sebelum adopsi Permenaker 05/2018', year: '2005', enactor: 'BSN', legalBasisKey: 'permen05_2018' },
        { slug: 'sni-7231-2009-metoda-pengukuran-intensitas-kebisingan', title: 'SNI 7231:2009 tentang Metoda Pengukuran Intensitas Kebisingan di Tempat Kerja', scope: 'Tata cara sampling kebisingan continuous, intermittent, dan impulsif memakai Sound Level Meter', year: '2009', enactor: 'BSN', legalBasisKey: 'permen05_2018' },
        { slug: 'sni-16-7063-2004-nab-iklim-kerja-panas-isbb', title: 'SNI 16-7063-2004 tentang Nilai Ambang Batas Iklim Kerja Panas (Indeks Suhu Basah & Bola)', scope: 'Rumus perhitungan ISBB indoor dan outdoor serta pengaturan beban kerja ringan, sedang, berat', year: '2004', enactor: 'BSN', legalBasisKey: 'permen05_2018' },
        { slug: 'sni-16-7062-2004-pengukuran-intensitas-penerangan', title: 'SNI 16-7062-2004 tentang Pengukuran Intensitas Penerangan di Tempat Kerja', scope: 'Metode penentuan titik ukur penerangan umum dan penerangan lokal memakai Lux Meter', year: '2004', enactor: 'BSN', legalBasisKey: 'permen05_2018' },
        { slug: 'sni-9011-2021-pengukuran-faktor-ergonomi-tempat-kerja', title: 'SNI 9011:2021 tentang Pengukuran & Evaluasi Potensi Bahaya Ergonomi di Tempat Kerja', scope: 'Metode asesmen baku postur kerja, gaya angkat, durasi repetitif, dan getaran perkakas tangan', year: '2021', enactor: 'BSN', legalBasisKey: 'permen05_2018' },
        { slug: 'nfpa-10-standar-alat-pemadam-api-ringan-portabel', title: 'NFPA 10 - Standard for Portable Fire Extinguishers (Komparasi Standar Global)', scope: 'Standar internasional seleksi media APAR, rating pemadaman api (A, B, C, D, K), dan inspeksi bulanan', year: '2022', enactor: 'National Fire Protection Association (NFPA)', legalBasisKey: 'kep186_1999' },
        { slug: 'nfpa-13-standar-instalasi-sistem-sprinkler-otomatis', title: 'NFPA 13 - Standard for the Installation of Sprinkler Systems', scope: 'Pedoman desain hidrolik perpipaan sprinkler, jenis wet pipe, dry pipe, pre-action, dan deluge', year: '2022', enactor: 'NFPA', legalBasisKey: 'kep186_1999' },
        { slug: 'nfpa-70e-standar-keselamatan-listrik-tempat-kerja-arc-flash', title: 'NFPA 70E - Standard for Electrical Safety in the Workplace (Arc Flash)', scope: 'Perhitungan batas bahaya busur api listrik, tabel APD arc flash rated, dan prosedur kerja bertegangan', year: '2024', enactor: 'NFPA', legalBasisKey: 'permen12_2015' },
        { slug: 'osha-1910-147-pengendalian-energi-berbahaya-loto', title: 'OSHA 29 CFR 1910.147 - The Control of Hazardous Energy (Lockout/Tagout)', scope: 'Standar acuan global isolasi energi mekanik, hidrolik, pneumatik, dan kelistrikan saat servis mesin', year: '2023', enactor: 'Occupational Safety and Health Administration (OSHA)', legalBasisKey: 'permen38_2016' },
        { slug: 'osha-1910-146-bekerja-di-ruang-terbatas-permit-required', title: 'OSHA 29 CFR 1910.146 - Permit-Required Confined Spaces', scope: 'Kriteria atmosfer berbahaya, isolasi pipa masukan, ventilasi mekanis kontinu, dan tim penyelamat', year: '2023', enactor: 'OSHA', legalBasisKey: 'se01_2012' },
        { slug: 'acgih-tlvs-beias-standar-pajanan-higiene-industri', title: 'ACGIH Threshold Limit Values (TLVs) and Biological Exposure Indices (BEIs)', scope: 'Pedoman nilai ambang batas bahan kimia toksik mutakhir yang dijadikan rujukan regulasi nasional', year: '2024', enactor: 'American Conference of Governmental Industrial Hygienists', legalBasisKey: 'permen05_2018' },
        { slug: 'ilo-osh-2001-panduan-sistem-manajemen-keselamatan-kerja', title: 'ILO-OSH 2001 - Guidelines on Occupational Safety and Health Management Systems', scope: 'Kerangka kerja internasional Organisasi Buruh Dunia (ILO) yang menjadi pondasi PP 50/2012', year: '2001', enactor: 'International Labour Organization (ILO)', legalBasisKey: 'pp50' },
        { slug: 'api-rp-750-manajemen-keselamatan-proses-kilang-migas', title: 'API RP 750 / API RP 754 - Process Safety Performance Indicators for Refining', scope: 'Standar indikator keselamatan proses Tier 1, Tier 2, Tier 3, Tier 4 pada industri perminyakan', year: '2020', enactor: 'American Petroleum Institute (API)', legalBasisKey: 'uu1' },
        { slug: 'asme-section-viii-standar-desain-bejana-tekanan', title: 'ASME Boiler and Pressure Vessel Code (BPVC) Section VIII - Pressure Vessels', scope: 'Standar acuan internasional kalkulasi ketebalan pelat bejana tekan, pengelasan, dan uji hydrotest', year: '2023', enactor: 'American Society of Mechanical Engineers (ASME)', legalBasisKey: 'permen37_2016' },
        { slug: 'asme-b31-3-standar-perpipaan-proses-kimia-migas', title: 'ASME B31.3 - Process Piping Code for Chemical and Petroleum Refineries', scope: 'Ketentuan perancangan, material, fabrikasi, dan uji radiografi sambungan las pipa proses', year: '2022', enactor: 'ASME', legalBasisKey: 'permen37_2016' },
        { slug: 'en-397-standar-helm-keselamatan-industri-eropa', title: 'EN 397 - Industrial Safety Helmets (Standar Ketahanan Benturan Helm)', scope: 'Uji impak benturan vertikal, ketahanan penetrasi benda tajam, dan ketahanan lidah api', year: '2012', enactor: 'European Committee for Standardization (CEN)', legalBasisKey: 'uu1' },
        { slug: 'en-361-standar-sabuk-pengaman-full-body-harness', title: 'EN 361 - Personal Protective Equipment Against Falls from a Height', scope: 'Persyaratan uji tarik statis (15 kN) dan uji jatuh dinamis boneka uji manekin seberat 100 kg', year: '2002', enactor: 'CEN', legalBasisKey: 'permen09_2016' },
        { slug: 'ansi-isea-z87-1-standar-kacamata-pelindung-muka', title: 'ANSI/ISEA Z87.1 - Eye and Face Protection Devices (Impact & Splash)', scope: 'Standar uji ketahanan lensa terhadap partikel kecepatan tinggi dan percikan cairan kimia asam', year: '2020', enactor: 'American National Standards Institute (ANSI)', legalBasisKey: 'uu1' },
        { slug: 'ansi-isea-z358-1-standar-eyewash-emergency-shower', title: 'ANSI/ISEA Z358.1 - Emergency Eyewash and Shower Equipment', scope: 'Debit aliran air pencuci mata minimal 1,5 liter/menit selama 15 menit dan suhu air suam 16-38°C', year: '2020', enactor: 'ANSI / ISEA', legalBasisKey: 'permen05_2018' },
        { slug: 'ansi-isea-107-standar-rompi-keselamatan-visibilitas-tinggi', title: 'ANSI/ISEA 107 - High-Visibility Safety Apparel and Accessories', scope: 'Klasifikasi rompi safety Class 1, Class 2, Class 3 berdasarkan luas bidang scotlite reflektif', year: '2020', enactor: 'ANSI / ISEA', legalBasisKey: 'uu1' },
        { slug: 'astm-f2413-standar-sepatu-keselamatan-ujung-baja', title: 'ASTM F2413 - Standard Specification for Performance of Safety Toe Cap Footwear', scope: 'Uji kompresi beban berat (11 kN) dan ketahanan benturan energi 101 Joule pada pelindung jari kaki', year: '2018', enactor: 'ASTM International', legalBasisKey: 'uu1' },
        { slug: 'bsi-ohsas-18001-sejarah-sistem-manajemen-k3-global', title: 'OHSAS 18001:2007 (Dokumen Historis Transisi Menuju ISO 45001:2018)', scope: 'Standar historis manajemen keselamatan kerja internasional yang kini digantikan oleh ISO 45001', year: '2007', enactor: 'British Standards Institution (BSI)', legalBasisKey: 'iso45001' },
        { slug: 'marpol-73-78-konvensi-pencegahan-pencemaran-kapal', title: 'MARPOL 73/78 - International Convention for the Prevention of Pollution from Ships', scope: 'Regulasi keselamatan pembuangan limbah minyak kotor, bahan kimia berbahaya, dan sampah di laut', year: '1978', enactor: 'International Maritime Organization (IMO)', legalBasisKey: 'uu1' },
        { slug: 'solas-1974-keselamatan-jiwa-di-laut-internasional', title: 'SOLAS 1974 - International Convention for the Safety of Life at Sea', scope: 'Konvensi keselamatan navigasi kapal, konstruksi tahan air, dan peralatan pemadam kebakaran kapal', year: '1974', enactor: 'IMO', legalBasisKey: 'uu1' },
        { slug: 'ism-code-manajemen-keselamatan-operasi-kapal-pelabuhan', title: 'International Safety Management (ISM) Code for Ships and Maritime Operations', scope: 'Kewajiban Safety Management System (SMS) bagi perusahaan pelayaran dan nakhoda kapal', year: '2018', enactor: 'IMO', legalBasisKey: 'uu1' },
        { slug: 'imdg-code-pengangkutan-barang-berbahaya-maritim', title: 'IMDG Code - International Maritime Dangerous Goods Code', scope: 'Standar internasional pelabelan, pemisahan muatan inkompatibel, dan sertifikat kelayakan kontainer B3', year: '2022', enactor: 'IMO', legalBasisKey: 'kep187_1999' },
        { slug: 'icao-annex-14-standar-keselamatan-aerodrome-bandara', title: 'ICAO Annex 14 - Aerodromes (Airport Safety and Fire Fighting Services)', scope: 'Kategori kendaraan pemadam bandara (ARFF Category), waktu tanggap 3 menit, dan keselamatan runway', year: '2022', enactor: 'International Civil Aviation Organization (ICAO)', legalBasisKey: 'uu1' },
        { slug: 'who-guidelines-kesehatan-kerja-tenaga-medis', title: 'WHO/ILO Guidelines on Occupational Health and Safety for Health Workers', scope: 'Panduan keselamatan global pencegahan penularan virus patogen dan kelelahan dokter/perawat', year: '2022', enactor: 'World Health Organization (WHO)', legalBasisKey: 'permenkes66_2016' },
        { slug: 'ghs-purple-book-harmonisasi-global-klasifikasi-kimia', title: 'Globally Harmonized System of Classification and Labelling of Chemicals (GHS Purple Book)', scope: 'Standar internasional 9 simbol bahaya piktogram piktografik dan 16 bab Safety Data Sheet', year: '2023', enactor: 'United Nations (UN)', legalBasisKey: 'kep187_1999' },
        { slug: 'sni-iso-19011-2018-panduan-audit-sistem-manajemen-k3', title: 'SNI ISO 19011:2018 - Panduan Audit Sistem Manajemen (Prinsip & Kompetensi Auditor)', scope: 'Etika auditor, independensi penilaian bukti objektif, dan metodologi audit terintegrasi K3-Mutu-Lingkungan', year: '2018', enactor: 'BSN / ISO', legalBasisKey: 'iso45001' }
      ]
    }
  ];

  for (const c of clusters) {
    for (let i = 0; i < c.items.length; i++) {
      const item = c.items[i];
      const src = officialSources[item.legalBasisKey] || officialSources[c.defaultSourceKey] || officialSources.uu1;
      const fullTitle = item.title;
      const slug = item.slug;
      const keyword = `${slug.replace(/-/g, ' ')} kepatuhan k3`.trim();

      records.push({
        section: 'regulasi-k3',
        slug,
        title: fullTitle,
        metaTitle: `${fullTitle} | Ringkasan & Kepatuhan K3`,
        description: `Ulasan hukum resmi ${fullTitle}: lingkup kewajiban kepatuhan ${item.scope}, sanksi pelanggaran hukum, checklist inspeksi, dan implementasi audit SMK3.`,
        answer: `${fullTitle} yang diterbitkan oleh ${item.enactor} pada tahun ${item.year} menetapkan kewajiban hukum kepatuhan di tempat kerja yang mencakup ${item.scope}. Regulasi ini menjadi instrumen wajib yang diverifikasi oleh Pengawas Ketenagakerjaan dan auditor sistem manajemen keselamatan kerja di seluruh Indonesia.`,
        highlights: [
          `Instansi Penerbit: ${item.enactor}`,
          `Tahun Pengundangan: ${item.year}`,
          `Ruang Lingkup: ${item.scope}`,
          'Status Hukum: Berlaku & Wajib Ditaati Seluruh Tempat Kerja'
        ],
        blocks: [
          {
            heading: `Latar Belakang & Kedudukan Hukum ${fullTitle}`,
            paragraphs: [
              `Penerbitan ${fullTitle} didasarkan pada mandat perlindungan keselamatan tenaga kerja dan penataan standar operasional fasilitas industri nasional. Regulasi ini mengikat secara hukum bagi setiap pengurus tempat kerja, pemilik aset, kontraktor, serta tenaga kerja yang berada di dalam yurisdiksi Republik Indonesia.`,
              `Ketentuan ini memuat pasal-pasal normatif mengenai ${item.scope}, penetapan standar teknis peralatan, kualifikasi kompetensi personel pelaksana, serta prosedur pengawasan berkala oleh instansi pengawas ketenagakerjaan.`
            ]
          },
          {
            heading: 'Poin Kunci Kepatuhan & Kewajiban Pengurus Perusahaan',
            paragraphs: [
              'Dalam rangka memenuhi ketentuan regulasi ini, pihak manajemen perusahaan diwajibkan untuk menjalankan langkah-langkah kepatuhan operasional:',
            ],
            bullets: [
              `Menyusun SOP dan instruksi kerja tertulis yang mengadopsi norma teknis ${fullTitle}`,
              'Memastikan seluruh peralatan kerja, mesin, atau instalasi terkait memiliki izin pemakaian dan hasil riksa uji berkala yang sah',
              'Menugaskan personel dan pengawas yang telah memiliki lisensi kewenangan kerja resmi (SIO / SKP Kemnaker)',
              'Menyediakan fasilitas keselamatan kerja dan alat pelindung diri (APD) terstandar secara cuma-cuma bagi seluruh pekerja',
              'Menyimpan seluruh dokumen catatan inspeksi, pemeliharaan, dan rekaman insiden untuk keperluan audit kepatuhan'
            ]
          },
          {
            heading: 'Sanksi Hukum & Dampak Ketidakpatuhan',
            paragraphs: [
              'Pelanggaran terhadap ketentuan regulasi ini dapat berakibat pada diterbitkannya Nota Pemeriksaan Pengawas Ketenagakerjaan, sanksi administratif berupa penghentian sementara kegiatan operasional, kegagalan dalam audit sertifikasi SMK3 PP 50/2012, pembatalan keikutsertaan lelang tender proyek, hingga ancaman sanksi pidana kurungan dan denda sesuai ketentuan undang-undang ketenagakerjaan yang berlaku.'
            ]
          },
          {
            heading: 'Layanan Konsultasi Kepatuhan di PT Kreasi Ultimate Berjaya',
            paragraphs: [
              'PT Kreasi Ultimate Berjaya menyediakan layanan pendampingan audit kepatuhan hukum K3 (Legal Compliance Audit), penyusunan matriks register regulasi, serta penyelenggaraan program pelatihan sertifikasi resmi untuk memastikan seluruh elemen tempat kerja Anda memenuhi persyaratan regulasi ini secara tuntas.'
            ]
          }
        ],
        faqs: [
          { question: `Siapa yang berwenang mengawasi pelaksanaan ${fullTitle}?`, answer: `Pengawasan dilakukan oleh Pejabat Fungsional Pengawas Ketenagakerjaan di tingkat Dinas Tenaga Kerja Provinsi dan Kementerian Ketenagakerjaan RI, didampingi oleh Auditor SMK3 independen saat proses sertifikasi.` },
          { question: `Dokumen apa saja yang wajib disiapkan perusahaan untuk membuktikan kepatuhan terhadap ${fullTitle}?`, answer: 'Dokumen mencakup SOP kerja aman, rekaman izin kerja (PTW), logbook pemeliharaan alat, sertifikat kelaikan riksa uji instalasi, lisensi personil (SIO/SKP), dan bukti sosialisasi K3 kepada tenaga kerja.' },
          { question: `Bagaimana jika ada pertentangan antara standar internal perusahaan dengan ${fullTitle}?`, answer: 'Sesuai asas hukum perundang-undangan, norma keselamatan kerja dalam regulasi pemerintah bersifat standar minimum (mandatory). Perusahaan boleh menerapkan standar yang lebih ketat, namun tidak boleh berada di bawah ketentuan minimum regulasi nasional.' }
        ],
        related: ['pelatihan/ahli-k3-umum', 'panduan/syarat-ahli-k3-umum', 'perbandingan/bnsp-vs-kemnaker', 'jadwal'],
        sources: [src, officialSources.uu1, officialSources.pp50],
        status: 'published',
        publishedAt: '2026-08-01',
        updatedAt: '2026-09-01',
        indexable: true,
        intent: `regulasi k3 ${slug} pasal kepatuhan hukum audit`,
        primaryKeyword: keyword,
        searchIntent: `isi pasal, kewajiban kepatuhan hukum, sanksi, dan audit ${fullTitle}`,
        intentType: 'informational',
        parentTopic: `Regulasi K3 ${c.category}`,
        cannibalizationGroup: `regulasi-${c.prefix.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
        contentKind: 'regulation',
        primaryCtaText: `Konsultasi Kepatuhan ${fullTitle.split('(')[0].trim()}`,
        primaryCtaIntent: 'perusahaan',
        secondaryCtaText: 'Tanya Program Pelatihan Terkait',
        secondaryCtaIntent: 'jadwal'
      });
    }
  }

  return records;
}
